### ISSUE TITLE
mixxx crashes

### ISSUE THREAD

**Issue by cr6git** [void-linux/void-packages#1126]
### System

* xuname:  `Void 4.17.6_1 x86_64 GenuineIntel uptodate rrFFFFFFFFFFFFFFFFFF`

* package:  `mixxx-2.1.1_2`

### Actual behavior
mixxx crashes when opening a folder containing mp3 files...
### Steps to reproduce the behavior
Start `mixxx`
Try to open a folder containing an mp3 file to mix...
It crashes instantaneously:
````
*** Error in `mixxx': munmap_chunk(): invalid pointer: 0x00007ff110078ef0 ***
Abandon
````

**Comment by jnbr** [comment]
here is a backtrace:

```
#0  0x00007ffff047e920 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff047fffd in __GI_abort () at abort.c:90
#2  0x00007ffff04c09dd in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff05c6d78 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff04c706c in malloc_printerr (action=<optimized out>, str=0x7ffff05c6dd0 "munmap_chunk(): invalid pointer", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5425
#4  0x00007ffff3402e7e in TagLib::ByteVector::ByteVectorPrivate::~ByteVectorPrivate() () at /usr/lib/libtag.so.1
#5  0x00007ffff33ffaa0 in TagLib::ByteVector::~ByteVector() () at /usr/lib/libtag.so.1
#6  0x00007ffff3400ce7 in TagLib::ByteVector::operator=(TagLib::ByteVector const&) () at /usr/lib/libtag.so.1
#7  0x00007ffff33d5cfe in TagLib::ID3v2::Frame::Header::setData(TagLib::ByteVector const&, unsigned int) () at /usr/lib/libtag.so.1
#8  0x00007ffff33cc57e in TagLib::ID3v2::FrameFactory::createFrame(TagLib::ByteVector const&, TagLib::ID3v2::Header*) const () at /usr/lib/libtag.so.1
#9  0x00007ffff33d1625 in TagLib::ID3v2::Tag::parse(TagLib::ByteVector const&) () at /usr/lib/libtag.so.1
#10 0x00007ffff33d1a2a in TagLib::ID3v2::Tag::read() () at /usr/lib/libtag.so.1
#11 0x00007ffff33d1b9f in TagLib::ID3v2::Tag::Tag(TagLib::File*, long, TagLib::ID3v2::FrameFactory const*) () at /usr/lib/libtag.so.1
#12 0x00007ffff33c8e0f in TagLib::MPEG::File::read(bool) () at /usr/lib/libtag.so.1
#13 0x00007ffff33c9054 in TagLib::MPEG::File::File(char const*, bool, TagLib::AudioProperties::ReadStyle) () at /usr/lib/libtag.so.1
#14 0x0000555555cf9add in mixxx::MetadataSourceTagLib::importTrackMetadataAndCoverImage(mixxx::TrackMetadata*, QImage*) const (this=0x7ffecc00a868, pTrackMetadata=0x0, pCoverImage=0x7ffec6f54930)
    at src/sources/metadatasourcetaglib.cpp:131
#15 0x0000555555d228cf in SoundSourceProxy::importCoverImage() const (this=this@entry=0x7ffec6f549c0) at src/sources/soundsourceproxy.cpp:610
#16 0x0000555555d2992a in SoundSourceProxy::importTemporaryCoverImage(QFileInfo, QSharedPointer<SandboxSecurityToken>) (fileInfo=..., pSecurityToken=...) at src/sources/soundsourceproxy.cpp:327
#17 0x0000555555a640e6 in CoverArtUtils::extractEmbeddedCover(QFileInfo, QSharedPointer<SandboxSecurityToken>) (fileInfo=..., pToken=...) at src/library/coverartutils.cpp:42
#18 0x0000555555a64229 in CoverArtUtils::extractEmbeddedCover(QFileInfo) (fileInfo=...) at src/library/coverartutils.cpp:34
#19 0x0000555555a64764 in CoverArtUtils::loadCover(CoverInfo const&) (info=...) at src/library/coverartutils.cpp:53
#20 0x0000555555a5bcb3 in CoverArtCache::loadCover(CoverInfo const&, QObject const*, int, bool) (this=<optimized out>, info=..., pRequestor=0x5555793634e0, desiredWidth=90, signalWhenDone=<optimized out>)
    at src/library/coverartcache.cpp:127
#21 0x0000555555a5f212 in non-virtual thunk to QtConcurrent::RunFunctionTask<CoverArtCache::FutureResult>::run() () at /usr/include/qt5/QtConcurrent/qtconcurrentrunbase.h:112
#22 0x00007ffff47628e2 in  () at /usr/lib/libQt5Core.so.5
#23 0x00007ffff47657ff in  () at /usr/lib/libQt5Core.so.5
#24 0x00007ffff2667568 in start_thread (arg=0x7ffec6f55700) at pthread_create.c:465
#25 0x00007ffff053e52f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
@cr6git can you test if it still fails with a rebuilt taglib?

**Comment by jnbr** [comment]
mixxx and protobuf have been rebuilt. Shouldn't be an issue anymore.
