### ISSUE TITLE
ReText package requires more dependencies

### ISSUE THREAD

**Issue by alihardan** [void-linux/void-packages#11525]
### System

* xuname:  
~~~
$ xuname
dmesg: read kernel buffer failed: Operation not permitted
Void 4.19.39_1 i686 GenuineIntel notuptodate rFF
~~~
* package:  ReText

### The problem

I installed ReText package. When I try to run it, it says `The 'python-markdown-math' distribution was not found and is required by the application`.

There are not exists `python-markdown-math` in Void Linux packages.

The output of CLI:

~~~
$ retext
Using configuration file: /home/ali/.config/ReText project/ReText.conf
Traceback (most recent call last):
  File "/bin/retext", line 111, in <module>
    main()
  File "/bin/retext", line 79, in main
    window = ReTextWindow()
  File "/usr/lib/python3.6/site-packages/ReText/window.py", line 217, in __init__
    availableMarkups = markups.get_available_markups()
  File "/usr/lib/python3.6/site-packages/markups/__init__.py", line 33, in get_available_markups
    for markup in get_all_markups():
  File "/usr/lib/python3.6/site-packages/markups/__init__.py", line 23, in get_all_markups
    return [entry_point.load() for entry_point in entry_points]
  File "/usr/lib/python3.6/site-packages/markups/__init__.py", line 23, in <listcomp>
    return [entry_point.load() for entry_point in entry_points]
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2345, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2368, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-markdown-math' distribution was not found and is required by the application
~~~

**Note:** I think maybe ReText is not who needs this package, maybe it's python3-markup, which is one of ReText dependencies.

Look at Arch packages:

https://www.archlinux.org/packages/community/any/python-markups/

python-markups required by retext and python-markups requires python-markdown-math.

**Comment by hfel** [comment]
I have the same problem.

**Comment by r0m3chco** [comment]
me too
