### ISSUE TITLE
bzr python error

### ISSUE THREAD

**Issue by rapha8l** [void-linux/void-packages#11990]
### System

* xuname:  
 Void 5.0.19_1 x86_64 GenuineIntel notuptodate rrrmFFFFF

* package:  
 Bzr

### Steps to reproduce the behavior
Launch bzr :

bzr: ERROR: exceptions.TypeError: first argument must be string or compiled pattern

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bzrlib/commands.py", line 930, in exception_to_return_code
    return the_callable(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bzrlib/commands.py", line 1082, in run_bzr
    get_cmd_object('help').run_argv_aliases([])
  File "/usr/lib/python2.7/site-packages/bzrlib/commands.py", line 673, in run_argv_aliases
    return self.run(**all_cmd_args)
  File "/usr/lib/python2.7/site-packages/bzrlib/commands.py", line 697, in run
    return self._operation.run_simple(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bzrlib/cleanup.py", line 136, in run_simple
    self.cleanups, self.func, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bzrlib/cleanup.py", line 166, in _do_with_cleanups
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bzrlib/commands.py", line 1138, in ignore_pipe
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bzrlib/builtins.py", line 4852, in run
    bzrlib.help.help(topic)
  File "/usr/lib/python2.7/site-packages/bzrlib/help.py", line 54, in help
    outfile.write(source.get_help_text(shadowed_terms))
  File "/usr/lib/python2.7/site-packages/bzrlib/help_topics/__init__.py", line 895, in get_help_text
    i18n.install()
  File "/usr/lib/python2.7/site-packages/bzrlib/i18n.py", line 92, in install
    _translations = install_translations(lang)
  File "/usr/lib/python2.7/site-packages/bzrlib/i18n.py", line 114, in install_translations
    fallback=True)
  File "/usr/lib/python2.7/gettext.py", line 554, in translation
    t = _translations.setdefault(key, class_(fp))
  File "/usr/lib/python2.7/gettext.py", line 255, in __init__
    self._parse(fp)
  File "/usr/lib/python2.7/gettext.py", line 391, in _parse
    self.plural = c2py(plural)
  File "/usr/lib/python2.7/gettext.py", line 177, in c2py
    result, nexttok = _parse(_tokenize(plural))
  File "/usr/lib/python2.7/gettext.py", line 114, in _parse
    nexttok = next(tokens)
  File "/usr/lib/python2.7/gettext.py", line 85, in _tokenize
    for mo in re.finditer(_token_pattern, plural):
  File "/usr/lib/python2.7/re.py", line 190, in finditer
    return _compile(pattern, flags).finditer(string)
  File "/usr/lib/python2.7/re.py", line 247, in _compile
    raise TypeError, "first argument must be string or compiled pattern"
TypeError: first argument must be string or compiled pattern

bzr 2.7.0 on python 2.7.16 (Linux-5.0.19_1-x86_64-with-glibc2.2.5)
arguments: ['/sbin/bzr']
plugins: bash_completion[2.7.0], bzrtools[2.6.0], changelog_merge[2.7.0],
    etckeeper[unknown], grep[2.7.0], launchpad[2.7.0],
    netrc_credential_store[2.7.0], news_merge[2.7.0], po_merge[2.7.0],
    weave_fmt[2.7.0]
encoding: 'utf-8', fsenc: 'UTF-8', lang: 'fr_FR.UTF-8'

*** Bazaar has encountered an internal error.  This probably indicates a
    bug in Bazaar.  You can help us fix it by filing a bug report at
        https://bugs.launchpad.net/bzr/+filebug
    including this traceback and a description of the problem.

**Comment by rapha8l** [comment]
Maybe related to this :
https://bugzilla.redhat.com/show_bug.cgi?id=1417084

**Comment by CameronNemo** [comment]
There is a fork, brz or something. Should be python 3 compatible and a drop in replacement.

**Comment by rapha8l** [comment]
Thanks, it may be this https://www.breezy-vcs.org/
