### ISSUE TITLE
ImportError: No module named matemenu

### ISSUE THREAD

**Issue by Atlanelan** [void-linux/void-packages#12004]
When I try to edit mate menu by running mozo through terminal the following error occurs:

~]$ mozo

Traceback (most recent call last):

File "/usr/bin/mozo", line 22, in <module> from Mozo.MainWindow import MainWindow File "/usr/lib/python2.7/site-packages/Mozo/MainWindow.py", line 19, in <module> import matemenu

ImportError: No module named matemenu

When I open mate menu (Advanced Mate Menu) plugin from panel this message shows:

Couldn't load plugin: applications

Traceback (most reent call last):

File "/usr/lib/mate-menu/mate-menu.py", line 202, in PopulatePlugins exec("from {plugin_module} import pluginclass".format(plugin_module=plugin_module))

File "<string>", line 1, in <module>

File "/usr/lib/python2.7/site-packages/mate_menu/plugins/applications.py", line 38, in <module> import matemenu

ImportError: No module named matemenu.

**Comment by jnbr** [comment]
This was fixed in #12001
