### ISSUE TITLE
vdpauinfo: segfault

### ISSUE THREAD

**Issue by ackalker** [void-linux/void-packages#12717]
### System

* xuname:  
  Void 5.1.15_1 x86_64 GenuineIntel uptodate rrrrmdFFFFFFFFF
* package:  
  vdpauinfo-1.0_3

### Expected behavior

Running `vdpauinfo` should output VDPAU capabilities without crashing.

### Actual behavior

Running `vdpauinfo` on my system produces a segmentation fault without any other output.

### Steps to reproduce the behavior

* While running X, in a terminal run the command `vdpauinfo`

### Additional notes

* Graphics card
  NVIDIA GM107 [GeForce GTX 750]
* Video driver
  nouveau

I suspected that this could be a library issue, so I ran the tool again using `LD_DEBUG=libs`. The last bit of output on my system is (full output [here](https://gist.github.com/b58b979e3859d4862d96e15e06809758)):

```sh
$ LD_DEBUG=libs vdpauinfo
[...]
      3793:	calling init: /usr/lib/vdpau/libvdpau_nouveau.so.1
      3793:	
      3793:	find library=libnss_files.so.2 [0]; searching
      3793:	 search cache=/etc/ld.so.cache
      3793:	  trying file=/usr/lib/libnss_files.so.2
      3793:	
      3793:	
      3793:	calling init: /usr/lib/libnss_files.so.2
      3793:	

Segmentation fault
```

So it looks like the crash occurs while trying to init `libnss_files.so.2`, and in any case before control is transferred to `vdpauinfo` binary.
I'm wondering: could the recent `glibc` update be the culprit?

**Comment by ackalker** [comment]
Anyway, after installing the `mesa-ati-dri-dbg` package, I get the following backtrace with a bit more detail:
```sh
$ gdb -q vdpauinfo
Reading symbols from vdpauinfo...
Reading symbols from /usr/lib/debug//usr/bin/vdpauinfo...
(gdb) directory /masterdir/builddir/mesa-19.1.1/build
Source directories searched: /masterdir/builddir/mesa-19.1.1/build:$cdir:$cwd
(gdb) set pagination off 
(gdb) run
Starting program: /usr/bin/vdpauinfo 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
display: :0   screen: 0
warning: the debug information found in "/usr/lib/vdpau/libvdpau_r300.so.1.0.0" does not match "/usr/lib/vdpau/libvdpau_nouveau.so.1" (CRC mismatch).

[New Thread 0x7fffefbda700 (LWP 23390)]

Thread 1 "vdpauinfo" received signal SIGSEGV, Segmentation fault.
nv50_ir::AlgebraicOpt::handleCVT_CVT (this=<optimized out>, cvt=0x555555802590)
    at ../src/gallium/drivers/nouveau/codegen/nv50_ir_peephole.cpp:2085
2085	   if (insn->saturate ||
(gdb) bt
#0  nv50_ir::AlgebraicOpt::handleCVT_CVT (this=<optimized out>, cvt=0x555555802590) at ../src/gallium/drivers/nouveau/codegen/nv50_ir_peephole.cpp:2085
#1  0x00007ffff72c1696 in nv50_ir::AlgebraicOpt::visit (this=0x7fffffffc140, bb=<optimized out>) at ../src/gallium/drivers/nouveau/codegen/nv50_ir_peephole.cpp:2351
#2  0x00007ffff7288210 in nv50_ir::Pass::doRun (this=0x7fffffffc140, func=<optimized out>, ordered=<optimized out>, skipPhi=false) at ../src/gallium/drivers/nouveau/codegen/nv50_ir_bb.cpp:500
#3  0x00007ffff72882bf in nv50_ir::Pass::doRun (this=0x7fffffffc140, prog=<optimized out>, ordered=false, skipPhi=false) at ../src/gallium/drivers/nouveau/codegen/nv50_ir_inlines.h:413
#4  0x00007ffff72b0deb in nv50_ir::Program::optimizeSSA (this=this@entry=0x5555557ecdb0, level=3) at ../src/gallium/drivers/nouveau/codegen/nv50_ir_peephole.cpp:4005
#5  0x00007ffff72859b7 in nv50_ir_generate_code (info=info@entry=0x5555558440b0) at ../src/gallium/drivers/nouveau/codegen/nv50_ir.cpp:1267
#6  0x00007ffff72ddceb in nvc0_program_translate (prog=prog@entry=0x55555582b5a0, chipset=<optimized out>, debug=debug@entry=0x5555557e7798) at ../src/gallium/drivers/nouveau/nvc0/nvc0_program.c:638
#7  0x00007ffff72e5dac in nvc0_cp_state_create (pipe=0x5555557e73d0, cso=0x7fffffffce20) at ../src/gallium/drivers/nouveau/nvc0/nvc0_context.h:292
#8  0x00007ffff70034f3 in vl_compositor_cs_create_shader (c=c@entry=0x5555557c18b8, compute_shader_text=<optimized out>) at ../src/gallium/auxiliary/vl/vl_compositor_cs.c:433
#9  0x00007ffff6ffcf2a in init_shaders (c=0x5555557c18b8) at ../src/gallium/auxiliary/vl/vl_compositor.c:74
#10 vl_compositor_init (c=c@entry=0x5555557c18b8, pipe=<optimized out>) at ../src/gallium/auxiliary/vl/vl_compositor.c:767
#11 0x00007ffff6fecdcb in vdp_imp_device_create_x11 (display=<optimized out>, screen=<optimized out>, device=0x7fffffffe03c, get_proc_address=0x7fffffffdfd8) at ../src/gallium/state_trackers/vdpau/device.c:129
#12 0x00007ffff7e6daf5 in vdp_device_create_x11 () from /usr/lib/libvdpau.so.1
#13 0x00005555555554ad in main (argc=<optimized out>, argv=0x7fffffffe168) at vdpauinfo.cpp:488
(gdb) print insn
$1 = (nv50_ir::Instruction *) 0x0
(gdb) # boom! that's guaranteed to blow up yeah...
```
Although there's still a warning, at least the symbol names now look reasonable.

**Comment by ericonr** [comment]
Is this still happening? vdpau and friends are very mysterious...
