### ISSUE TITLE
rtorrent: segfault

### ISSUE THREAD

**Issue by samukhin** [void-linux/void-packages#13113]
### System
* xuname:
  Void 4.19.55_1 x86_64 GenuineIntel uptodate rrFFF
* package:
  rtorrent-0.9.7_4 curl-7.65.1_2 libcurl-7.65.1_2

### Expected behavior
rtorrent just works without crashes

### Actual behavior
rtorrent segfaults after starting some torrent

```
(gdb) bt
#0  0x00007ffff7ef5d00 in sh_delentry () from /usr/lib/libcurl.so.4
#1  0x00007ffff7ef7009 in Curl_multi_closed () from /usr/lib/libcurl.so.4
#2  0x00007ffff7ef3ed9 in Curl_closesocket () from /usr/lib/libcurl.so.4
#3  0x00007ffff7ee5398 in Curl_disconnect () from /usr/lib/libcurl.so.4
#4  0x00007ffff7ef79a7 in multi_done () from /usr/lib/libcurl.so.4
#5  0x00007ffff7ef9a04 in curl_multi_remove_handle () from /usr/lib/libcurl.so.4
#6  0x0000555555675934 in ?? ()
#7  0x0000555555677eb5 in ?? ()
#8  0x00007ffff7e8108b in ?? () from /usr/lib/libtorrent.so.20
#9  0x00007ffff7de90ca in torrent::TrackerList::close_all_excluding(int) () from /usr/lib/libtorrent.so.20
#10 0x00007ffff7de8051 in torrent::TrackerController::enable(int) () from /usr/lib/libtorrent.so.20
#11 0x00007ffff7dca55c in torrent::Download::start(int) () from /usr/lib/libtorrent.so.20
#12 0x00005555556515d9 in ?? ()
#13 0x00005555556588af in ?? ()
#14 0x00007ffff7e54ece in ?? () from /usr/lib/libtorrent.so.20
#15 0x00007ffff7dc7c0e in ?? () from /usr/lib/libtorrent.so.20
#16 0x00007ffff7e1c3fc in torrent::thread_base::event_loop(torrent::thread_base*) () from /usr/lib/libtorrent.so.20
#17 0x000055555558a359 in ?? ()
#18 0x00007ffff731db6b in __libc_start_main (main=0x555555589470, argc=1, argv=0x7fffffffe6b8, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe6a8) at ../csu/libc-start.c:308
#19 0x000055555558ac2a in ?? ()
```

### Steps to reproduce the behavior
Launch rtorrent with at least one torrent, press Ctrl+s to start it.

**Comment by jnbr** [comment]
Can you test if #13193 fixes the issue?

**Comment by samukhin** [comment]
> Can you test if #13193 fixes the issue?

Yes, now it works.
