### ISSUE TITLE
python3-cryptography: gives an error: X25519 is not supported by this version of OpenSSL

### ISSUE THREAD

**Issue by user318** [void-linux/void-packages#13584]
### System

* xuname:  Void 4.19.60_1 x86_64 GenuineIntel notuptodate rF
* package:  python3-cryptography-2.4.2_2

### Expected behavior

It is expected to work with x25519.

### Actual behavior

It returns an error when I try to generate x25519 key.

### Steps to reproduce the behavior

```
$ python
Python 3.6.9 (default, Jul  5 2019, 09:47:14) 
[GCC 9.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey
>>> private_key = X25519PrivateKey.generate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/cryptography/hazmat/primitives/asymmetric/x25519.py", line 39, in generate
    _Reasons.UNSUPPORTED_EXCHANGE_ALGORITHM
cryptography.exceptions.UnsupportedAlgorithm: X25519 is not supported by this version of OpenSSL.
>>> from cryptography.hazmat.backends import default_backend
>>> default_backend().x25519_generate_key()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 2067, in x25519_generate_key
    self.openssl_assert(evp_pkey_ctx != self._ffi.NULL)
  File "/usr/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 115, in openssl_assert
    return binding._openssl_assert(self._lib, ok)
  File "/usr/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 77, in _openssl_assert
    errors_with_text
cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=117436572, lib=6, func=4095, reason=156, reason_text=b'error:06FFF09C:digital envelope routines:CRYPTO_internal:unsupported algorithm')])
```

**Comment by xtraeme** [comment]
This seems to be a specific libressl issue

**Comment by ericonr** [comment]
Will be fixed with a switch to OpenSSL, nothing to be acted on specifically.
