### ISSUE TITLE
docker-compose currently broken

### ISSUE THREAD

**Issue by leonardlorenz** [void-linux/void-packages#13786]
### Some description
The current docker-compose that is up in the repos is broken. I downloaded the v1.24.1 tag from the docker/compose Github and ran the binary, which works flawlessly.

I'm suggesting to tell users to downgrade their docker-compose. I'm going to write an issue on docker/compose too.

### System

* xuname:  
Void 5.1.21_1 x86_64 GenuineIntel uptodate rrmFFF
* package:  
- docker-compose

### Expected behavior

`docker-compose --version` outputs version as in
```
λ ./docker-compose-Linux-x86_64 --version
docker-compose version 1.24.1, build 4667896b
```

### Actual behavior

```
Traceback (most recent call last):
  File "/home/mtrx/.local/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 17, in <module>
    import docker
  File "/usr/lib/python3.6/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/lib/python3.6/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 8, in <module>
    import websocket
  File "/usr/lib/python3.6/site-packages/websocket/__init__.py", line 22, in <module>
    from ._abnf import *
  File "/usr/lib/python3.6/site-packages/websocket/_abnf.py", line 34, in <module>
    import numpy
  File "/usr/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3.6/site-packages/numpy/core/__init__.py", line 97, in <module>
    from . import _add_newdocs
  File "/usr/lib/python3.6/site-packages/numpy/core/_add_newdocs.py", line 6839, in <module>
    """.format(ftype=float_name)))
  File "/usr/lib/python3.6/site-packages/numpy/core/function_base.py", line 467, in add_newdoc
    _add_docstring(getattr(new, doc[0]), doc[1].strip())
AttributeError: type object 'numpy.float16' has no attribute 'as_integer_ratio'
```

### Steps to reproduce the behavior
```
sudo xbps-install -S docker docker-compose
sudo docker-compose --version
```

**Comment by leonardlorenz** [comment]
Cause for this problem was a broken python installation. Reinstalling some packages with --user flag fixed it.
