### ISSUE TITLE
Mumble: Segmentation fault

### ISSUE THREAD

**Issue by shumvgolove** [void-linux/void-packages#14222]
Mumble segfaults on startup:
```
Locale is "en_US" (System: "en_US")
TextToSpeech: Failed to contact speech dispatcher.
Database SQLite: "3.29.0"
Overlay: Removing old socket on "/home/sh/.MumbleOverlayPipe"
Overlay: Listening on "/home/sh/.MumbleOverlayPipe"
GlobalShortcutX: Using XI2 2.3
SocketRPC: Removing old socket on "/home/sh/.MumbleSocket"
AudioInput: 96000 bits/s, 48000 hz, 480 sample
OSSOutput: Initialized
Segmentation fault
```
`$ dmesg` returns this error:
```
[ 1536.944422] OSSInput[5914]: segfault at 10 ip 00005555d798adea sp 00007f277e03c950 error 4 in mumble[5555d780d000+1bd000]
[ 1536.944426] Code: 55 48 89 e5 41 57 41 56 41 55 41 54 53 48 89 fb 48 83 ec 38 4c 8b 25 a5 1d 2e 00 64 48 8b 04 25 28 00 00 00 48 89 45 c8 31 c0 <49> 8b 44 24 10 8b 48 14 85 c9 0f 85 c6 02 00 00 48 8d 05 7f 18 2e
```

I think [this](https://github.com/mumble-voip/mumble/issues/3685) is related to issue.

**Comment by Duncaen** [comment]
Bets way to find out if its related would be to install `mumble-dbg` and then running mumble with gdb and producing a backtrace.

**Comment by shumvgolove** [comment]
Sorry, but how can I install `mumble-dbg`? There is no such thing in repository...

**Comment by Duncaen** [comment]
https://docs.voidlinux.org/xbps/repositories/official/debug.html

**Comment by shumvgolove** [comment]
Thank you!

```
(gdb) bt
#0  OSSInput::run (this=0x555555e84460) at OSS.cpp:208
#1  0x00007ffff617123b in ?? () from /lib/libQtCore.so.4
#2  0x00007ffff7fb5a21 in start (p=<optimized out>)
    at src/thread/pthread_create.c:195
#3  0x00007ffff7fc319b in __clone ()
    at src/thread/x86_64/clone.s:22
Backtrace stopped: frame did not save the PC
```

**Comment by kotajacob** [comment]
same issue
```
(gdb) bt
#0  OSSInput::run (this=0x555555cfb640) at OSS.cpp:208
#1  0x00007ffff61cdfc6 in ?? () from /usr/lib/libQtCore.so.4
#2  0x00007ffff6104f27 in start_thread (arg=<optimized out>) at pthread_create.c:479
#3  0x00007ffff5c60e0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)
```

**Comment by Hoshpak** [comment]
I could reproduce it on one of my systems but not on the other. However I would also tend to just disable OSS support since it's not shipped with the kernel and there are no OSS packages in the repository so OSS support in mumble should be no use for regular Void setups anyway.

**Comment by kotajacob** [comment]
I just tested adding no-oss to the template and recompiling and it is running fine on my system now.

**Comment by shumvgolove** [comment]
Thanks!
