### ISSUE TITLE
pylint: 'astroid<3,>=2.2.0' distribution was not found and is required by pylint

### ISSUE THREAD

**Issue by AN3223** [void-linux/void-packages#14441]
### System

* xuname:  Void 5.2.14_1 x86_64 GenuineIntel uptodate rrrmFFF
* package:  pylint-2.3.1_1 python3-pylint-2.3.1_1

### Expected behavior
Should run

### Actual behavior
Throws an exception:
```
Traceback (most recent call last):
  File "/bin/pylint", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'astroid<3,>=2.2.0' distribution was not found and is required by pylint
```

### Steps to reproduce the behavior
`$ pylint2`
or
`$ pylint3`

**Comment by AN3223** [comment]
@Hoshpak Now I got `pkg_resources.DistributionNotFound: The 'typed-ast>=1.3.0' distribution was not found and is required by astroid` when trying to run pylint3 (works fine after installing python3-typed-ast).

**Comment by Hoshpak** [comment]
That's strange. I explicitely added the dependency to pylint, it seems the builders failed to pick it up. However it's indeed a dependency of astroid and not pylint. I fixed that now.
