### ISSUE TITLE
docker-compose broken

### ISSUE THREAD

**Issue by DirectorX** [void-linux/void-packages#14451]
### System

* xuname:  
  Void 5.2.14_1 x86_64 GenuineIntel/KVM uptodate rFFFFF
* package:  
  - docker-19.03.2_1
  - docker-compose-1.24.1_2
  - python3-3.6.9_1
  - python3-jsonschema-3.0.2_1

### Expected behavior
`docker-compose --version` successfully prints version and other info

### Actual behavior
```bash
➜  ~ docker-compose --version
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (jsonschema 3.0.2 (/usr/lib/python3.6/site-packages), Requirement.parse('jsonschema<3,>=2.5.1'), {'docker-compose'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jsonschema<3,>=2.5.1' distribution was not found and is required by docker-compose

```

**Comment by DirectorX** [comment]
353efa4ce3e0bed1c704981b57ac1c9f983a4bbf

**Comment by DirectorX** [comment]
https://github.com/void-linux/void-packages/commit/11545efb61b6c0fd8af79d9a12e54e54c7c46a88
