### ISSUE TITLE
pavucontrol segfaults on volume change

### ISSUE THREAD

**Issue by jnbr** [void-linux/void-packages#15505]
### System

* xuname:  
 Void 5.2.18_1 x86_64-musl GenuineIntel uptodate rFFFFFFFFFFFFFFFFFFF
* package:  
  pavucontrol-4.0_1

### Expected behavior

pavucontrol should be able to change the output volume

### Actual behavior

segfaults:

```
#0  0x00007ffff56da4dc in _XInternAtom (dpy=dpy@entry=0x5555555f38d0, name=name@entry=0x55555566a900 "_NET_WM_DESKTOP", onlyIfExists=onlyIfExists@entry=0, psig=psig@entry=0x7fffffffdee8,
    pidx=pidx@entry=0x7fffffffdee0, pn=pn@entry=0x7fffffffdee4) at IntAtom.c:84
#1  0x00007ffff56da9ab in XInternAtom (dpy=0x5555555f38d0, name=name@entry=0x55555566a900 "_NET_WM_DESKTOP", onlyIfExists=onlyIfExists@entry=0) at IntAtom.c:175
#2  0x00007ffff6006d70 in gdk_x11_atom_to_xatom_for_display (atom=0x50, display=0x555555629040) at gdkproperty-x11.c:115
#3  gdk_x11_atom_to_xatom_for_display (display=0x555555629040, atom=0x50) at gdkproperty-x11.c:96
#4  0x00007ffff727e34f in window_get_desktop (w=0x555555afe550, d=0x555555629040) at canberra-gtk.c:188
#5  ca_gtk_proplist_set_for_widget (p=0x555555d34be0, widget=widget@entry=0x555555bd3420) at canberra-gtk.c:271
#6  0x00007ffff727ed4a in ca_gtk_play_for_widget (w=0x555555bd3420, id=id@entry=2) at canberra-gtk.c:445
#7  0x0000555555595f5d in SinkWidget::executeVolumeUpdate (this=<optimized out>) at /usr/include/gtkmm-3.0/gtkmm/hvbox.h:112
#8  SinkWidget::executeVolumeUpdate (this=<optimized out>) at sinkwidget.cc:89
#9  0x0000555555590356 in DeviceWidget::timeoutEvent (this=<optimized out>) at devicewidget.cc:175
#10 0x00007ffff74ea082 in sigc::slot0<bool>::operator() (this=<error reading variable: value has been optimized out>) at /usr/include/sigc++-2.0/sigc++/functors/slot_base.h:335
#11 (anonymous namespace)::glibmm_source_callback (data=<error reading variable: value has been optimized out>) at main.cc:243
#12 0x00007ffff6857464 in g_timeout_dispatch (source=0x555555be24a0, callback=<optimized out>, user_data=<optimized out>) at ../glib/gmain.c:4668
#13 0x00007ffff685c42e in g_main_dispatch (context=0x55555563a320) at ../glib/gmain.c:3179
#14 g_main_context_dispatch (context=context@entry=0x55555563a320) at ../glib/gmain.c:3844
#15 0x00007ffff685e310 in g_main_context_iterate (context=context@entry=0x55555563a320, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:3917
#16 0x00007ffff685e34f in g_main_context_iteration (context=context@entry=0x55555563a320, may_block=may_block@entry=1) at ../glib/gmain.c:3978
#17 0x00007ffff589664d in g_application_run (application=0x5555555f9210, argc=argc@entry=1, argv=argv@entry=0x7fffffffe508) at ../gio/gapplication.c:2559
#18 0x00007ffff760e471 in Gio::Application::run (this=this@entry=0x7fffffffe3a0, argc=argc@entry=1, argv=argv@entry=0x7fffffffe508) at ../giomm/application.h:283
#19 0x00007ffff7cd2565 in Gtk::Application::run (this=this@entry=0x7fffffffe3a0, argc=argc@entry=1, argv=argv@entry=0x7fffffffe508) at application.cc:137
#20 0x000055555558bf69 in main (argc=1, argv=0x7fffffffe508) at pavuapplication.cc:182
```

### Steps to reproduce the behavior

change output volume in pavucontrol

**Comment by jnbr** [comment]
Doesn't happen with xorg/i3, only with wayland/sway.

**Comment by vpzomtrrfrt** [comment]
See https://gitlab.freedesktop.org/pulseaudio/pavucontrol/issues/68

**Comment by vpzomtrrfrt** [comment]
I think this is a libcanberra issue, it seems to be fixed upstream but without a release.

**Comment by jnbr** [comment]
Thank you for the link. Could you point me to the libcanberra source you are using?
The last commit on git://git.0pointer.de/libcanberra is from 2012.

**Comment by jnbr** [comment]
nvm, I didn't notice that this very commit from 2012 hasn't found it's way into a release yet.

**Comment by xtraeme** [comment]
So let's merge this change

**Comment by jnbr** [comment]
Yes, I'm on it.
