### ISSUE TITLE
edit frame tool broken on mypaint package

### ISSUE THREAD

**Issue by Chili-Bebber** [void-linux/void-packages#17841]
### System

* xuname:  
  ``Void 5.3.18_1 x86_64 GenuineIntel uptodate rrrmFFFF``
* affected package(s) including the version
  ``mypaint 1.2.1_5``

### Expected behavior
    the edit frame tool has its correct icon and works
### Actual behavior
    the edit frame tool has a missing icon and throws this error when you try to use it:
```python
Mypaint version: 1.2.1+gitexport.bcf5a28d
System information: Linux-5.3.18_1-x86_64-with-glibc2.2.5
Using: Python 2.7.17, GTK 3.24.13, GdkPixbuf 2.40.0, Cairo 1.16.0, GLib 2.60.1
Traceback (most recent call last):
  File "/usr/share/mypaint/gui/document.py", line 2030, mode_radioaction_changed_cb(self=<gui.document.Document object>, action=<Gtk.RadioAction object at 0x7f391dae54b0 (GtkRadioAction at 0x7f3910003e10)>, current_action=<Gtk.RadioAction object at 0x7f391dae5550 (GtkRadioAction at 0x5566d43e7540)>)
                    mode = mode_class()
                self.modes.context_push(mode)
  variables: {'self.modes.context_push': ('local', <bound method ModeStack.context_push of <ModeStack [FrameEditMode]>>), 'mode': ('local', <gui.framewindow.FrameEditMode object at 0x7f391d0e6750>)}
  File "/usr/share/mypaint/gui/mode.py", line 1307, context_push(self=<ModeStack [FrameEditMode]>, mode=<gui.framewindow.FrameEditMode object>)
            self._stack.append(mode)
            mode.enter(doc=self._doc)
            self.changed(old=old_mode, new=mode)
  variables: {'doc': (None, []), 'self._doc': ('local', <gui.document.Document object at 0x7f391db39650>), 'mode.enter': ('local', <bound method FrameEditMode.enter of <gui.framewindow.FrameEditMode object at 0x7f391d0e6750>>)}
  File "/usr/share/mypaint/gui/framewindow.py", line 120, enter(self=<gui.framewindow.FrameEditMode object>, doc=<gui.document.Document object>, **kwds={})
            cn = gui.cursor.Name
            self.cursor_move_w_e = mkcursor(cn.MOVE_WEST_OR_EAST)
            self.cursor_move_n_s = mkcursor(cn.MOVE_NORTH_OR_SOUTH)
  File "/usr/share/mypaint/gui/framewindow.py", line 117, <lambda>(name='cursor_move_w_e')
                self.ACTION_NAME,
                name,
            )
  variables: {'name': ('local', 'cursor_move_w_e')}
  File "/usr/share/mypaint/gui/cursor.py", line 312, get_action_cursor(self=<gui.cursor.CustomCursorMaker object>, action_name='FrameEditMode', cursor_name='cursor_move_w_e')
                return Gdk.Cursor.new(Gdk.CursorType.ARROW)
            return self.get_icon_cursor(icon_name, cursor_name)
  variables: {'self.get_icon_cursor': ('local', <bound method CustomCursorMaker.get_icon_cursor of <gui.cursor.CustomCursorMaker object at 0x7f39212c73d0>>), 'icon_name': ('local', 'mypaint-frame-symbolic'), 'cursor_name': ('local', 'cursor_move_w_e')}
  File "/usr/share/mypaint/gui/cursor.py", line 335, get_icon_cursor(self=<gui.cursor.CustomCursorMaker object>, icon_name='mypaint-frame-symbolic', cursor_name='cursor_move_w_e')
                        fg=(1, 1, 1, 1),
                        outline=(0, 0, 0, 1),
                    )
  variables: {'outline': (None, [])}
  File "/usr/share/mypaint/gui/drawutils.py", line 302, load_symbolic_icon(icon_name='mypaint-frame-symbolic', size=16, fg=(1, 1, 1, 1), success=None, warning=None, error=None, outline=(0, 0, 0, 1))
            warning_color=rgba_or_none(warning),
            error_color=rgba_or_none(error),
        )
  variables: {'error': ('local', None), 'error_color': (None, []), 'rgba_or_none': ('local', <function <lambda> at 0x7f391d0bdbd0>)}
Error: rsvg-error-quark: XML parse error: error code=201 (3) in (null):26:121: Namespace prefix xlink for href on use is not defined
 (0)
```
### Steps to reproduce the behavior
    install the mypaint package, launch it and try to use the edit frame tool

**Comment by teh-jazzman** [comment]
There is a wrong namespace declaration in some SVG icons that the XML parser complains about. This part is an easy fix, but I currently can't get the package to build properly. The SWIG-generated python code to load the low-level C library fails to actually load the library. It's also quite different from the code that's in the current package. If I use that code it works as expected. Not sure what I have to do to make SWIG generate the code as it is in the current package or why it isn't the same code in the first place.
