### ISSUE TITLE
riot-desktop doesn't work

### ISSUE THREAD

**Issue by dawidpotocki** [void-linux/void-packages#18266]
### System

* xuname:  
  `Void 5.3.18_1 x86_64 GenuineIntel uptodate rrrmFFFFF`
* package:  
  `riot-desktop-1.5.6_1` 

### Expected behavior

Riot werks

### Actual behavior

Riot doesn't show an application window (without launching twice). It started happening after 1.5.0
update (or something like that) and kept working on my machine with my logged
in account, but on new installs, it complained about not having set a default
server. Since 1.5.6, it won't even show this message, it will just show a white
empty window, that's it. I know it doesn't happen only on my machines, since I
first heard about this from other Riot user on Void.

### Steps to reproduce the behavior

Fresh install `riot-desktop` and launch `riot-desktop` in terminal.

<details>
<summary>
riot-desktop output
</summary>
<pre>
sh: 0: getcwd() failed: No such file or directory
node[17887]: pthread_create: Invalid argument
seshat unavailable Error: Cannot find module 'matrix-seshat'
Require stack:
- /usr/lib/riot-desktop/electron_app/src/electron-main.js
- /usr/lib/riot-desktop/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7615:16)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/usr/lib/riot-desktop/electron_app/src/electron-main.js:49:14)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/riot-desktop/electron_app/src/electron-main.js',
    '/usr/lib/riot-desktop/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
App threw an error during load
Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42:25)
    at process.cwd (/usr/lib/riot-desktop/electron_app/node_modules/graceful-fs/polyfills.js:10:19)
    at Function.module.exports.sync (/usr/lib/riot-desktop/electron_app/node_modules/locate-path/index.js:16:16)
    at Function.module.exports.sync (/usr/lib/riot-desktop/electron_app/node_modules/find-up/index.js:38:27)
    at Function.module.exports.sync (/usr/lib/riot-desktop/electron_app/node_modules/pkg-up/index.js:5:37)
    at new Conf (/usr/lib/riot-desktop/electron_app/node_modules/conf/index.js:22:25)
    at new ElectronStore (/usr/lib/riot-desktop/electron_app/node_modules/electron-store/index.js:20:3)
    at Object.<anonymous> (/usr/lib/riot-desktop/electron_app/src/electron-main.js:109:15)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42:25)
    at process.cwd (/usr/lib/riot-desktop/electron_app/node_modules/graceful-fs/polyfills.js:10:19)
    at Function.module.exports.sync (/usr/lib/riot-desktop/electron_app/node_modules/locate-path/index.js:16:16)
    at Function.module.exports.sync (/usr/lib/riot-desktop/electron_app/node_modules/find-up/index.js:38:27)
    at Function.module.exports.sync (/usr/lib/riot-desktop/electron_app/node_modules/pkg-up/index.js:5:37)
    at new Conf (/usr/lib/riot-desktop/electron_app/node_modules/conf/index.js:22:25)
    at new ElectronStore (/usr/lib/riot-desktop/electron_app/node_modules/electron-store/index.js:20:3)
    at Object.<anonymous> (/usr/lib/riot-desktop/electron_app/src/electron-main.js:109:15)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
</pre>
</details>

**Comment by vpzomtrrfrt** [comment]
After building riot-desktop 1.5.7 from #18334, the white screen seems to be resolved, but the "Riot is misconfigured" screen is still present

**Comment by vpzomtrrfrt** [comment]
It appears that it's searching for the config file in `/usr/lib/riot-desktop/resources/webapp/`, while the package is placing it in `/usr/lib/riot-desktop/`.

**Comment by Pestdoktor** [comment]
Yea, I didn't notice because I already had a user config set up.

Updated my branch to fix.

**Comment by Piraty** [comment]
Fixed with #18334
