### ISSUE TITLE
pmbootstrap fails to install

### ISSUE THREAD

**Issue by xrdn** [void-linux/void-packages#18375]
### System

* xuname:  
  *Void 5.4.13_1 x86_64 GenuineIntel uptodate rrrmFFFF*
* package:  
  *pmbootstrap-1.13.0_1*

### Expected behavior
Running `pmbootstrap init` should result in a postmarketOS development environment.
### Actual behavior
Running `pmbootstrap init` results in the following log (taken from `pmbootstrap log`).
```
(018496) [20:09:34] *** (1/5) PREPARE NATIVE CHROOT ***
(018496) [20:09:34] NOTE: Skipped apk version check for chroot 'native', because it is not installed yet!
(018496) [20:09:34] % sudo mkdir -p /home/user/.local/var/pmbootstrap/chroot_native/dev
(018496) [20:09:34] % sudo mount -t tmpfs -o size=1M,noexec,dev tmpfs /home/user/.local/var/pmbootstrap/chroot_native/dev
(018496) [20:09:34] % sudo mkdir -p /home/user/.local/var/pmbootstrap/chroot_native/dev/pts /home/user/.local/var/pmbootstrap/chroot_native/dev/shm
(018496) [20:09:34] % sudo mount -t tmpfs -o nodev,nosuid,noexec tmpfs /home/user/.local/var/pmbootstrap/chroot_native/dev/shm
(018496) [20:09:34] % sudo mknod -m 666 /home/user/.local/var/pmbootstrap/chroot_native/dev/null c 1 3
(018496) [20:09:34] % sudo mknod -m 666 /home/user/.local/var/pmbootstrap/chroot_native/dev/zero c 1 5
(018496) [20:09:34] % sudo mknod -m 666 /home/user/.local/var/pmbootstrap/chroot_native/dev/full c 1 7
(018496) [20:09:34] % sudo mknod -m 644 /home/user/.local/var/pmbootstrap/chroot_native/dev/random c 1 8
(018496) [20:09:34] % sudo mknod -m 644 /home/user/.local/var/pmbootstrap/chroot_native/dev/urandom c 1 9
(018496) [20:09:34] [Errno 13] Permission denied: '/home/user/.local/var/pmbootstrap/chroot_native/dev/null'!
(018496) [20:09:34] ERROR: Failed to create device nodes in the 'native' chroot.
(018496) [20:09:34] See also: <https://postmarketos.org/troubleshooting>
(018496) [20:09:34] Traceback (most recent call last):
  File "/home/user/dev/pmbootstrap/pmb/chroot/mount.py", line 49, in create_device_nodes
    stat_result = os.stat(path)
PermissionError: [Errno 13] Permission denied: '/home/user/.local/var/pmbootstrap/chroot_native/dev/null'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/dev/pmbootstrap/pmb/__init__.py", line 63, in main
    getattr(frontend, args.action)(args)
  File "/home/user/dev/pmbootstrap/pmb/helpers/frontend.py", line 195, in install
    pmb.install.install(args)
  File "/home/user/dev/pmbootstrap/pmb/install/_install.py", line 481, in install
    pmb.chroot.apk.install(args, pmb.config.install_native_packages,
  File "/home/user/dev/pmbootstrap/pmb/chroot/apk.py", line 198, in install
    pmb.chroot.init(args, suffix)
  File "/home/user/dev/pmbootstrap/pmb/chroot/init.py", line 54, in init
    pmb.chroot.mount(args, suffix)
  File "/home/user/dev/pmbootstrap/pmb/chroot/mount.py", line 94, in mount
    mount_dev_tmpfs(args, suffix)
  File "/home/user/dev/pmbootstrap/pmb/chroot/mount.py", line 89, in mount_dev_tmpfs
    create_device_nodes(args, suffix)
  File "/home/user/dev/pmbootstrap/pmb/chroot/mount.py", line 63, in create_device_nodes
    raise RuntimeError("Failed to create device nodes in the '" +
RuntimeError: Failed to create device nodes in the 'native' chroot.

(027480) [20:12:00] % tail -f /home/user/.local/var/pmbootstrap/log.txt -n 60
(027480) [20:12:00] *** output passed to pmbootstrap stdout, not to this log ***
(029434) [20:12:32] % tail -f /home/user/.local/var/pmbootstrap/log.txt -n 60
(029434) [20:12:32] *** output passed to pmbootstrap stdout, not to this log ***

```

### Steps to reproduce the behavior
Run `pmbootstrap init`

**Comment by bra1nwave** [comment]
You need to edit the `/etc/sudoers` with the `visudo` command and add this line:
> Defaults umask = 022




See [here](https://old.reddit.com/r/voidlinux/comments/dsdn5a/did_sudo_behaviour_change_recently/)

**Comment by xrdn** [comment]
Solved
