### ISSUE TITLE
gnome-passwordsafe 3.32 and pykeepass 3.1+ are incompatible

### ISSUE THREAD

**Issue by paxet** [void-linux/void-packages#20687]
### System

* xuname:  
  Void 5.6.2_1 x86_64 GenuineIntel notuptodate rrFF
* package:  
  gnome-passwordsafe 3.32.0_3
  python3-pykeepass-3.2.0_1

### Expected behavior
Open a keepass database without error

### Actual behavior
Throws an error when loading database.
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/passwordsafe/unlock_database.py", line 277, in password_unlock_success
    self.open_database_page()
  File "/usr/lib/python3.8/site-packages/passwordsafe/unlock_database.py", line 603, in open_database_page
    UnlockedDatabase(self.window, self.parent_widget, self.database_manager, self)
  File "/usr/lib/python3.8/site-packages/passwordsafe/unlocked_database.py", line 86, in __init__
    self.assemble_listbox()
  File "/usr/lib/python3.8/site-packages/passwordsafe/unlocked_database.py", line 132, in assemble_listbox
    self.show_page_of_new_directory(False, False)
  File "/usr/lib/python3.8/site-packages/passwordsafe/unlocked_database.py", line 242, in show_page_of_new_directory
    elif self.stack.get_child_by_name(self.database_manager.get_group_uuid_from_group_object(self.current_group)) is None and self.stack.get_child_by_name(self.database_manager.get_entry_uuid_from_entry_object(self.current_group)) is None and edit_group is False:
TypeError: Must be string, not UUID
```
Link to Password Safe issue: https://gitlab.gnome.org/World/PasswordSafe/-/issues/128

### Steps to reproduce the behavior
Launch gnome-passowordsafe and open a KeePass v.4 database

**Comment by paxet** [comment]
Thank you, solved.
