### ISSUE TITLE
hplip: crashes

### ISSUE THREAD

**Issue by bobertlo** [void-linux/void-packages#20689]
```
Found device: hp:/net/ENVY_5660_series?ip=10.1.20.100
Traceback (most recent call last):
  File "/usr/share/hplip/ui5/setupdialog.py", line 1305, in NextButton_clicked
    self.showAddPrinterPage()
  File "/usr/share/hplip/ui5/setupdialog.py", line 711, in showAddPrinterPage
    self.findPrinterPPD()
  File "/usr/share/hplip/ui5/setupdialog.py", line 789, in findPrinterPPD
    self.ppds = cups.getSystemPPDs()
  File "/usr/share/hplip/prnt/cups.py", line 329, in getSystemPPDs
    path = os.path.join(cups_ppd_path, ppd)
  File "/usr/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Aborted
```

Seems to be a regression of https://github.com/void-linux/void-packages/commit/687e3c21c6cacf52b18782a30f43b9883b098b21

That directory did not exist, and creating it solved the issue. I don't know why this is happening.

**Comment by bobertlo** [comment]
I'm just confused because it looks like it should be created by the package? I don't know why this is an issue. I ended up setting up the printer through the CUPS web interface before tracking this down.
