### ISSUE TITLE
vapoursynth missing the subtitle rendering plugin (Subtext)

### ISSUE THREAD

**Issue by DirectorX** [void-linux/void-packages#2275]
### System

* xuname:  
```
Void 4.17.18_1 x86_64 GenuineIntel uptodate hold rrmFFFF
```
* package:  
  - vapoursynth-R44_3

### Expected behavior
```python
import vapoursynth as vs
core = vs.get_core()
video = core.ffms2.Source('source.mkv')
video = core.sub.Subtitle(video, 'THIS TEXT IS SUBTITLE')
video.set_output()
```

The script above should finish successfully.

### Actual behavior

```
Traceback (most recent call last):
File "src/cython/vapoursynth.pyx", line 1937, in vapoursynth.vpy_evaluateScript
File "src/cython/vapoursynth.pyx", line 1938, in vapoursynth.vpy_evaluateScript
File "script.vpy", line 6, in 
video = core.sub.Subtitle(video, 'THIS TEXT IS SUBTITLE')
File "src/cython/vapoursynth.pyx", line 1523, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name sub exists. Did you mistype a plugin namespace?
```

### Steps to reproduce the behavior

- Execute the script

**Comment by DirectorX** [comment]
The fix is trivial

```diff
diff --git a/srcpkgs/vapoursynth/template b/srcpkgs/vapoursynth/template
index e585abd99c..dc22c3ef55 100644
--- a/srcpkgs/vapoursynth/template
+++ b/srcpkgs/vapoursynth/template
@@ -4,7 +4,7 @@ version=R44
 revision=3
 build_style=gnu-configure
 hostmakedepends="automake pkg-config libtool nasm python3-Cython"
-makedepends="python3-devel zimg-devel libmagick-devel libass-devel"
+makedepends="python3-devel zimg-devel libmagick-devel libass-devel ffmpeg-devel"
 short_desc="Application for video manipulation"
 maintainer="lemmi <lemmi@nerd2nerd.org>"
 license="LGPL-2"
```

@lemmi
