### ISSUE TITLE
python3-jupyter_console: Missing /bin/jupyter-console

### ISSUE THREAD

**Issue by mamins1376** [void-linux/void-packages#23500]
### System

* xuname:  Void 5.4.50_1 x86_64 AuthenticAMD notuptodate rrrmFFFFFFFF
* package:  `python3-jupyter_console-6.1.0_1`

### Expected behavior
Jupyter's different modules have their own binaries which are used to execute them.

python2 version already has the file (`/bin/jupyter-console2`) present.

### Actual behavior
`/usr/bin/jupyter-console` is not shipped in the package; thus leading to this error, even if `python3-jupyter_console` is installed:
```
Traceback (most recent call last):
  File "/sbin/jupyter", line 11, in <module>
    load_entry_point('jupyter-core==4.6.3', 'console_scripts', 'jupyter')()
  File "/usr/lib/python3.8/site-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/usr/lib/python3.8/site-packages/jupyter_core/command.py", line 133, in _jupyter_abspath
    raise Exception(
Exception: Jupyter command `jupyter-console` not found.
```

### Steps to reproduce the behavior
Just install `python3-jupyter` (has the mentioned package as it's direct dependency) and hit `jupyter console`.

**Comment by ericonr** [comment]
```
$ xbps-query -Rf python3-jupyter_console
/usr/bin/jupyter-console
/usr/lib/python3.8/site-packages/jupyter_console/__init__.py
/usr/lib/python3.8/site-packages/jupyter_console/__main__.py
/usr/lib/python3.8/site-packages/jupyter_console/_version.py
/usr/lib/python3.8/site-packages/jupyter_console/app.py
/usr/lib/python3.8/site-packages/jupyter_console/completer.py
/usr/lib/python3.8/site-packages/jupyter_console/ptshell.py
/usr/lib/python3.8/site-packages/jupyter_console/tests/__init__.py
/usr/lib/python3.8/site-packages/jupyter_console/tests/test_console.py
/usr/lib/python3.8/site-packages/jupyter_console/tests/test_image_handler.py
/usr/lib/python3.8/site-packages/jupyter_console/tests/writetofile.py
/usr/lib/python3.8/site-packages/jupyter_console/zmqhistory.py
/usr/lib/python3.8/site-packages/jupyter_console-6.1.0-py3.8.egg-info
/usr/share/licenses/python3-jupyter_console/LICENSE
```

Have you updated the package? This issue was solved a few days ago.

**Comment by ericonr** [comment]
Yes, you're out of date. The latest version is `6.1.0_2`.

**Comment by mamins1376** [comment]
Oh! sorry
