### ISSUE TITLE
python-virtualenv is not working (missing dependencies)

### ISSUE THREAD

**Issue by subosito** [void-linux/void-packages#24253]
### System

* xuname:  
  
```
Void 5.7.14_1 x86_64 GenuineIntel uptodate rFFFF 
```
* package:  

```
python-virtualenv-20.0.20_1
```

### Expected behavior

It should create virtual environment using python2.

### Actual behavior

It breaks with error message: missing dependencies.

### Steps to reproduce the behavior

```
$ sudo xbps-install python-virtualenv
$ virtualenv2 py2-env
Traceback (most recent call last):
  File "/usr/bin/virtualenv2", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'importlib-metadata<2,>=0.12' distribution was not found and is required by virtualenv
```

Everything is working fine using `python3-virtualenv`:

```
$ sudo xbps-install python3-virtualenv
$ virtualenv3 py3-env
created virtual environment CPython3.8.5.final.0-64 in 116ms
  creator CPython3Posix(dest=/home/subosito/example/py3-env, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/subosito/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
```

**Comment by sgn** [comment]
`python-virtualenv` requires `distlib` and `importlib-resources` which is not shipped anymore.
Please use `python3-` instead. I'll remove it.

**Comment by subosito** [comment]
@sgn I see, thanks.
