### ISSUE TITLE
gnome-authenticator depends on libhandy, pyfavicon... and then doesn't work

### ISSUE THREAD

**Issue by harrisonthorne** [void-linux/void-packages#24457]
### System

* xuname:  

Void 5.7.15_1 x86_64 AuthenticAMD notuptodate rrrmFFFFFFFFFFF

* package:  

gnome-authenticator-3.32.2_1

### Expected behavior

The app should start.

### Actual behavior

It doesn't.

### Steps to reproduce the behavior

After installing `gnome-authenticator`, running it from the command-line (`authenticator`) yields

```
Traceback (most recent call last):
  File "/usr/bin/authenticator", line 31, in <module>
    require_version("Handy", "0.0")
  File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Handy not available
```

So I installed `libhandy` (0.0.13_1). Then I get this from authenticator:

```
Traceback (most recent call last):
  File "/usr/bin/authenticator", line 55, in <module>
    from Authenticator.models import Logger
  File "/usr/lib/python3.8/site-packages/Authenticator/models/__init__.py", line 31, in <module>
    from .backup import BackupJSON
  File "/usr/lib/python3.8/site-packages/Authenticator/models/backup.py", line 23, in <module>
    from Authenticator.widgets import AccountsWidget
  File "/usr/lib/python3.8/site-packages/Authenticator/widgets/__init__.py", line 21, in <module>
    from .provider_image import ProviderImage
  File "/usr/lib/python3.8/site-packages/Authenticator/widgets/provider_image.py", line 26, in <module>
    from pyfavicon import Favicon
ModuleNotFoundError: No module named 'pyfavicon'
```

I installed `python3-pip` and did `pip3 install --user pyfavicon`. And now authenticator gives me this:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/Authenticator/application.py", line 59, in do_startup
    self._setup_actions()
  File "/usr/lib/python3.8/site-packages/Authenticator/application.py", line 142, in _setup_actions
    Keyring.get_default().connect("notify::can-be-locked",
  File "/usr/lib/python3.8/site-packages/Authenticator/models/keyring.py", line 49, in get_default
    Keyring.instance = Keyring()
  File "/usr/lib/python3.8/site-packages/Authenticator/models/keyring.py", line 44, in __init__
    self.props.can_be_locked = self.is_password_enabled() and self.has_password()
  File "/usr/lib/python3.8/site-packages/Authenticator/models/keyring.py", line 136, in is_password_enabled
    state = Secret.password_lookup_sync(schema, {}, None)
gi.repository.GLib.Error: g-dbus-error-quark: The name org.freedesktop.secrets was not provided by any .service files (2)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/Authenticator/application.py", line 77, in do_activate
    window = Window.get_default()
  File "/usr/lib/python3.8/site-packages/Authenticator/widgets/window.py", line 70, in get_default
    Window.instance = Window()
  File "/usr/lib/python3.8/site-packages/Authenticator/widgets/window.py", line 55, in __init__
    self.init_template('Window')
TypeError: <lambda>() takes 0 positional arguments but 1 was given
```

**Comment by harrisonthorne** [comment]
> notuptodate

`xi -u` didn't change the problem. New `xuname`:

Void 5.7.15_1 x86_64 AuthenticAMD uptodate rrrmFFFFFFFFFFF

**Comment by ericonr** [comment]
Did you try 'libhandy1' instead?

**Comment by harrisonthorne** [comment]
Just did, here's the output (I don't think it's different lol):

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/Authenticator/application.py", line 59, in do_startup
    self._setup_actions()
  File "/usr/lib/python3.8/site-packages/Authenticator/application.py", line 142, in _setup_actions
    Keyring.get_default().connect("notify::can-be-locked",
  File "/usr/lib/python3.8/site-packages/Authenticator/models/keyring.py", line 49, in get_default
    Keyring.instance = Keyring()
  File "/usr/lib/python3.8/site-packages/Authenticator/models/keyring.py", line 44, in __init__
    self.props.can_be_locked = self.is_password_enabled() and self.has_password()
  File "/usr/lib/python3.8/site-packages/Authenticator/models/keyring.py", line 136, in is_password_enabled
    state = Secret.password_lookup_sync(schema, {}, None)
gi.repository.GLib.Error: g-dbus-error-quark: The name org.freedesktop.secrets was not provided by any .service files (2)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/Authenticator/application.py", line 77, in do_activate
    window = Window.get_default()
  File "/usr/lib/python3.8/site-packages/Authenticator/widgets/window.py", line 70, in get_default
    Window.instance = Window()
  File "/usr/lib/python3.8/site-packages/Authenticator/widgets/window.py", line 55, in __init__
    self.init_template('Window')
TypeError: <lambda>() takes 0 positional arguments but 1 was given
```

**Comment by harrisonthorne** [comment]
Is it working for you (or anyone else)? I think our concern might have to do with this?

```
The name org.freedesktop.secrets was not provided by any .service files (2)
```

I'm using `runit`

**Comment by ericonr** [comment]
Do you have `gnome-keyring` installed? Might need to add it as dependency... And it definitely shouldn't require a package from pip.

**Comment by ericonr** [comment]
We're definitely missing a lot of deps: https://gitlab.gnome.org/World/Authenticator/-/blob/master/requirements.txt

**Comment by sgn** [comment]
Working on it.

**Comment by sgn** [comment]
Please test #24470
