### ISSUE TITLE
python3-pylint throws a traceback at startup

### ISSUE THREAD

**Issue by CMB** [void-linux/void-packages#25718]
When running, for instance, `pylint foo.py`, I get this:

    Traceback (most recent call last):
      File "/usr/bin/pylint", line 33, in <module>
        sys.exit(load_entry_point('pylint==2.6.0', 'console_scripts', 'pylint')())
      File "/usr/lib/python3.9/site-packages/pylint/__init__.py", line 19, in run_pylint
        from pylint.lint import Run as PylintRun
      File "/usr/lib/python3.9/site-packages/pylint/lint/__init__.py", line 75, in <module>
        from pylint.lint.check_parallel import check_parallel
      File "/usr/lib/python3.9/site-packages/pylint/lint/check_parallel.py", line 7, in <module>
        from pylint import reporters
      File "/usr/lib/python3.9/site-packages/pylint/reporters/__init__.py", line 24, in <module>
        from pylint import utils
      File "/usr/lib/python3.9/site-packages/pylint/utils/__init__.py", line 47, in <module>
        from pylint.utils.ast_walker import ASTWalker
      File "/usr/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 6, in <module>
        from astroid import nodes
      File "/usr/lib/python3.9/site-packages/astroid/__init__.py", line 65, in <module>
        from astroid.nodes import *
      File "/usr/lib/python3.9/site-packages/astroid/nodes.py", line 23, in <module>
        from astroid.node_classes import (
      File "/usr/lib/python3.9/site-packages/astroid/node_classes.py", line 42, in <module>
        from astroid import bases
      File "/usr/lib/python3.9/site-packages/astroid/bases.py", line 36, in <module>
        MANAGER = manager.AstroidManager()
      File "/usr/lib/python3.9/site-packages/astroid/util.py", line 26, in <lambda>
        lambda: importlib.import_module("." + module_name, "astroid")
      File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "/usr/lib/python3.9/site-packages/astroid/manager.py", line 27, in <module>
        from astroid.interpreter._import import spec
      File "/usr/lib/python3.9/site-packages/astroid/interpreter/_import/spec.py", line 32, in <module>
        from . import util
      File "/usr/lib/python3.9/site-packages/astroid/interpreter/_import/util.py", line 4, in <module>
        import pkg_resources
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3239, in <module>
        def _initialize_master_working_set():
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
        f(*args, **kwargs)
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 569, in _build_master
        return cls._build_from_requirements(__requires__)
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
        dists = ws.resolve(reqs, Environment())
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 770, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'lazy_object_proxy==1.4.*' distribution was not found and is required by astroid

I've seen this on two machines.

**Comment by sgn** [comment]
https://github.com/PyCQA/astroid/commit/e1b4e11e383bf281544f1300e41eea2ac6ab251c

Let's patch it out.
