### ISSUE TITLE
[Update Request: Broken Package] Catfish

### ISSUE THREAD

**Issue by eth0OS** [void-linux/void-packages#26379]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
* package:  
  *affected package(s) including the version*: catfish-1.4.13_3

### Expected behavior

Running the command "catfish" in a terminal should open the main window of the application.

### Actual behavior

It outputs an error about python:

```
Traceback (most recent call last):
  File "/bin/catfish", line 44, in <module>
    catfish.main()
  File "/usr/lib/python3.9/site-packages/catfish/__init__.py", line 78, in main
    window = CatfishWindow.CatfishWindow()
  File "/usr/lib/python3.9/site-packages/catfish_lib/Window.py", line 171, in __new__
    builder = get_builder(__builder__['ui_file'])
  File "/usr/lib/python3.9/site-packages/catfish_lib/helpers.py", line 109, in get_builder
    builder.add_from_file(ui_filename)
  File "/usr/lib/python3.9/site-packages/catfish_lib/Builder.py", line 87, in add_from_file
    ele_widgets = tree.getiterator("object")
AttributeError: 'ElementTree' object has no attribute 'getiterator'
```

### Steps to reproduce the behavior

Run the command 'catfish' in a terminal. 

---

Additional notes:
I am aware that update request are not encouraged but I've shared this problem with the folks over the Telegram group and some of them are experiencing the same problem. I was told that the problem is already fixed upstream but the devs haven't tagged a release yet. Since the package is completely unusable and it's orphaned, and also it is a considerable useful package for XFCE users, I kindly ask for consider a middle release compilation and the pushing to void's repo. Thank you.

**Comment by ericonr** [comment]
If you know how to test PRs, I'd appreciate testing in https://github.com/void-linux/void-packages/pull/26382

I couldn't launch it because it complained about Xfconf something.

**Comment by eth0OS** [comment]
I have no single clue how to test PRs but I appreciate your effort, I'll ask on the Telegram group if somebody is up to test it.

**Comment by ericonr** [comment]
Follow steps here https://github.com/void-linux/void-packages#quick-start , if you want to learn it. Pretty simple.

**Comment by eth0OS** [comment]
Got it! But I run into this error:

```
Traceback (most recent call last):
  File "/bin/catfish", line 43, in <module>
    import catfish
  File "/usr/lib/python3.9/site-packages/catfish/__init__.py", line 32, in <module>
    from catfish import CatfishWindow
  File "/usr/lib/python3.9/site-packages/catfish/CatfishWindow.py", line 50, in <module>
    from catfish.CatfishPrefsDialog import CatfishPrefsDialog
  File "/usr/lib/python3.9/site-packages/catfish/CatfishPrefsDialog.py", line 29, in <module>
    from catfish_lib.PrefsDialog import PrefsDialog
  File "/usr/lib/python3.9/site-packages/catfish_lib/__init__.py", line 23, in <module>
    from . Window import Window  # noqa
  File "/usr/lib/python3.9/site-packages/catfish_lib/Window.py", line 27, in <module>
    from catfish_lib import CatfishSettings
  File "/usr/lib/python3.9/site-packages/catfish_lib/CatfishSettings.py", line 23, in <module>
    gi.require_version('Xfconf', '0')
  File "/usr/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Xfconf not available
```

**Comment by ericonr** [comment]
Ok, that's what I had, but I thought it would be because I'm not running XFCE. You do have `xfconf` installed?

**Comment by eth0OS** [comment]
Yes, I do. xfconf-4.14.3_1.

**Comment by q66** [comment]
likely xfconf must be built with introspection support

**Comment by ericonr** [comment]
Yup, that's what's missing. I'm trying to build 4.15.1 with introspection.

**Comment by ericonr** [comment]
@eth0OS I just pushed a new version, it seems to be working now! You have to build the package with `./xbps-src pkg -f catfish` this time, otherwise it won't replace the version you just built.

**Comment by eth0OS** [comment]
Thank you once again. Should I build the new xfconf template and install it before building the new catfish?

**Comment by ericonr** [comment]
It will build xfconf automatically, just remember to install it :)
