### ISSUE TITLE
terminator-1.91_1  option parse error

### ISSUE THREAD

**Issue by paoloschi** [void-linux/void-packages#2671]
### System

* xuname:  
 Void 4.18.7_2 x86_64 GenuineIntel uptodate rFF
* package:  
  pkgver: terminator-1.91_1

### Expected behavior
executing `terminator -h` the list of available program options is printed into the terminal 

### Actual behavior
```
$ terminator -h
Traceback (most recent call last):
  File "/usr/bin/terminator", line 68, in <module>
    OPTIONS = terminatorlib.optionparse.parse_options()
  File "/usr/lib/python2.7/site-packages/terminatorlib/optionparse.py", line 110, in parse_options
    (options, args) = parser.parse_args()
  File "/usr/lib/python2.7/optparse.py", line 1400, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/lib/python2.7/optparse.py", line 1444, in _process_args
    self._process_short_opts(rargs, values)
  File "/usr/lib/python2.7/optparse.py", line 1551, in _process_short_opts
    option.process(opt, value, values, self)
  File "/usr/lib/python2.7/optparse.py", line 789, in process
    self.action, self.dest, opt, value, values, parser)
  File "/usr/lib/python2.7/optparse.py", line 811, in take_action
    parser.print_help()
  File "/usr/lib/python2.7/optparse.py", line 1670, in print_help
    file.write(self.format_help().encode(encoding, "replace"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1115: ordinal not in range(128)
```
I tried running in terminator itself and also from xterm

with the void terminator-1.91_1 package NOT INSTALLED, extracting [terminator-1.91.tar.gz](https://launchpad.net/terminator/gtk3/1.91/+download/terminator-1.91.tar.gz) and executing `./terminator -h `  from the extraction directory,  I get: 
```
$ ./terminator -h
Usage: terminator [options]

Options:
  -h, --help            show this help message and exit
  -v, --version         Display program version
  -m, --maximise        Maximize the window
  -f, --fullscreen      Make the window fill the screen
  -b, --borderless      Disable window borders
  -H, --hidden          Hide the window at startup
  -T FORCEDTITLE, --title=FORCEDTITLE
                        Specify a title for the window
  --geometry=GEOMETRY   Set the preferred size and position of the window(see
                        X man page)
  -e COMMAND, --command=COMMAND
                        Specify a command to execute inside the terminal
  -g CONFIG, --config=CONFIG
                        Specify a config file
  -x, --execute         Use the rest of the command line as a command to
                        execute inside the terminal, and its arguments
  --working-directory=DIR
                        Set the working directory
  -c CLASSNAME, --classname=CLASSNAME
                        Set a custom name (WM_CLASS) property on the window
  -i FORCEDICON, --icon=FORCEDICON
                        Set a custom icon for the window (by file or name)
  -r ROLE, --role=ROLE  Set a custom WM_WINDOW_ROLE property on the window
  -l LAYOUT, --layout=LAYOUT
                        Launch with the given layout
  -s, --select-layout   Select a layout from a list
  -p PROFILE, --profile=PROFILE
                        Use a different profile as the default
  -u, --no-dbus         Disable DBus
  -d, --debug           Enable debugging information (twice for debug server)
  --debug-classes=DEBUG_CLASSES
                        Comma separated list of classes to limit debugging to
  --debug-methods=DEBUG_METHODS
                        Comma separated list of methods to limit debugging to
  --new-tab             If Terminator is already running, just open a new tab
```

**Comment by maxice8** [comment]
Worked fine here

```
$ terminator -h
Usage: terminator [options]

Options:
  -h, --help            show this help message and exit
  -v, --version         Display program version
  -m, --maximise        Maximize the window
  -f, --fullscreen      Make the window fill the screen
  -b, --borderless      Disable window borders
  -H, --hidden          Hide the window at startup
  -T FORCEDTITLE, --title=FORCEDTITLE
                        Specify a title for the window
  --geometry=GEOMETRY   Set the preferred size and position of the window(see
                        X man page)
  -e COMMAND, --command=COMMAND
                        Specify a command to execute inside the terminal
  -g CONFIG, --config=CONFIG
                        Specify a config file
  -x, --execute         Use the rest of the command line as a command to
                        execute inside the terminal, and its arguments
  --working-directory=DIR
                        Set the working directory
  -c CLASSNAME, --classname=CLASSNAME
                        Set a custom name (WM_CLASS) property on the window
  -i FORCEDICON, --icon=FORCEDICON
                        Set a custom icon for the window (by file or name)
  -r ROLE, --role=ROLE  Set a custom WM_WINDOW_ROLE property on the window
  -l LAYOUT, --layout=LAYOUT
                        Launch with the given layout
  -s, --select-layout   Select a layout from a list
  -p PROFILE, --profile=PROFILE
                        Use a different profile as the default
  -u, --no-dbus         Disable DBus
  -d, --debug           Enable debugging information (twice for debug server)
  --debug-classes=DEBUG_CLASSES
                        Comma separated list of classes to limit debugging to
  --debug-methods=DEBUG_METHODS
                        Comma separated list of methods to limit debugging to
  --new-tab             If Terminator is already running, just open a new tab
```

**Comment by paoloschi** [comment]
based on the traceback that I still have, can you help me how to figure the cause?
initially I had thought of a missing runtime dependence but since directly from the source here also works.....

**Comment by Johnnynator** [comment]
Looks to me like smth smth encoding issue. Can you open a python shell and run 
```
import sys
getattr(sys.stdout, "encoding", None)
```
But this wouldn't explain why it works from source

**Comment by paoloschi** [comment]
```
$ python
Python 2.7.15 (default, Jul 16 2018, 08:54:52) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> getattr(sys.stdout, "encoding", None)
'UTF-8'
>>> 
```
maybe significant that here it works from the source only if the Void package is NOT installed?
I guess that a main script in sources, finding the modules installed in the system calls those with priority over the source files but since the installed files are the same what can change?.......
I would like to add that, apart from this oddity, the program seems to be running regularly.

**Comment by Johnnynator** [comment]
Mhh... I don't have any clue as of now what this bug is or what triggers it.

**Comment by paoloschi** [comment]
I think I've got it! by reading the INSTALL file from source:
```
[..]
If you don't care about native language support or icons, Terminator
should run just fine directly from this directory, just:

    ./terminator --help
[..]
```
here's what happens: when I run 'terminator -h' from source, this is printed to me in English whereas
when I do it from the installed program, it is translated into my native language, LANG=en_IT.UTF8.
..and since my language is damn well taped with 'extended' characters (accented vowels), the printed text is different from yours and causes me the encoding error!!!

a python 'locale' bug?
this however is the first time in general that I have encountered a localization problem (numbers 'grouping' apart..)

**Comment by maxice8** [comment]
Ping, issue still present ?

**Comment by paoloschi** [comment]
Yes, still present, same `can't decode byte 0xc3 in position 1115: ordinal not in range(128)`

```
Void 4.20.5_1 x86_64 GenuineIntel uptodate rFFF
pkgver: terminator-1.91_1

$ terminator -h
Traceback (most recent call last):
  File "/usr/bin/terminator", line 68, in <module>
    OPTIONS = terminatorlib.optionparse.parse_options()
  File "/usr/lib/python2.7/site-packages/terminatorlib/optionparse.py", line 110, in parse_options
    (options, args) = parser.parse_args()
  File "/usr/lib/python2.7/optparse.py", line 1400, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/lib/python2.7/optparse.py", line 1444, in _process_args
    self._process_short_opts(rargs, values)
  File "/usr/lib/python2.7/optparse.py", line 1551, in _process_short_opts
    option.process(opt, value, values, self)
  File "/usr/lib/python2.7/optparse.py", line 789, in process
    self.action, self.dest, opt, value, values, parser)
  File "/usr/lib/python2.7/optparse.py", line 811, in take_action
    parser.print_help()
  File "/usr/lib/python2.7/optparse.py", line 1670, in print_help
    file.write(self.format_help().encode(encoding, "replace"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1115: ordinal not in range(128)
```

**Comment by the-maldridge** [comment]
Terminator has been rebuilt since this issue was reported and the reported fault no longer occurs.
