### ISSUE TITLE
castero - package or dependency appears to be broken

### ISSUE THREAD

**Issue by runrin** [void-linux/void-packages#28105]
* xuname:  
Void 5.10.8_1 x86_64 AuthenticAMD notuptodate rFF
* package:  
castero-0.8.2_2

castero works fine when installed in a virtual env with pip, but when installed via xbps it will not start at all. here is its output:

```
Traceback (most recent call last):
  File "/bin/castero", line 33, in <module>
    sys.exit(load_entry_point('castero==0.8.2', 'console_scripts', 'castero')())
  File "/bin/castero", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/castero/__main__.py", line 12, in <module>
    monkey.patch_all(thread=False, select=False)
  File "/usr/lib/python3.9/site-packages/gevent/monkey.py", line 1210, in patch_all
    from gevent import events
  File "/usr/lib/python3.9/site-packages/gevent/events.py", line 67, in <module>
    from zope.interface import Interface
ModuleNotFoundError: No module named 'zope.interface'
```

to reproduce, simply install castero, and attempt to run it in a terminal emulator.

this issue occurred before 1535506 with version 0.8.2_1 as well.

**Comment by ericonr** [comment]
> Void 5.10.8_1 x86_64 AuthenticAMD notuptodate rFF

Have you tried updating the system as a whole?

**Comment by runrin** [comment]
yes, i update frequently, and just did to `Void 5.10.8_1 x86_64 AuthenticAMD uptodate rFF` and get the same error.

i have periodically installed this package the last few months, and it has always given the same error.

**Comment by ericonr** [comment]
@ndowens

**Comment by ericonr** [comment]
@runrin this will be fixed in a bit :)

**Comment by runrin** [comment]
thanks :D
