### ISSUE TITLE
pscircle: SIGILL (illegal instruction error)

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/void-packages#2858]
### System

* xuname:  
Void 4.18.7_2 x86_64 GenuineIntel notuptodate rFFFFFFFFFFFFF
* package:  
pscircle

### Expected behavior

Running `pscircle` produces a process visualization.

### Actual behavior

```
(gdb) run
Starting program: /usr/bin/pscircle 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x0000555555558dac in proc_to_pnode (ctx=ctx@entry=0x7fffffffe150, pnode=pnode@entry=0x5555557683c0, proc=proc@entry=0x7fffffffe0e0) at ../src/proc_linux.c:119
119	../src/proc_linux.c: No such file or directory.
(gdb) bt
#0  0x0000555555558dac in proc_to_pnode (ctx=ctx@entry=0x7fffffffe150, pnode=pnode@entry=0x5555557683c0, proc=proc@entry=0x7fffffffe0e0) at ../src/proc_linux.c:119
#1  0x00005555555599da in linux_get_next_proc (ctx=ctx@entry=0x7fffffffe150, pnode=0x5555557683c0) at ../src/proc_linux.c:94
#2  0x000055555555808b in read_procs_linux (procs=procs@entry=0x555555768320) at ../src/procs.c:153
#3  0x00005555555589d0 in procs_init (procs=0x555555768320, fp=0x0) at ../src/procs.c:74
#4  0x000055555555619c in main (argc=<optimized out>, argv=0x7fffffffe318) at ../src/pscircle.c:35
```

### Steps to reproduce the behavior

Run pscircle without arguments.

**Comment by maxice8** [comment]
Just tested, working fine here on x86_64

**Comment by abenson** [comment]
SIGILL for me as well. Here's an strace

[pscircle.txt](https://github.com/void-linux/void-packages/files/2390863/pscircle.txt)

**Comment by abenson** [comment]
Works after revbump for me as well

**Comment by maxice8** [comment]
Decided to revbump

**Comment by mustaqimM** [comment]
I'm still getting this error:
```fish
“pscircle” terminated by signal SIGILL (Illegal instruction)
```
