### ISSUE TITLE
zpaq segment faults

### ISSUE THREAD

**Issue by Mek101** [void-linux/void-packages#31080]
### System

* xuname:  
  Void 5.11.22_1 x86_64-musl AuthenticAMD uptodate rrnFFFFFF

* package:  
  `zpaq-7.15_2`

### Expected behavior
`zpaq` compresses the given folder

### Actual behavior
`zpaq` segment faults just after starting

### Steps to reproduce the behavior
Attempt to create a new archive with `zpaq add`

```
[mek101@home-server /storage/anime/No Game No Life]$ zpaq add 720p.paq 720p/\[Fate-Subs\]\ No\ Game\ No\ Life\ -\ 01\ \[720p\].mkv 
zpaq v7.15 journaling archiver, compiled Nov 27 2018
Creating 720p.paq at offset 0 + 0
Adding 559.388679 MB in 1 files -method 14 -threads 4 at 2021-05-23 19:39:45.
 3.06% 0:01:13 [1..244] 16714017 -method 14,52,0
Segmentation fault
```

**Comment by ericonr** [comment]
I wouldn't be surprised if this has existed since forever for the package on musl. Have you used it before?

**Comment by Mek101** [comment]
>Have you used it before?

No, I just installed it because I wanted to archive some old anime episodes I now have in higher res

**Comment by paper42** [comment]
I can reproduce this:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  memcpy () at src/string/x86_64/memcpy.s:18
18	src/string/x86_64/memcpy.s: No such file or directory.
[Current thread is 1 (LWP 8176)]
#0  memcpy () at src/string/x86_64/memcpy.s:18
#1  0x00005619b0412cd5 in libzpaq::StringBuffer::read (this=0x7fb3de968d30, buf=<optimized out>, n=16384) at libzpaq.h:1472
#2  0x00005619b04335a5 in libzpaq::Compressor::compress (this=this@entry=0x7fb3de5f5790, n=n@entry=-1) at libzpaq.cpp:2930
#3  0x00005619b043bfa6 in libzpaq::compressBlock (in=in@entry=0x7fb3de968d30, out=out@entry=0x7fb3de968d78, method_=<optimized out>, filename=0x7fb3de9686a0 "jDC20220521182512d0000000001", comment=0x7fb3de968de0 "jDC\001", dosha1=dosha1@entry=true) at libzpaq.cpp:7718
#4  0x00005619b0400c96 in compressThread (arg=0x7ffcb714f490) at /usr/include/c++/8.2/bits/basic_string.h:2281
#5  0x00007fb3de9208ce in start (p=0x7fb3de610ac0) at src/thread/pthread_create.c:195
#6  0x00007fb3de92d9fb in __clone () at src/thread/x86_64/clone.s:22
Backtrace stopped: frame did not save the PC
```
