### ISSUE TITLE
weather - package or dependency appears to be broken

### ISSUE THREAD

**Issue by runrin** [void-linux/void-packages#31157]
* xuname:  
Void 5.11.22_1 x86_64 AuthenticAMD uptodate rrFFF
* package:  
weather-2.4.1_2

this appears to have stopped working fairly recently.

commands with coordinates such as example command `weather 35.878573,-78.727813` produce the following result:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/weather.py", line 221, in get_uri
    data = urlopen(uri).read().decode("utf-8")
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/weather", line 70, in <module>
    partial = weather.get_metar(
  File "/usr/lib/python3.9/site-packages/weather.py", line 266, in get_metar
    metar = get_uri(
  File "/usr/lib/python3.9/site-packages/weather.py", line 230, in get_uri
    sys.exc_type,
AttributeError: module 'sys' has no attribute 'exc_type'
```

**Comment by Chocimier** [comment]
> urllib.error.HTTPError: HTTP Error 403: Forbidden

Try to find where from this program fetches data and what happened to service.

> 'sys' has no attribute 'exc_type'

Code targets both python 2 and 3, but sys.exc_type was removed in python 3. You may let know author, but this is on error handling path, so won't help much.

**Comment by runrin** [comment]
this is working again.
