### ISSUE TITLE
onionshare-gui fails to start

### ISSUE THREAD

**Issue by danil-braun** [void-linux/void-packages#31556]
### System

* xuname:  
  `Void 5.11.22_1 x86_64 GenuineIntel uptodate rrFF`
* package:  
  onionshare-2.2_5

fails to start:

```
$ onionshare-gui 
OnionShare 2.2 | https://onionshare.org/
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-d'
Traceback (most recent call last):
  File "/bin/onionshare-gui", line 22, in <module>
    onionshare_gui.main()
  File "/usr/lib/python3.9/site-packages/onionshare_gui/__init__.py", line 142, in main
    gui = OnionShareGui(common, onion, qtapp, app, filenames, config, local_only)
  File "/usr/lib/python3.9/site-packages/onionshare_gui/onionshare_gui.py", line 172, in __init__
    self.share_mode.init()
  File "/usr/lib/python3.9/site-packages/onionshare_gui/mode/share_mode/__init__.py", line 48, in init
    self.web = Web(self.common, True, "share")
  File "/usr/lib/python3.9/site-packages/onionshare/web/web.py", line 77, in __init__
    self.generate_static_url_path()
  File "/usr/lib/python3.9/site-packages/onionshare/web/web.py", line 166, in generate_static_url_path
    self.app.add_url_rule(
  File "/usr/lib/python3.9/site-packages/flask/scaffold.py", line 56, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1092, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: static
```

**Comment by lun-4** [comment]
That issue has already been upstreamed: https://github.com/micahflee/onionshare/issues/1365

**Comment by paper42** [comment]
I would vote for removing onionshare from packages, it is broken right now and updating it would require packaging a lot of new dependencies (I stopped at 8). OnionShare can still be installed with flatpak which upstream recommends. Maybe we could split CLI and still provide that.

**Comment by twann4** [comment]
I made a pull request, and now this issue is fixed. See https://github.com/onionshare/onionshare/pull/1392
