### ISSUE TITLE
`ibus-setup-hangul` requires librsvg

### ISSUE THREAD

**Issue by avoidr** [void-linux/void-packages#3157]
`ibus-setup-hangul` does not start unless `librsvg` is installed.
```
$ ibus-setup-hangul
Traceback (most recent call last):
  File "/usr/share/ibus-hangul/setup/main.py", line 304, in <module>
    Setup(bus).run()
  File "/usr/share/ibus-hangul/setup/main.py", line 153, in __init__
    self.__window.set_icon_from_file(icon_file)
gi.repository.GLib.Error: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/usr/share/ibus-hangul/icons/ibus-hangul.svg” (3)
```

package: `ibus-hangul-1.5.1_1`

**Comment by youngjinpark20** [comment]
https://github.com/void-linux/void-packages/pull/6728
