### ISSUE TITLE
'threadpoolctl' should be included in 'python3-scikit-learn' package

### ISSUE THREAD

**Issue by rivanfebrian123** [void-linux/void-packages#31976]
### System

* xuname:  `Void 5.12.14_1 x86_64-musl GenuineIntel notuptodate rrFFFF`
* package:  `python3-scikit-learn-0.23.2_1`

### Expected behavior
Include `threadpoolctl` by default

### Actual behavior
```
>>> from sklearn.cluster import KMeans
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/sklearn/cluster/__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "/usr/lib/python3.9/site-packages/sklearn/cluster/_spectral.py", line 18, in <module>
    from ._kmeans import k_means
  File "/usr/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py", line 18, in <module>
    from threadpoolctl import threadpool_limits
ModuleNotFoundError: No module named 'threadpoolctl'
```

### Steps to reproduce the behavior
- Install `python3-scikit-learn`
- Run `python3`
- Type `from sklearn.cluster import KMeans`

**Comment by ahesford** [comment]
Thanks for the report. The pending update should fix this issue.

**Comment by rivanfebrian123** [comment]
Your welcome :)

**Comment by apremgeorge** [comment]
I'm getting the same Error with python 3.9.5
scikit-learn Version: 0.24.2
threadpoolctl Version: 3.0.0
```
from sklearn.cluster import KMeans

ModuleNotFoundError                       Traceback (most recent call last)
c:\mb\MBA\MBA4.py in <cell line: 1>()
----> [66](file:///c%3A/mb/MBA/MBA4.py?line=65) from sklearn.cluster import KMeans

File c:\Users\mb\anaconda3\envs\AEKaggle\lib\site-packages\sklearn\cluster\__init__.py:6, in <module>
      [1](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/__init__.py?line=0) """
      [2](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/__init__.py?line=1) The :mod:`sklearn.cluster` module gathers popular unsupervised clustering
      [3](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/__init__.py?line=2) algorithms.
      [4](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/__init__.py?line=3) """
----> [6](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/__init__.py?line=5) from ._spectral import spectral_clustering, SpectralClustering
      [7](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/__init__.py?line=6) from ._mean_shift import (mean_shift, MeanShift,
      [8](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/__init__.py?line=7)                           estimate_bandwidth, get_bin_seeds)
      [9](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/__init__.py?line=8) from ._affinity_propagation import affinity_propagation, AffinityPropagation

File c:\Users\mb\anaconda3\envs\AEKaggle\lib\site-packages\sklearn\cluster\_spectral.py:19, in <module>
     [17](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/_spectral.py?line=16) from ..neighbors import kneighbors_graph, NearestNeighbors
     [18](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/_spectral.py?line=17) from ..manifold import spectral_embedding
---> [19](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/_spectral.py?line=18) from ._kmeans import k_means
     [22](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/_spectral.py?line=21) @_deprecate_positional_args
     [23](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/_spectral.py?line=22) def discretize(vectors, *, copy=True, max_svd_restarts=30, n_iter_max=20,
     [24](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/_spectral.py?line=23)                random_state=None):
     [25](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/_spectral.py?line=24)     """Search for a partition matrix (clustering) which is closest to the
     [26](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/_spectral.py?line=25)     eigenvector embedding.
     [27](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/_spectral.py?line=26) 
   (...)
     [73](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/_spectral.py?line=72) 
     [74](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/_spectral.py?line=73)     """

File c:\Users\mb\anaconda3\envs\AEKaggle\lib\site-packages\sklearn\cluster\_kmeans.py:18, in <module>
     [16](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/_kmeans.py?line=15) import numpy as np
     [17](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/_kmeans.py?line=16) import scipy.sparse as sp
---> [18](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/_kmeans.py?line=17) from threadpoolctl import threadpool_limits
     [19](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/_kmeans.py?line=18) from threadpoolctl import threadpool_info
     [21](file:///c%3A/Users/mb/anaconda3/envs/AEKaggle/lib/site-packages/sklearn/cluster/_kmeans.py?line=20) from ..base import BaseEstimator, ClusterMixin, TransformerMixin

ModuleNotFoundError: No module named 'threadpoolctl'
```
