### ISSUE TITLE
New failures to build

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#32749]
Found while testing things for doxygen update:

`kea` (there are a few updates out, we can try moving to a new version):

```
make[2]: Leaving directory '/builddir/kea-1.9.5/src'
Making all in doc
make[2]: Entering directory '/builddir/kea-1.9.5/doc'
Making all in sphinx
make[3]: Entering directory '/builddir/kea-1.9.5/doc/sphinx'
rm -f ./arm/platforms.rst
cp ./../../platforms.rst ./arm/platforms.rst
/usr/bin/sphinx-build -M html . ./_build -v -E -a -W -j 2 -c "/builddir/kea-1.9.5/doc/sphinx"
Running Sphinx v4.1.1
making output directory... done

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.9/site-packages/sphinx/application.py", line 251, in __init__
    self.config.setup(self)
  File "/builddir/kea-1.9.5/doc/sphinx/conf.py", line 231, in setup
    app.add_stylesheet('kea.css')
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'

Exception occurred:
  File "/builddir/kea-1.9.5/doc/sphinx/conf.py", line 231, in setup
    app.add_stylesheet('kea.css')
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
The full traceback has been saved in /tmp/sphinx-err-dxcqvg1x.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[3]: *** [Makefile:861: html] Error 2
```

and `kexi` (@Johnnynator):

```
-- Note: Graphical interface is not available so configuration and test apps that require Qt GUI won't be executed
CMake Error at cmake/modules/FindKexiMarble.cmake:78 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:202 (find_package)


CMake Error at cmake/modules/FindKexiMarble.cmake:81 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:202 (find_package)


CMake Error at cmake/modules/FindKexiMarble.cmake:84 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:202 (find_package)


-- Looking for uname
-- Looking for uname - found
```

**Comment by loreb** [comment]
The first one is easy, they renamed the method - https://github.com/sphinx-doc/sphinx/issues/7747

**Comment by sgn** [comment]
kea: https://github.com/void-linux/void-packages/commit/7f6b350c0ad296bd48ca68510a714e9a2b9363e8

**Comment by sgn** [comment]
Also pybind11, however, building classes.rst in isolation doesn't run into failure.
