### ISSUE TITLE
easyeffects: Segmentation fault x86_64-musl

### ISSUE THREAD

**Issue by hervyqa** [void-linux/void-packages#32784]
### System

* xuname:  `Void 5.13.13_1 x86_64-musl GenuineIntel uptodate rrnFFFF`
* package:  `easyeffects-6.1.0_1`

### Expected behavior
easyeffect it's working properly.

### Actual behavior
Segmentation fault on void musl.
```
[langit@l7 ~]$ easyeffects 
Segmentation fault
[langit@l7 ~]$ fish
➜  ~ easyeffects
fish: Job 1, 'easyeffects' terminated by signal SIGSEGV (Address boundary error)
➜  ~ 
```

service & status:
```
➜  ~ sudo vsv status pipe
Password: 

   SERVICE              STATE   ENABLED   PID      COMMAND           TIME
 ✔ pipewire-pulse       run     true      791      pipewire-pulse    36 minutes
 ✔ pipewire             run     true      792      pipewire          36 minutes

➜  ~ pactl info
Server String: /var/run/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 54
Tile Size: 65472
User Name: _pipewire
Host Name: l7
Server Name: PulseAudio (on PipeWire 0.3.34)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_00_1b.0.analog-stereo
Default Source: alsa_input.pci-0000_00_1b.0.analog-stereo
Cookie: ccbc:485d
➜  ~ 
```

### Steps to reproduce the behavior
```
➜  ~ sudo xbps-install -Su #sync and update
➜  ~ sudo xbps-install easyeffects
➜  ~ easyeffects
```

**Comment by hervyqa** [comment]
hi @paper42

**Comment by ericonr** [comment]
Backtrace:

```
#0  __strchrnul (s=0x1 <error: Cannot access memory at address 0x1>, c=c@entry=0x3b) at src/string/strchrnul.c:19
        w = <optimized out>
        k = <optimized out>
#1  0x00007ffff7fb1148 in strchr (s=<optimized out>, c=0x3b) at src/string/strchr.c:5
        r = <optimized out>
#2  0x00007ffff63945f5 in std::locale::_Impl::_Impl(char const*, unsigned long) () from /lib/libstdc++.so.6
No symbol table info available.
#3  0x00007ffff6394ff5 in std::locale::locale(char const*) () from /lib/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff6fe2af4 in ?? () from /lib/libgtkmm-4.0.so.0
No symbol table info available.
#5  0x00007ffff6fed03d in Gtk::Application::Application(Glib::ustring const&, Gio::Application::Flags) () from /lib/libgtkmm-4.0.so.0
No symbol table info available.
#6  0x00005555555cfa48 in Application::Application (this=<optimized out>, this=<optimized out>) at ../src/application.cpp:24
No locals.
#7  Application::create () at ../src/application.cpp:23
No locals.
#8  main (argc=0x1, argv=0x7fffffffe118) at ../src/easyeffects.cpp:53
        bindtext_output = <optimized out>
        app = {
          <std::__shared_ptr<Application, (__gnu_cxx::_Lock_policy)2>> = {
            <std::__shared_ptr_access<Application, (__gnu_cxx::_Lock_policy)2, false, false>> = {<No data fields>}, 
            members of std::__shared_ptr<Application, (__gnu_cxx::_Lock_policy)2>:
            _M_ptr = <optimized out>,
            _M_refcount = {
              _M_pi = <optimized out>
            }
          }, <No data fields>}
```

looks to be something in how gtk initializes locales (or because I removed the exception in bad locale creation). Can investigate further later if no one gets to it.

**Comment by hervyqa** [comment]
Fix.

![Screenshot_20220604_093227](https://user-images.githubusercontent.com/45872139/171974850-104a47f3-0ad5-4cd1-89df-ebdf2a30feb1.png)
