### ISSUE TITLE
Package Issue: multiMC

### ISSUE THREAD

**Issue by apirusKde** [void-linux/void-packages#32950]
Minecraft 1.17 Profile error:  (due to openjdk-11? *though it should support java runtime up to 55, but it says 52 in the multimc console*
~
~
~

MultiMC version: 0.6.12-custom

Java path is:
/usr/lib/jvm/java-1.8-openjdk/jre/bin/java

Checking Java version...
Java is version 1.8.0_272, using 64-bit architecture, from Void.

Kernel driver in use: amdgpu

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home//.multimc/instances/1.17.1/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /home/r/.multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /home/r/.multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /home//.multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /home/r/.multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /home/r/.multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /home/r/.multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /home/r/.multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /home//.multimc/libraries/com/mojang/blocklist/1.0.5/blocklist-1.0.5.jar
  /home//.multimc/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  /home//.multimc/libraries/com/github/oshi/oshi-core/5.7.5/oshi-core-5.7.5.jar
  /home//.multimc/libraries/net/java/dev/jna/jna/5.8.0/jna-5.8.0.jar
  /home//.multimc/libraries/net/java/dev/jna/jna-platform/5.8.0/jna-platform-5.8.0.jar
  /home//.multimc/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home//.multimc/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.14.1/log4j-slf4j18-impl-2.14.1.jar
  /home//.multimc/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  /home//.multimc/libraries/com/mojang/javabridge/1.1.23/javabridge-1.1.23.jar
  /home//.multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home//.multimc/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /home//.multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home//.multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home//.multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home//.multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /home//.multimc/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /home//.multimc/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  /home//.multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home//.multimc/libraries/com/mojang/authlib/2.3.31/authlib-2.3.31.jar
  /home//.multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home//.multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home//.multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home//.multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home//.multimc/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  /home//.multimc/libraries/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar
  /home//.multimc/libraries/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar
  /home//.multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /home//.multimc/libraries/com/mojang/minecraft/1.17.1/minecraft-1.17.1-client.jar

Native libraries:
  /home//.multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
  /home//.multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
  /home//.multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
  /home//.multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar
  /home//.multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
  /home//.multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar
  /home//.multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar
  /home//.multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar

Params:
  --username  --version MultiMC5 --gameDir /home//.multimc/instances/1.17.1/.minecraft --assetsDir /home//.multimc/assets --assetIndex 1.17 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 5041

Using onesix launcher.

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:171)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Process exited with code 1.

Minecraft version 1.8.9 error:
~
~
~

MultiMC version: 0.6.12-custom

Minecraft folder is:
/opt/.multimc/instances/1.8.9/.minecraft

Java path is:
/usr/lib/jvm/java-1.8-openjdk/jre/bin/java

Checking Java version...
Java is version 1.8.0_272, using 64-bit architecture, from Void.

Kernel driver in use: amdgpu

Main Class:
  net.minecraft.client.main.Main

Native path:
  /opt/.multimc/instances/1.8.9/natives

Libraries:
  /opt/.multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /opt/.multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /opt/.multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /opt/.multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /opt/.multimc/libraries/com/mojang/netty/1.7.7/netty-1.7.7.jar
  /opt/.multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /opt/.multimc/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  /opt/.multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /opt/.multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /opt/.multimc/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  /opt/.multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /opt/.multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /opt/.multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /opt/.multimc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /opt/.multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /opt/.multimc/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  /opt/.multimc/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  /opt/.multimc/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  /opt/.multimc/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /opt/.multimc/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  /opt/.multimc/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /opt/.multimc/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  /opt/.multimc/libraries/com/mojang/realms/1.7.59/realms-1.7.59.jar
  /opt/.multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /opt/.multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /opt/.multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /opt/.multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /opt/.multimc/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  /opt/.multimc/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  /opt/.multimc/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar
  /opt/.multimc/libraries/com/mojang/minecraft/1.8.9/minecraft-1.8.9-client.jar

Native libraries:
  /opt/.multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /opt/.multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Params:
  --username  --version MultiMC5 --gameDir /opt/.multimc/instances/1.8.9/.minecraft --assetsDir /opt/.multimc/assets --assetIndex 1.8 --uuid  --accessToken  --userProperties  --userType 

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 5763

Using onesix launcher.

[16:59:09] [Client thread/INFO]: Setting user: 
[16:59:09] [Client thread/INFO]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)
[16:59:10] [Client thread/INFO]: LWJGL Version: 2.9.4
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 9/13/21 4:59 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at ave.ar(SourceFile:560)
	at ave.am(SourceFile:361)
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ave.ar(SourceFile:560)
	at ave.am(SourceFile:361)

-- Initialization --
Details:
Stacktrace:
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 5.13.15_1
	Java Version: 1.8.0_272, Void
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Void
	Memory: 458668152 bytes (437 MB) / 514850816 bytes (491 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: No
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /opt/.multimc/instances/1.8.9/.minecraft/crash-reports/crash-2021-09-13_16.59.10-client.txt
[16:59:10] [Client Shutdown Thread/INFO]: Stopping server
Process exited with code 255.

**Comment by apirusKde** [comment]
Update: I have previously set the java version to java-1-8. Now when openjdk-11 is in use i get this error with Minecraft 1.17:

Minecraft process ID: 6916


Using onesix launcher.

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:171)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Process exited with code 1.


Error with Minecraft 1.8.9:


Params:
  --username  --version MultiMC5 --gameDir /opt/.multimc/instances/1.8.9/.minecraft --assetsDir /opt/.multimc/assets --assetIndex 1.8 --uuid  --accessToken  --userProperties  --userType 

Window size: max (if available)

Java Arguments:
[-Xms1024m, -Xmx8000m, -Duser.language=en]


Minecraft process ID: 7020


Using onesix launcher.

[17:31:29] [Client thread/INFO]: Setting user: premop
[17:31:29] [Client thread/INFO]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)
[17:31:30] [Client thread/INFO]: LWJGL Version: 2.9.4
Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
Process exited with code 127.

**Comment by Hnaguski** [comment]
Minecraft 1.17 requires java 16 or higher, for now that isn't packaged in void but you can download it from [adoptopenjdk](https://adoptopenjdk.net/?variant=openjdk16&jvmVariant=hotspot). Once that's downloaded, you can tell multimc to use it from the instance settings menu.

**Comment by apirusKde** [comment]
alright, ive submitted a package request for openjdk-17, but version 1.8.9 throws a different error. one i try to run it with that java version i will update the issue

**Comment by apirusKde** [comment]
Okay, now Minecraft 1.17 works. Minecraft 1.8.9 throws a different error:


Time: 9/15/21, 2:06 AM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at ave.ar(SourceFile:560)
	at ave.am(SourceFile:361)
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 12 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ave.ar(SourceFile:560)
	at ave.am(SourceFile:361)

-- Initialization --
Details:
Stacktrace:
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 5.13.15_1
	Java Version: 16.0.2, Eclipse Foundation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Foundation
	Memory: 860153272 bytes (820 MB) / 1082130432 bytes (1032 MB) up to 8388608000 bytes (8000 MB)
	JVM Flags: 2 total; -Xms1024m -Xmx8000m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: No
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: Cannot invoke "bns.c()" because the return value of "ave.b(ave)" is null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /opt/.multimc/instances/1.8.9/.minecraft/crash-reports/crash-2021-09-15_02.06.39-client.txt
[02:06:39] [Client Shutdown Thread/INFO]: Stopping server
Process exited with code 255.

**Comment by Hnaguski** [comment]
Do you have mesa installed? It seems like some sort of graphics issue based on the error message. I tried 1.8.9 with Java 16 on my (AMD) machine and it seems to have worked so I'm not quite convinced it's a packaging issue. You might have better luck asking on a multimc support channel.

**Comment by kotajacob** [comment]
I've had issues in the past with very old versions of minecraft not working properly on newer java versions. In this case you're probably just missing graphics drivers like @Hnaguski said, but you can try launching the 1.8.9 instance with an older jdk. Here's a screenshot of [my beta 1.7.3 instance configured to use openjdk-8](https://paste.nilsu.org/91b5ead8b4bb8f647103fda5397d09055c5c7bd7.webp). You need to install the `openjdk-8` package for that to work.

Ultimately it's looking like the MultiMC package might need to be removed anyway. The [upstream license doesn't permit using the logo or name](https://github.com/MultiMC/MultiMC5/issues/4102) in packages such as ours 🙃. So the only way MultiMC can continue to be packaged is if we forked and renamed it. It's a mess, for now you're best off downloading a [procompiled binary it from their website](https://multimc.org/#Download), installing `qt5-svg`, and downloading the latest java manually like @Hnaguski suggested (or waiting on our package to be updated).

Normally you'd want to extract the MultiMC tar somewhere like `~/.local/opt/` and then link the executable to your local bin with `ln -s ~/.local/opt/MultiMC/MultiMC ~/.local/bin/MultiMC`. You could also create a `multimc.desktop` file in `~/.local/share/applications/` with the following if you want it to show up in most desktop environment launchers:
```desktop
[Desktop Entry]
Version=1
Type=Application
Name=minecraft
GenericName=Minecraft
Comment=Game
Exec=/home/<Your Username>/.local/opt/MultiMC/MultiMC
Actions=
Categories=Game;
```

**Comment by ImperatorStorm** [comment]
> So the only way MultiMC can continue to be packaged is if we forked and renamed it.

You could also go the way of the [.deb package](https://github.com/MultiMC/MultiMC5/blob/develop/launcher/package/ubuntu/multimc/opt/multimc/run.sh), which just downloads the latest multimc binary from [multimc.org](https://multimc.org/#Download). Peterix is fine with this, as stated in https://github.com/MultiMC/MultiMC5/issues/4102#issuecomment-920334126

**Comment by Duncaen** [comment]
I think the best solution here is to make the package restricted, we won't build or ship it and users are free to either download the binaries themselves or use the repository to build the package from source themselves for personal use.

There are a few problems I see with shipping binaries:
* They only support two of the architectures we ship packages for.
* We can't rebuild it if any of the linked shared libraries require a rebuild (not sure how high the chances are for that to happen, since its just qt5 and zlib).
* Downloading binaries at install time just results in a bad user experience, completely negating all benefits of using a package manager.

**Comment by Hnaguski** [comment]
> You could also go the way of the [.deb package](https://github.com/MultiMC/MultiMC5/blob/develop/launcher/package/ubuntu/multimc/opt/multimc/run.sh), which just downloads the latest multimc binary from [multimc.org](https://multimc.org/#Download). Peterix is fine with this, as stated in [MultiMC/MultiMC5#4102 (comment)](https://github.com/MultiMC/MultiMC5/issues/4102#issuecomment-920345089)

I definitely share Duncaen's opinion on the matter, this wouldn't be a good solution for a void package. Unless someone wants to maintain a fork we can build from source, the package should be restricted.

**Comment by fosslinux** [comment]
Yes it should just be restricted IMO

**Comment by apirusKde** [comment]
if anyone is still experiencing issues with minecraft 1.8.9, you need to have the package xrandr installed. Also use openjdk8 with 1.8.9, and use openjdk15 and up for 1.17 (tested on openjdk16) for those versions to work.
