### ISSUE TITLE
`jupyter-core` is not found

### ISSUE THREAD

**Issue by rivanfebrian123** [void-linux/void-packages#33536]
### System

* xuname: Void 5.13.19_1 x86_64 GenuineIntel notuptodate rrrmFFFFF
* package:  python3-jupyter_notebook-6.3.0_2

### Actual behavior
```
[rivanfebrian123@RVN ~]$ jupyter notebook
Traceback (most recent call last):
  File "/usr/bin/jupyter", line 33, in <module>
    sys.exit(load_entry_point('jupyter-core==4.7.1', 'console_scripts', 'jupyter')())
  File "/usr/bin/jupyter", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: jupyter-core
```

When I try to install `jupyter-core` manually, it says:
```
[rivanfebrian123@RVN ~]$ sudo xbps-install -S python3-jupyter_core
Password: 
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/multilib/nonfree/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/multilib/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/nonfree/x86_64-repodata' ...
Package `python3-jupyter_core' already installed.
```

### Steps to reproduce the behavior
`sudo xbps-install -S python3-jupyter_notebook`

**Comment by dkwo** [comment]
Not a solution, but the more modern `jupyterlab` works for me, perhaps you could give it a try.

**Comment by ahesford** [comment]
The `python3-jupyter_core` package you have is too new. You are still running Python 3.9, but we just moved Void to 3.10. You'll need to do a full system update.
