### ISSUE TITLE
openshot hangs never starts

### ISSUE THREAD

**Issue by zlice** [void-linux/void-packages#33897]
### System

* xuname:  `Void 5.14.3 x86_64 AuthenticAMD notuptodate hold rrrmFFFFFFFFF`
* package: `openshot-2.5.1_3`

### Expected behavior

Get to GUI

### Actual behavior

openshot hangs

### Steps to reproduce the behavior

```
openshot-qt 
Loaded modules from installed directory: /usr/lib/python3.10/site-packages/openshot_qt

         app:INFO ------------------------------------------------
         app:INFO             Thu Nov  4 07:38:06 2021            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)            
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
         app:INFO platform: Linux-5.14.3-x86_64-with-glibc2.32
         app:INFO processor: 
         app:INFO machine: x86_64
         app:INFO python version: 3.10.0
         app:INFO qt5 version: 5.15.2
         app:INFO pyqt5 version: 5.15.5
     metrics:ERROR Error determining OS version in metrics.py
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: en_US.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
         app:INFO Setting font to /usr/lib/python3.10/site-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
QMainWindow::addDockWidget: invalid 'area' argument
     ui_util:INFO Initializing UI for MainWindow
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/bin/openshot-qt", line 33, in <module>
    sys.exit(load_entry_point('openshot-qt==2.5.1', 'gui_scripts', 'openshot-qt')())
  File "/usr/lib/python3.10/site-packages/openshot_qt/launch.py", line 97, in main
    app = OpenShotApp(argv)
  File "/usr/lib/python3.10/site-packages/openshot_qt/classes/app.py", line 221, in __init__
    self.window = MainWindow(mode)
  File "/usr/lib/python3.10/site-packages/openshot_qt/windows/main_window.py", line 2521, in __init__
    self.timeline = TimelineWebView(self)
  File "/usr/lib/python3.10/site-packages/openshot_qt/windows/views/timeline_webview.py", line 3000, in __init__
    self.cache_renderer.setInterval(0.5 * 1000)
TypeError: setInterval(self, int): argument 1 has unexpected type 'float'
     version:INFO Found current version: {"openshot_version": "2.6.1", "error_rate_stable": 0.05, "error_rate_unstable": 0.05}

^C      logger:ERROR Exception ignored in:
      logger:ERROR <module 'threading' from '/usr/lib/python3.10/threading.py'>
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/lib/python3.10/threading.py", line 1538, in _shutdown
      logger:ERROR lock.acquire()
      logger:ERROR KeyboardInterrupt
      logger:ERROR :
         app:INFO             OpenShot's session ended            
         app:INFO             Thu Nov  4 07:39:43 2021            
         app:INFO ================================================



```

**Comment by loreb** [comment]
Superficially it looks like they fixed it upstream in https://github.com/OpenShot/openshot-qt/commit/cd69f2ad8d10c26b20eb9ae46bcc288f3c322b85, the package is a bit outdated - see if applying the patch above fixes your problem.

**Comment by zlice** [comment]
Looks like the same issue

**Comment by Johnnynator** [comment]
Tested 2.6.1 quickly, it is differently broken

```
Unhandled Python exception
Caught signal 6 (SIGABRT)
---- Unhandled Exception: Stack Trace ----
  /usr/lib/libc.so.6             ( abort                                     + 0x112 )  [0x7f9458d27536]
  /usr/lib/libQt5Core.so.5       (                                           + 0x91c91)  [0x7f945771cc91]
  /usr/lib/python3.10/site-packages/PyQt5/QtCore.abi3.so (                                           + 0xb5222)  [0x7f9457d16222]
  /usr/lib/python3.10/site-packages/PyQt5/sip.so (                                           + 0x116a3)  [0x7f9457c4b6a3]
  /usr/lib/python3.10/site-packages/PyQt5/QtWidgets.abi3.so (                                           + 0x14cb2d)  [0x7f9454b30b2d]
  /usr/lib/python3.10/site-packages/PyQt5/QtWidgets.abi3.so (                                           + 0x3ca63c)  [0x7f9454dae63c]
  /usr/lib/libQt5Widgets.so.5    ( QWidget::event(QEvent*)                   + 0x1ce )  [0x7f94544c503e]
  /usr/lib/python3.10/site-packages/PyQt5/QtWidgets.abi3.so (                                           + 0x3ccc03)  [0x7f9454db0c03]
  /usr/lib/libQt5Widgets.so.5    ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x7f  )  [0x7f945448517f]
  /usr/lib/python3.10/site-packages/PyQt5/QtWidgets.abi3.so (                                           + 0x38d6ae)  [0x7f9454d716ae]
  /usr/lib/libQt5Core.so.5       ( QCoreApplication::notifyInternal2(QObject*, QEvent*)  + 0x12a )  [0x7f945793a19a]
  /usr/lib/libQt5Widgets.so.5    ( QWidgetPrivate::sendPaintEvent(QRegion const&)  + 0x36  )  [0x7f94544bd166]
  /usr/lib/libQt5Widgets.so.5    ( QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x7f2 )  [0x7f94544bd9b2]
  /usr/lib/libQt5Widgets.so.5    ( QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x503 )  [0x7f94544bed03]
  /usr/lib/libQt5Widgets.so.5    ( QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x50c )  [0x7f94544bd6cc]
  /usr/lib/libQt5Widgets.so.5    ( QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x503 )  [0x7f94544bed03]
  /usr/lib/libQt5Widgets.so.5    ( QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x50c )  [0x7f94544bd6cc]
  /usr/lib/libQt5Widgets.so.5    ( QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x503 )  [0x7f94544bed03]
  /usr/lib/libQt5Widgets.so.5    ( QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x322 )  [0x7f94544beb22]
  /usr/lib/libQt5Widgets.so.5    ( QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x322 )  [0x7f94544beb22]
  /usr/lib/libQt5Widgets.so.5    ( QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x322 )  [0x7f94544beb22]
  /usr/lib/libQt5Widgets.so.5    ( QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x322 )  [0x7f94544beb22]
  /usr/lib/libQt5Widgets.so.5    ( QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)  + 0x50c )  [0x7f94544bd6cc]
  /usr/lib/libQt5Widgets.so.5    (                                           + 0x17388a)  [0x7f945449588a]
  /usr/lib/libQt5Widgets.so.5    (                                           + 0x1740cb)  [0x7f94544960cb]
  /usr/lib/libQt5Widgets.so.5    (                                           + 0x1be66f)  [0x7f94544e066f]
  /usr/lib/libQt5Widgets.so.5    ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x7f  )  [0x7f945448517f]
  /usr/lib/python3.10/site-packages/PyQt5/QtWidgets.abi3.so (                                           + 0x38d6ae)  [0x7f9454d716ae]
  /usr/lib/libQt5Core.so.5       ( QCoreApplication::notifyInternal2(QObject*, QEvent*)  + 0x12a )  [0x7f945793a19a]
  /usr/lib/libQt5Gui.so.5        ( QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*)  + 0x8d  )  [0x7f9453d8b9fd]
  /usr/lib/libQt5Gui.so.5        ( QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0xac  )  [0x7f9453d606bc]
  /usr/lib/qt5/plugins/platforms/../../../libQt5WaylandClient.so.5 (                                           + 0xa73c0)  [0x7f94461f03c0]
  /usr/lib/libglib-2.0.so.0      ( g_main_context_dispatch                   + 0x25b )  [0x7f9456c84c0b]
  /usr/lib/libglib-2.0.so.0      (                                           + 0x53eb8)  [0x7f9456c84eb8]
  /usr/lib/libglib-2.0.so.0      ( g_main_context_iteration                  + 0x2f  )  [0x7f9456c84f6f]
  /usr/lib/libQt5Core.so.5       ( QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x5f  )  [0x7f945799157f]
  /usr/lib/libQt5Core.so.5       ( QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x12b )  [0x7f9457938b4b]
  /usr/lib/libQt5Core.so.5       ( QCoreApplication::exec()                  + 0x90  )  [0x7f9457940dd0]
  /usr/lib/python3.10/site-packages/PyQt5/QtWidgets.abi3.so (                                           + 0x38c3bd)  [0x7f9454d703bd]
  /usr/lib/libpython3.10.so.1.0  (                                           + 0xebcb4)  [0x7f9458fb2cb4]
  /usr/lib/libpython3.10.so.1.0  ( _PyObject_MakeTpCall                      + 0x95  )  [0x7f9458f759f5]
  /usr/lib/libpython3.10.so.1.0  ( _PyEval_EvalFrameDefault                  + 0x89e5)  [0x7f9458f34f75]
  /usr/lib/libpython3.10.so.1.0  (                                           + 0x1754f4)  [0x7f945903c4f4]
  /usr/lib/libpython3.10.so.1.0  ( _PyEval_EvalFrameDefault                  + 0x6eff)  [0x7f9458f3348f]
  /usr/lib/libpython3.10.so.1.0  (                                           + 0x1754f4)  [0x7f945903c4f4]
  /usr/lib/libpython3.10.so.1.0  ( PyEval_EvalCode                           + 0x90  )  [0x7f945903c6b0]
  /usr/lib/libpython3.10.so.1.0  (                                           + 0x1b3dea)  [0x7f945907adea]
  /usr/lib/libpython3.10.so.1.0  (                                           + 0x1b3ff7)  [0x7f945907aff7]
  /usr/lib/libpython3.10.so.1.0  (                                           + 0x1b40df)  [0x7f945907b0df]
  /usr/lib/libpython3.10.so.1.0  ( _PyRun_SimpleFileObject                   + 0x11a )  [0x7f945907d16a]
  /usr/lib/libpython3.10.so.1.0  ( _PyRun_AnyFileObject                      + 0x3b  )  [0x7f945907d61b]
  /usr/lib/libpython3.10.so.1.0  ( Py_RunMain                                + 0x41e )  [0x7f945909962e]
  /usr/lib/libpython3.10.so.1.0  ( Py_BytesMain                              + 0x56  )  [0x7f9459099e86]
  /usr/lib/libc.so.6             ( __libc_start_main                         + 0xea  )  [0x7f9458d28e0a]
  /usr/bin/python3               ( _start                                    + 0x2a  )  [0x559151e6208a]
---- End of Stack Trace ----
```
