### ISSUE TITLE
FreeCAD 0.19.2 crashes on sketches

### ISSUE THREAD

**Issue by zlice** [void-linux/void-packages#34016]
### System

* xuname:   Void 5.15.1 x86_64 AuthenticAMD uptodate hold rrrmFFFFFFFFF
* package:  freecad-0.19.2_2

### Expected behavior

Able to create new sketches

### Actual behavior

```

Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x3d000) [0x7f0216727000]
#1  /usr/lib/libQt5Gui.so.5(+0x5a9c5a) [0x7f021767cc5a]
#2  /usr/lib/libQt5Gui.so.5(+0x3fa757) [0x7f02174cd757]
#3  0x7f02174b9934 in QPaintEngineEx::drawPixmapFragments(QPainter::PixmapFragment const*, int, QPixmap const&, QFlags<QPainter::PixmapFragmentHint>) from /usr/lib/libQt5Gui.so.5+0x1d4
#4  0x7f021797901d in qDrawBorderPixmap(QPainter*, QRect const&, QMargins const&, QPixmap const&, QRect const&, QMargins const&, QTileRules const&, QFlags<QDrawBorderPixmap::DrawingHint>) from /usr/lib/libQt5Widgets.so.5+0x187d
#5  0x7f02179e320e in QFusionStyle::drawPrimitive(QStyle::PrimitiveElement, QStyleOption const*, QPainter*, QWidget const*) const from /usr/lib/libQt5Widgets.so.5+0x146e
#6  0x7f02179e952b in QFusionStyle::drawComplexControl(QStyle::ComplexControl, QStyleOptionComplex const*, QPainter*, QWidget const*) const from /usr/lib/libQt5Widgets.so.5+0x311b
#7  0x7f0217a3bfa1 in QGroupBox::paintEvent(QPaintEvent*) from /usr/lib/libQt5Widgets.so.5+0x81
#8  0x7f021794c03e in QWidget::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0x1ce
#9  0x7f0217a3d10d in QGroupBox::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0x8d
#10  0x7f021790c17f in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x7f
#11  0x7f0218dd3328 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib64/libFreeCADGui.so+0x88
#12  0x7f0216de219a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x12a
#13  0x7f0217944166 in QWidgetPrivate::sendPaintEvent(QRegion const&) from /usr/lib/libQt5Widgets.so.5+0x36
#14  0x7f02179449b2 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x7f2
#15  0x7f0217945d03 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x503
#16  0x7f0217945b22 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x322
#17  0x7f0217945b22 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x322
#18  0x7f0217945b22 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x322
#19  0x7f0217945b22 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x322
#20  0x7f0217945b22 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x322
#21  0x7f02179446cc in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x50c
#22  /usr/lib/libQt5Widgets.so.5(+0x17388a) [0x7f021791c88a]
#23  /usr/lib/libQt5Widgets.so.5(+0x1ba321) [0x7f0217963321]
#24  /usr/lib/libQt5Widgets.so.5(+0x1be72c) [0x7f021796772c]
#25  0x7f021790c17f in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x7f
#26  0x7f0218dd3328 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib64/libFreeCADGui.so+0x88
#27  0x7f0216de219a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x12a
#28  0x7f021720dc99 in QGuiApplicationPrivate::processGeometryChangeEvent(QWindowSystemInterfacePrivate::GeometryChangeEvent*) from /usr/lib/libQt5Gui.so.5+0x179
#29  0x7f02171e76bc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Gui.so.5+0xac
#30  /usr/lib/qt5/plugins/platforms/../../../libQt5XcbQpa.so.5(+0x6340a) [0x7f021168140a]
#31  /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x25b) [0x7f021491ec0b]
#32  /usr/lib/libglib-2.0.so.0(+0x53eb8) [0x7f021491eeb8]
#33  /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2f) [0x7f021491ef6f]
#34  0x7f0216e3957f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x5f
#35  0x7f0216de0b4b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x12b
#36  0x7f0217b05147 in QDialog::exec() from /usr/lib/libQt5Widgets.so.5+0x187
#37  0x7f0144947a5c in CmdSketcherNewSketch::activated(int) from /usr/lib/freecad/lib64/SketcherGui.so+0x10c
#38  0x7f0218e01f91 in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /usr/lib/freecad/lib64/libFreeCADGui.so+0x4d1
#39  /usr/lib/libQt5Core.so.5(+0x2e57b0) [0x7f0216e187b0]
#40  0x7f0217905b82 in QAction::triggered(bool) from /usr/lib/libQt5Widgets.so.5+0x42
#41  0x7f02179083c1 in QAction::activate(QAction::ActionEvent) from /usr/lib/libQt5Widgets.so.5+0xe1
#42  /usr/lib/libQt5Widgets.so.5(+0x252262) [0x7f02179fb262]
#43  0x7f02179fb381 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) from /usr/lib/libQt5Widgets.so.5+0xf1
#44  0x7f0217aeac7a in QToolButton::mouseReleaseEvent(QMouseEvent*) from /usr/lib/libQt5Widgets.so.5+0xa
#45  0x7f021794c03e in QWidget::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0x1ce
#46  0x7f021790c17f in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x7f
#47  0x7f021791306b in QApplication::notify(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x49b
#48  0x7f0218dd3328 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib64/libFreeCADGui.so+0x88
#49  0x7f0216de219a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x12a
#50  0x7f0217912096 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /usr/lib/libQt5Widgets.so.5+0x1d6
#51  /usr/lib/libQt5Widgets.so.5(+0x1bb0a1) [0x7f02179640a1]
#52  /usr/lib/libQt5Widgets.so.5(+0x1be3ce) [0x7f02179673ce]
#53  0x7f021790c17f in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x7f
#54  0x7f0218dd3328 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib64/libFreeCADGui.so+0x88
#55  0x7f0216de219a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x12a
#56  0x7f02172115c3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /usr/lib/libQt5Gui.so.5+0x653
#57  0x7f02171e76bc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Gui.so.5+0xac
#58  /usr/lib/qt5/plugins/platforms/../../../libQt5XcbQpa.so.5(+0x6340a) [0x7f021168140a]
#59  /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x25b) [0x7f021491ec0b]
#60  /usr/lib/libglib-2.0.so.0(+0x53eb8) [0x7f021491eeb8]
#61  /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2f) [0x7f021491ef6f]
#62  0x7f0216e3957f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x5f
#63  0x7f0216de0b4b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x12b
#64  0x7f0216de8dd0 in QCoreApplication::exec() from /usr/lib/libQt5Core.so.5+0x90
#65  0x7f0218d48f68 in Gui::Application::runApplication() from /usr/lib/freecad/lib64/libFreeCADGui.so+0x1978
#66  FreeCAD(+0x4954) [0x560eeffb7954]
#67  /usr/lib/libc.so.6(__libc_start_main+0xea) [0x7f0216711e0a]
#68  FreeCAD(+0x4c4a) [0x560eeffb7c4a]
```

### Steps to reproduce the behavior

- open sketcher workbench
- create sketch

(Works fine in AppImage 0.19-24291)

### Comments

I've had weird issues with FreeCAD on my system before. The splash screen had to be disabled to even run a bit back but ran on another system with Void fine.

**Comment by parallelistic** [comment]
i'm unable to replicate this on my system, my steps are as follows:
* create new document
* switch to sketcher workbench
* create a new sketch

**Comment by zlice** [comment]
Would you mind sharing your config?

Starting with no config bombs because of splash screen, so I can't try with that.

splash bomb seg fault (can open another issue for that)

```
Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x3d000) [0x7fa033b47000]
#1  0x7fa0347ff9ff in QBackingStore::beginPaint(QRegion const&) from /usr/lib/libQt5Gui.so.5+0xcf
#2  /usr/lib/libQt5Widgets.so.5(+0x1736c2) [0x7fa034d3c6c2]
#3  0x7fa034d6c767 in QWidget::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0x8f7
#4  0x7fa034d2c17f in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x7f
#5  0x7fa0361f3328 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib64/libFreeCADGui.so+0x88
#6  0x7fa03420219a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x12a
#7  /usr/lib/libQt5Widgets.so.5(+0x1746f5) [0x7fa034d3d6f5]
#8  /usr/lib/libQt5Widgets.so.5(+0x1770f0) [0x7fa034d400f0]
#9  0x7fa034d54d42 in QWidget::repaint(QRect const&) from /usr/lib/libQt5Widgets.so.5+0x82
#10  0x7fa034d54daa in QWidget::repaint() from /usr/lib/libQt5Widgets.so.5+0x3a
#11  0x7fa034ece8a9 in QSplashScreen::repaint() from /usr/lib/libQt5Widgets.so.5+0x9
#12  0x7fa036580995 in Gui::SplashObserver::Log(char const*) from /usr/lib/freecad/lib64/libFreeCADGui.so+0x115
#13  0x7fa0356b09fe in Base::ConsoleSingleton::NotifyLog(char const*) from /usr/lib/freecad/lib64/libFreeCADBase.so+0xae
#14  0x7fa0356b0c5b in Base::ConsoleSingleton::Log(char const*, ...) from /usr/lib/freecad/lib64/libFreeCADBase.so+0x20b
#15  0x7fa03615bbb0 in messageHandler(QtMsgType, QMessageLogContext const&, QString const&) from /usr/lib/freecad/lib64/libFreeCADGui.so+0x50
#16  /usr/lib/libQt5Core.so.5(+0xc4b98) [0x7fa034017b98]
#17  /usr/lib/libQt5Core.so.5(+0xc4cb9) [0x7fa034017cb9]
#18  0x7fa033fe4516 in QMessageLogger::warning(char const*, ...) const from /usr/lib/libQt5Core.so.5+0xb6
#19  /usr/lib/qt5/plugins/platforms/../../../libQt5XcbQpa.so.5(+0x576a0) [0x7fa02ec556a0]
#20  /usr/lib/qt5/plugins/platforms/../../../libQt5XcbQpa.so.5(+0x5867e) [0x7fa02ec5667e]
#21  /usr/lib/qt5/plugins/platforms/../../../libQt5XcbQpa.so.5(+0x5a31b) [0x7fa02ec5831b]
#22  0x7fa0347ff43f in QBackingStore::resize(QSize const&) from /usr/lib/libQt5Gui.so.5+0xaf
#23  /usr/lib/libQt5Widgets.so.5(+0x172c61) [0x7fa034d3bc61]
#24  /usr/lib/libQt5Widgets.so.5(+0x1740cb) [0x7fa034d3d0cb]
#25  /usr/lib/libQt5Widgets.so.5(+0x1be66f) [0x7fa034d8766f]
#26  0x7fa034d2c17f in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x7f
#27  0x7fa0361f3328 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib64/libFreeCADGui.so+0x88
#28  0x7fa03420219a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x12a
#29  0x7fa0346329fd in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) from /usr/lib/libQt5Gui.so.5+0x8d
#30  0x7fa0346076bc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Gui.so.5+0xac
#31  /usr/lib/qt5/plugins/platforms/../../../libQt5XcbQpa.so.5(+0x6340a) [0x7fa02ec6140a]
#32  /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x25b) [0x7fa031d3ec0b]
#33  /usr/lib/libglib-2.0.so.0(+0x53eb8) [0x7fa031d3eeb8]
#34  /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2f) [0x7fa031d3ef6f]
#35  0x7fa0342595f0 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0xd0
#36  0x7fa036580995 in Gui::SplashObserver::Log(char const*) from /usr/lib/freecad/lib64/libFreeCADGui.so+0x115
#37  0x7fa0356b09fe in Base::ConsoleSingleton::NotifyLog(char const*) from /usr/lib/freecad/lib64/libFreeCADBase.so+0xae
#38  0x7fa0356b0c5b in Base::ConsoleSingleton::Log(char const*, ...) from /usr/lib/freecad/lib64/libFreeCADBase.so+0x20b
#39  0x7fa0356b138b in Base::ConsoleSingleton::sPyLog(_object*, _object*) from /usr/lib/freecad/lib64/libFreeCADBase.so+0x6b
#40  /usr/lib/libpython3.10.so.1.0(+0xebcb4) [0x7fa03533ecb4]
#41  /usr/lib/libpython3.10.so.1.0(_PyObject_MakeTpCall+0x95) [0x7fa0353019f5]
#42  /usr/lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x6fff) [0x7fa0352bf58f]
#43  /usr/lib/libpython3.10.so.1.0(+0x1754f4) [0x7fa0353c84f4]
#44  /usr/lib/libpython3.10.so.1.0(PyEval_EvalCode+0x90) [0x7fa0353c86b0]
#45  /usr/lib/libpython3.10.so.1.0(+0x1b3dea) [0x7fa035406dea]
#46  /usr/lib/libpython3.10.so.1.0(+0x1b3ff7) [0x7fa035406ff7]
#47  /usr/lib/libpython3.10.so.1.0(PyRun_StringFlags+0x75) [0x7fa0354097c5]
#48  0x7fa0356c3916 in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /usr/lib/freecad/lib64/libFreeCADBase.so+0x66
#49  0x7fa03615dfbf in Gui::Application::runInitGuiScript() from /usr/lib/freecad/lib64/libFreeCADGui.so+0x3f
#50  0x7fa03616881e in Gui::Application::runApplication() from /usr/lib/freecad/lib64/libFreeCADGui.so+0x122e
#51  FreeCAD(+0x4954) [0x56501616c954]
#52  /usr/lib/libc.so.6(__libc_start_main+0xea) [0x7fa033b31e0a]
#53  FreeCAD(+0x4c4a) [0x56501616cc4a]
```

**Comment by parallelistic** [comment]
I have not managed to replicate the splash screen crash either on my system, therefore my config is the default, I will try to replicate it on a new system when I get home.

**Comment by parallelistic** [comment]
Which config are you referring to?
my user.cfg: https://pastebin.com/e5iLMaRQ

**Comment by zlice** [comment]
Yes, that looks right. ~/.config/FreeCAD/FreeCAD.conf

I double checked, it looks like it's actually removing ~/.FreeCAD that causes the seg fault, the splash screen is fine. So now I'm really confused. Not sure why it's crashing then in either case.

**Comment by parallelistic** [comment]
My FreeCAD.conf file: https://pastebin.com/SigakK9V
Removing ~/.FreeCAD leads to it being generated properly again.
I also tried installing FreeCAD on a new system, worked fine... maybe it's something related to your system?

**Comment by zlice** [comment]
But what? I dont have a custom compiled FreeCAD or QT or anything. Python libs maybe?

**Comment by notthewave** [comment]
Wayland seems to be the issue.
setting QT_QPA_PLATFORM="xcb" solves this for me.

**Comment by zlice** [comment]
I am not on wayland, this does not fix the issue for me.

**Comment by zlice** [comment]
0.19.4 launches (with splash screen)

currently using mesa 22.1.1, kernel 5.18.1
