### ISSUE TITLE
gnuradio-companion fails to start

### ISSUE THREAD

**Issue by AppMathIsRealMath** [void-linux/void-packages#35070]
### System

* xuname:  
Void 5.15.14_1 x86_64 GenuineIntel uptodate rrrmFFFFFFFFFFFFFF

* package:  
gnuradio-3.8.0.0_9

### Expected behavior
Start gnuradio-companion successfully

### Actual behavior
Fails with:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 939, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sbin/gnuradio-companion", line 63, in check_gtk
    from gi.repository import Gtk
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 941, in _find_spec
  File "<frozen importlib._bootstrap>", line 914, in _find_spec_legacy
ImportWarning: DynamicImporter.find_spec() not found; falling back to find_module()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 939, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sbin/gnuradio-companion", line 100, in <module>
    check_gtk()
  File "/sbin/gnuradio-companion", line 67, in check_gtk
    die(err, "Failed to initialize GTK. If you are running over ssh, "
  File "/sbin/gnuradio-companion", line 42, in die
    from gi.repository import Gtk
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 941, in _find_spec
  File "<frozen importlib._bootstrap>", line 914, in _find_spec_legacy
ImportWarning: DynamicImporter.find_spec() not found; falling back to find_module()

### Steps to reproduce the behavior
Install gnuradio and execute "gnuradio-companion"

**Comment by ericonr** [comment]
Can you check if https://github.com/void-linux/void-packages/pull/35049 fixes this?

Pinging @unspecd for awareness

**Comment by unspecd** [comment]
Try installing `python3-gobject`.
```console
$ sudo xbps-install python3-gobject
```

**Comment by AppMathIsRealMath** [comment]
Same problem after reinstalling pango python3-gobject gir-freedesktop. If you have some patches I can test I'm happy to build from source.

**Comment by ericonr** [comment]
Does `xbps-pkgdb -a` print any erorrs?

The pull request I linked has an update patch for gnuradio.

**Comment by paper42** [comment]
I can reproduce this issue, #35049 fixes it for me.
