### ISSUE TITLE
Error When Building Visual Studio Code On Musl

### ISSUE THREAD

**Issue by JuniorSuperTux** [void-linux/void-packages#35176]
### System

* xuname:  
  Void 5.15.14_1 x86_64-musl GenuineIntel notuptodate rFF
* package:  
  vscode-1.63.2_1

### Expected behavior
Compiles Visual Studio Code OSS binary successfully and places it in local repository.

### Actual behavior
Here's the output of `./xbps-src pkg vscode`:
```
=> xbps-src: updating repositories for host (x86_64-musl)...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata' ...
x86_64-musl-repodata: 1687KB [avg rate: 442KB/s]
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/nonfree/x86_64-musl-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/debug/x86_64-musl-repodata' ...
x86_64-musl-repodata: 781KB [avg rate: 119KB/s]
=> xbps-src: updating software in / masterdir...
=> xbps-src: cleaning up / masterdir...
=> vscode-1.63.2_1: removing autodeps, please wait...
=> vscode-1.63.2_1: building for x86_64-musl...
   [host] pkg-config-0.29.2_3: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [host] python-2.7.18.4_1: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [host] nodejs-16.13.2_2: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [host] yarn-1.22.10_1: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [host] tar-1.34_2: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [host] git-2.34.1_1: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [host] ripgrep-13.0.0_1: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [target] libxkbfile-devel-1.1.0_1: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [target] libsecret-devel-0.20.4_1: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [target] electron13-13.6.7_1: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [runtime] libXtst-1.2.3_2: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [runtime] libxkbfile-1.1.0_1: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [runtime] nss-3.74_1: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [runtime] dejavu-fonts-ttf-2.37_2: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [runtime] xdg-utils-1.1.3_4: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [runtime] ripgrep-13.0.0_1: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [runtime] electron13-13.6.7_1: found (https://alpha.de.repo.voidlinux.org/current/musl)
=> vscode-1.63.2_1: installing host dependencies: pkg-config-0.29.2_3 python-2.7.18.4_1 nodejs-16.13.2_2 yarn-1.22.10_1 tar-1.34_2 git-2.34.1_1 ripgrep-13.0.0_1 ...
=> vscode-1.63.2_1: installing target dependencies: libxkbfile-devel-1.1.0_1 libsecret-devel-0.20.4_1 electron13-13.6.7_1 ...
=> vscode-1.63.2_1: running do-fetch hook: 00-distfiles ...
=> vscode-1.63.2_1: fetching distfile '1.63.2.tar.gz'...
1.63.2.tar.gz: [0B 0%] 2193KB/s ETA: unknown
1.63.2.tar.gz: [0B 0%] 273KB/s ETA: unknown
1.63.2.tar.gz: [0B 0%] 833KB/s ETA: unknown
1.63.2.tar.gz: [0B 0%] 1131KB/s ETA: unknown
1.63.2.tar.gz: [0B 0%] 1382KB/s ETA: unknown
1.63.2.tar.gz: [0B 0%] 1488KB/s ETA: unknown
1.63.2.tar.gz: [0B 0%] 1555KB/s ETA: unknown
1.63.2.tar.gz: [0B 0%] 1531KB/s ETA: unknown
1.63.2.tar.gz: [0B 0%] 1496KB/s ETA: unknown
1.63.2.tar.gz: [0B 0%] 1454KB/s ETA: unknown
1.63.2.tar.gz: [0B 0%] 1407KB/s ETA: unknown
1.63.2.tar.gz: [0B 0%] 1358KB/s ETA: unknown
1.63.2.tar.gz: [0B 0%] 1281KB/s ETA: unknown
1.63.2.tar.gz: 15MB [avg rate: 1334KB/s]
=> vscode-1.63.2_1: verifying checksum for distfile '1.63.2.tar.gz'... OK.
=> vscode-1.63.2_1: running do-extract hook: 00-distfiles ...
=> vscode-1.63.2_1: extracting distfile(s), please wait...
=> vscode-1.63.2_1: running do-patch hook: 00-patches ...
=> vscode-1.63.2_1: patching: disable-crash-reporter.patch.
=> vscode-1.63.2_1: patching: dont-download-ffmpeg.patch.
=> vscode-1.63.2_1: patching: fix_dir.patch.
=> vscode-1.63.2_1: patching: gulp.patch.
=> vscode-1.63.2_1: patching: product.patch.
=> vscode-1.63.2_1: patching: remove_git_command.patch.
=> vscode-1.63.2_1: patching: ripgrep.patch.
=> vscode-1.63.2_1: running pre-configure hook: 00-gnu-configure-asneeded ...
=> vscode-1.63.2_1: running pre-configure hook: 01-override-config ...
=> vscode-1.63.2_1: running pre-configure hook: 02-script-wrapper ...
=> vscode-1.63.2_1: running do_configure ...
=> vscode-1.63.2_1: running pre-build hook: 02-script-wrapper ...
=> vscode-1.63.2_1: running do_build ...
gyp info it worked if it ends with ok
gyp info using node-gyp@8.3.0
gyp info using node@16.13.2 | linux | x64
undefined
gyp info ok 
yarn install v1.22.10
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
info vscode-windows-ca-certs@0.3.0: The platform "linux" is incompatible with this module.
info "vscode-windows-ca-certs@0.3.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.3.1: The platform "linux" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info vscode-windows-registry@1.0.4: The platform "linux" is incompatible with this module.
info "vscode-windows-registry@1.0.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-mutex@0.4.1: The platform "linux" is incompatible with this module.
info "windows-mutex@0.4.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-process-tree@0.3.2: The platform "linux" is incompatible with this module.
info "windows-process-tree@0.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > css-loader@3.2.0" has incorrect peer dependency "webpack@^4.0.0".
warning " > eslint-plugin-header@3.1.1" has incorrect peer dependency "eslint@>=7.7.0".
warning " > file-loader@4.2.0" has incorrect peer dependency "webpack@^4.0.0".
warning " > gulp-postcss@9.0.0" has unmet peer dependency "postcss@^8.0.0".
warning " > gulp-tsb@4.0.6" has incorrect peer dependency "typescript@^3.0.0".
warning " > sinon-test@3.1.0" has incorrect peer dependency "sinon@2.x - 10.x".
warning " > style-loader@1.0.0" has incorrect peer dependency "webpack@^4.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
$ node build/npm/postinstall.js
Installing dependencies in build...
$ yarn 
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @typescript-eslint/experimental-utils@2.13.0" has unmet peer dependency "eslint@*".
warning " > @typescript-eslint/parser@3.10.1" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0 || ^7.0.0".
warning "@typescript-eslint/parser > @typescript-eslint/experimental-utils@3.10.1" has unmet peer dependency "eslint@*".
[4/4] Building fresh packages...
Done in 36.25s.
Installing dependencies in /builddir/vscode-1.63.2/build/lib/watch...
$ yarn 
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.1: The platform "linux" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.36s.
Installing dependencies in extensions...
$ yarn 
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ node ./postinstall
Removed /builddir/vscode-1.63.2/extensions/node_modules/typescript/AUTHORS.md
Removed /builddir/vscode-1.63.2/extensions/node_modules/typescript/CODE_OF_CONDUCT.md
Removed /builddir/vscode-1.63.2/extensions/node_modules/typescript/CopyrightNotice.txt
Removed /builddir/vscode-1.63.2/extensions/node_modules/typescript/LICENSE.txt
Removed /builddir/vscode-1.63.2/extensions/node_modules/typescript/README.md
Removed /builddir/vscode-1.63.2/extensions/node_modules/typescript/SECURITY.md
Removed /builddir/vscode-1.63.2/extensions/node_modules/typescript/ThirdPartyNoticeText.txt
Removed /builddir/vscode-1.63.2/extensions/node_modules/typescript/bin
Removed /builddir/vscode-1.63.2/extensions/node_modules/typescript/loc
removed '/builddir/vscode-1.63.2/extensions/node_modules/typescript/lib/tsc.js'
removed '/builddir/vscode-1.63.2/extensions/node_modules/typescript/lib/tsserverlibrary.d.ts'
removed '/builddir/vscode-1.63.2/extensions/node_modules/typescript/lib/tsserverlibrary.js'
removed '/builddir/vscode-1.63.2/extensions/node_modules/typescript/lib/typescriptServices.d.ts'
removed '/builddir/vscode-1.63.2/extensions/node_modules/typescript/lib/typescriptServices.js'
Done in 13.57s.
Installing dependencies in extensions/configuration-editing...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.81s.
Installing dependencies in extensions/css-language-features...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.50s.
Installing dependencies in extensions/css-language-features/server...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.03s.
Installing dependencies in extensions/debug-auto-launch...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.39s.
Installing dependencies in extensions/debug-server-ready...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.24s.
Installing dependencies in extensions/emmet...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 3.43s.
Installing dependencies in extensions/extension-editing...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.65s.
Installing dependencies in extensions/git...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.48s.
Installing dependencies in extensions/git-base...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.13s.
Installing dependencies in extensions/github...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 4.18s.
Installing dependencies in extensions/github-authentication...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.69s.
Installing dependencies in extensions/grunt...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.20s.
Installing dependencies in extensions/gulp...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.27s.
Installing dependencies in extensions/html-language-features...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.54s.
Installing dependencies in extensions/html-language-features/server...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 2.60s.
Installing dependencies in extensions/image-preview...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.22s.
Installing dependencies in extensions/ipynb...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 3.68s.
Installing dependencies in extensions/jake...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.22s.
Installing dependencies in extensions/json-language-features...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.60s.
Installing dependencies in extensions/json-language-features/server...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.61s.
Installing dependencies in extensions/markdown-language-features...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 3.06s.
Installing dependencies in extensions/markdown-math...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 4.37s.
Installing dependencies in extensions/merge-conflict...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.22s.
Installing dependencies in extensions/microsoft-authentication...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 3.14s.
Installing dependencies in extensions/npm...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.86s.
Installing dependencies in extensions/php-language-features...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.35s.
Installing dependencies in extensions/search-result...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.14s.
Installing dependencies in extensions/simple-browser...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.45s.
Installing dependencies in extensions/typescript-language-features...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.63s.
Installing dependencies in extensions/vscode-api-tests...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.25s.
Installing dependencies in extensions/vscode-colorize-tests...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.40s.
Installing dependencies in extensions/vscode-custom-editor-tests...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.42s.
Installing dependencies in extensions/vscode-notebook-tests...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.37s.
Installing dependencies in extensions/vscode-test-resolver...
$ yarn --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.36s.
Installing dependencies in remote...
$ yarn 
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info vscode-windows-ca-certs@0.3.0: The platform "linux" is incompatible with this module.
info "vscode-windows-ca-certs@0.3.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info vscode-windows-registry@1.0.4: The platform "linux" is incompatible with this module.
info "vscode-windows-registry@1.0.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-process-tree@0.3.2: The platform "linux" is incompatible with this module.
info "windows-process-tree@0.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 62.40s.
Installing dependencies in remote/web...
$ yarn 
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.78s.
Installing dependencies in test/automation...
$ yarn 
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 11.72s.
Installing dependencies in test/integration/browser...
$ yarn 
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 8.00s.
Installing dependencies in test/monaco...
$ yarn 
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > warnings-to-errors-webpack-plugin@2.3.0" has unmet peer dependency "webpack@^2.2.0-rc || ^3 || ^4 || ^5".
[4/4] Building fresh packages...
Done in 1.80s.
Installing dependencies in test/smoke...
$ yarn 
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 4.89s.
Done in 601.59s.
yarn run v1.22.10
$ node --max_old_space_size=8192 ./node_modules/gulp/bin/gulp.js vscode-linux-x64-min
[14:35:23] Using gulpfile /builddir/vscode-1.63.2/gulpfile.js
[14:35:23] Starting 'vscode-linux-x64-min'...
[14:35:23] Starting clean-out-build ...
[14:35:23] Finished clean-out-build after 3 ms
[14:35:23] Starting build-web-node-paths ...
No entry point for jschardet assuming dist/jschardet.min.js
[14:35:23] Finished build-web-node-paths after 76 ms
[14:35:23] Starting compile-build ...
[14:35:23] 'vscode-linux-x64-min' errored after 88 ms
[14:35:23] Error: compilation requires 4GB of RAM
    at /builddir/vscode-1.63.2/build/lib/compilation.js:77:19
    at /builddir/vscode-1.63.2/build/lib/task.js:45:28
    at new Promise (<anonymous>)
    at _doExecute (/builddir/vscode-1.63.2/build/lib/task.js:34:12)
    at _execute (/builddir/vscode-1.63.2/build/lib/task.js:25:11)
    at result (/builddir/vscode-1.63.2/build/lib/task.js:64:19)
    at async _execute (/builddir/vscode-1.63.2/build/lib/task.js:25:5)
    at async result (/builddir/vscode-1.63.2/build/lib/task.js:64:13)
    at async _execute (/builddir/vscode-1.63.2/build/lib/task.js:25:5)
    at async result (/builddir/vscode-1.63.2/build/lib/task.js:64:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
=> ERROR: vscode-1.63.2_1: do_build: 'yarn run gulp vscode-linux-x64-min' exited with 1
=> ERROR:   in do_build() at srcpkgs/vscode/template:51
```
### Steps to reproduce the behavior

Run `./xbps-src pkg vscode` in the cloned void-package folder

**Comment by Johnnynator** [comment]
> [14:35:23] Error: compilation requires 4GB of RAM

I assume you are trying to build in an environment that does not satisfy that requirement?
