### ISSUE TITLE
pandas is broken with ImportError: undefined symbol: xstrtod

### ISSUE THREAD

**Issue by ElDifinitivo** [void-linux/void-packages#35258]
### System

* xuname:  `Void 5.15.16_1 x86_64 AuthenticAMD uptodate rrmFFFFFFFFFFFFF`

* package:  `python3-pandas-1.4.0_1`

### Expected behavior

To be able to use the library.

### Actual behavior

```python3
>>> import pandas as pd
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import pandas as pd
  File "/usr/lib/python3.10/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/usr/lib/python3.10/site-packages/pandas/compat/__init__.py", line 14, in <module>
    from pandas.compat.numpy import (
  File "/usr/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/usr/lib/python3.10/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/usr/lib/python3.10/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa:F401
  File "/usr/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/usr/lib/python3.10/site-packages/pandas/_libs/tslibs/__init__.py", line 30, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
ImportError: /usr/lib/python3.10/site-packages/pandas/_libs/tslibs/parsing.so: undefined symbol: xstrtod
```

### Steps to reproduce the behavior

Any python software, either in the interpreter or any program/script, will fail with that exception output.

**Comment by ahesford** [comment]
This seems to be some ephemeral build problem. I revbumped the package to trigger a rebuild and, after you update, everything should be working properly.
