### ISSUE TITLE
libinput-1.19.3_1: build error: importlib.metadata.PackageNotFoundError: meson

### ISSUE THREAD

**Issue by pudiva** [void-linux/void-packages#35325]
### System

* xuname: Void 5.15.16_1 x86_64 GenuineIntel uptodate rrrrmdFFFFFF
* package: libinput-1.19.3_1

### Expected behavior

pkg built

### Actual behavior

pkg build crash:

`./xbps-src pkg libinput`

```
=> xbps-src: updating repositories for host (x86_64)...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/nonfree/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/debug/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/multilib/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/multilib/nonfree/x86_64-repodata' ...
=> xbps-src: updating software in / masterdir...
=> xbps-src: cleaning up / masterdir...
=> libinput-1.19.3_1: removing autodeps, please wait...
=> libinput-1.19.3_1: building [meson] for x86_64...
   [host] pkg-config-0.29.2_3: found (https://alpha.de.repo.voidlinux.org/current)
   [host] wayland-devel-1.19.0_1: found (https://alpha.de.repo.voidlinux.org/current)
   [host] meson-0.60.3_1: found (https://alpha.de.repo.voidlinux.org/current)
   [target] libevdev-devel-1.11.0_1: found (https://alpha.de.repo.voidlinux.org/current)
   [target] libwacom-devel-1.12_1: found (https://alpha.de.repo.voidlinux.org/current)
   [target] mtdev-devel-1.1.6_1: found (https://alpha.de.repo.voidlinux.org/current)
   [target] eudev-libudev-devel-3.2.10_1: found (https://alpha.de.repo.voidlinux.org/current)
   [target] gtk+3-devel-3.24.31_1: found (https://alpha.de.repo.voidlinux.org/current)
   [runtime] libevdev-devel-1.11.0_1: found (https://alpha.de.repo.voidlinux.org/current)
   [runtime] libwacom-devel-1.12_1: found (https://alpha.de.repo.voidlinux.org/current)
   [runtime] mtdev-devel-1.1.6_1: found (https://alpha.de.repo.voidlinux.org/current)
   [runtime] eudev-libudev-devel-3.2.10_1: found (https://alpha.de.repo.voidlinux.org/current)
   [runtime] gtk+3-devel-3.24.31_1: found (https://alpha.de.repo.voidlinux.org/current)
   [runtime] libinput-1.19.3_1: found (https://alpha.de.repo.voidlinux.org/current)
=> libinput-1.19.3_1: installing host dependencies: pkg-config-0.29.2_3 wayland-devel-1.19.0_1 meson-0.60.3_1 ...
=> libinput-1.19.3_1: installing target dependencies: libevdev-devel-1.11.0_1 libwacom-devel-1.12_1 mtdev-devel-1.1.6_1 eudev-libudev-devel-3.2.10_1 gtk+3-devel-3.24.31_1 ...
=> libinput-1.19.3_1: running pre-configure hook: 00-gnu-configure-asneeded ...
=> libinput-1.19.3_1: running pre-configure hook: 01-override-config ...
=> libinput-1.19.3_1: running pre-configure hook: 02-script-wrapper ...
=> libinput-1.19.3_1: running do_configure ...
Traceback (most recent call last):
  File "/usr/bin/meson", line 33, in <module>
    sys.exit(load_entry_point('meson==0.60.3', 'console_scripts', 'meson')())
  File "/usr/bin/meson", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: meson
=> ERROR: libinput-1.19.3_1: do_configure: 'PYTHONUNBUFFERED=1 ${meson_cmd} --prefix=/usr --libdir=/usr/lib${XBPS_TARGET_WORDSIZE} --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/bin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --buildtype=plain --auto-features=auto --wrap-mode=nodownload -Db_lto=true -Db_ndebug=true -Db_staticpic=true ${configure_args} . ${meson_builddir}' exited with 1
=> ERROR:   in do_configure() at common/build-style/meson.sh:106
```

### Steps to reproduce the behavior

Run `./xbps-src pkg libinput`

**Comment by q66** [comment]
i see python3.9, that means either your masterdir or your local package set is broken

**Comment by pudiva** [comment]
@q66 I just deleted my masterdir and did a binary-bootstrap.

**Comment by q66** [comment]
there hasn't been python 3.9 in void repos for months now

**Comment by pudiva** [comment]
so you mean I should uninstall this pkg from my system?

**Comment by pudiva** [comment]
how can I clean this up?

**Comment by q66** [comment]
your host system doesn't really matter here (it doesn't even have to be void)

as far as i can tell though, there is no problem on void side: https://gist.github.com/q66/93fd26ca3b56f1772c391e12d3a11bd9

**Comment by pudiva** [comment]
well I'm running void and this is broken under my system... I can see that I have python 3.10 installed, but there is a bunch of stuff referencing python 3.9 which is weird...

**Comment by q66** [comment]
if you did a clean binary-bootstrap and it's still broken, that means your local repository likely contains the bad packages

**Comment by pudiva** [comment]
I just did a pull from void-packages and my tree is clean

**Comment by q66** [comment]
your tree can be clean and your hostdir can still contain bad packages

**Comment by pudiva** [comment]
ahhhhhh I'll try deleting it. thanks!

**Comment by q66** [comment]
xbps-src does not pick them up for upgrade, because they're installed indirectly through other packages, and therefore xbps-src has no way of seeing that they are out of date; xbps will pick up your local hostdir/binpkgs over remote repositories

**Comment by pudiva** [comment]
Yes, it works! Thanks @q66 :sparkles:
