### ISSUE TITLE
`backblaze-b2` package is broken and outdated

### ISSUE THREAD

**Issue by kartikynwa** [void-linux/void-packages#37484]
### System

* xuname:  
  `Void 5.15.45_1 x86_64 AuthenticAMD uptodate rrmFFFF`
* package:  
  `backblaze-b2-2.1.0_2`

### Expected behavior

Should be able to run

### Actual behavior

Raises a module not found error:

```
 ❯ backblaze-b2
Traceback (most recent call last):
  File "/bin/backblaze-b2", line 33, in <module>
    sys.exit(load_entry_point('b2==2.1.0', 'console_scripts', 'b2')())
  File "/bin/backblaze-b2", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/b2/console_tool.py", line 25, in <module>
    from class_registry import ClassRegistry
ModuleNotFoundError: No module named 'class_registry'
```

### Steps to reproduce the behavior

1. Install the package: `xbps-install -S backblaze-b2`
2. Run the executable: `backblaze-b2`

I would update the package but I don't want to maintain it. The package can be removed if the maintainers see it fit.

**Comment by classabbyamp** [comment]
> I would update the package but I don't want to maintain it
you don't have to be maintainer to update it, and backblaze already has a maintainer currently

**Comment by kartikynwa** [comment]
The missing dependency is this package: https://github.com/todofixthis/class-registry

**Comment by sgn** [comment]
`backblaze-b2` is outdated, `b2sdk` has been updated and removes some API that is needed by `backblaze-b2`

**Comment by kartikynwa** [comment]
@the-maldridge tagging at your request

**Comment by kartikynwa** [comment]
@ahesford tagging at your request
