### ISSUE TITLE
offlineimap: python 3.11 sqlite multithreading error

### ISSUE THREAD

**Issue by pascal-huber** [void-linux/void-packages#40425]
### Is this a new report?

Yes

### System Info

Void 5.19.17_1 x86_64 AuthenticAMD uptodate rrmFFFFFFFFF

### Package(s) Affected

offlineimap-8.0.0_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

issue: https://github.com/OfflineIMAP/offlineimap3/issues/136
PR: https://github.com/OfflineIMAP/offlineimap3/pull/137

### Expected behaviour

`offlineimap` syncs mails.

### Actual behaviour

offlineimap throws errors of the form:

```
  Your sqlite is not multithreading safe.
Folder someFolder [acc: MyAccount]:
 ERROR: ERROR in syncfolder for MyAccount folder someFolder: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/offlineimap/accounts.py", line 610, in syncfolder
    statusfolder.openfiles()
  File "/usr/lib/python3.11/site-packages/offlineimap/folder/LocalStatusSQLite.py", line 107, in openfiles
    assert sqlite.threadsafety == 1, 'Your sqlite is not multithreading safe.'
AssertionError: Your sqlite is not multithreading safe.
```

### Steps to reproduce

1. Add an `.offlineimaprc` config containing a mail account
2. run `offlineimap`

**Comment by pascal-huber** [comment]
It works when I apply the changes of the mentioned PR.
