### ISSUE TITLE
Syncplay crashes when attempting to join server with python 3.11

### ISSUE THREAD

**Issue by mtroberts** [void-linux/void-packages#40475]
### Is this a new report?

Yes

### System Info

Void 5.19.17_1 x86_64 AuthenticAMD uptodate FFFFF

### Package(s) Affected

syncplay-1.6.9_3

### Expected behaviour

When clicking on Store Configuration and Run Syncplay, the app should launch MPV and connect to the server.

### Actual behaviour

App crashes with following error:

```
Traceback (most recent call last):
  File "/usr/lib/syncplay/syncplay/client.py", line 837, in start
    waitForConnection = self._reconnectingService.whenConnected(failAfterFailures=1)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/twisted/application/internet.py", line 1168, in whenConnected
    return self._machine.whenConnected(failAfterFailures)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/automat/_methodical.py", line 232, in __get__
    @preserveName(self.method)
     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 43, in decorator
    return copyfunction(decorated,
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 35, in copyfunction
    return function(copycode(template.__code__, codechanges), *values)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 23, in copycode
    return code(*values)
           ^^^^^^^^^^^^^
TypeError: code() argument 13 must be str, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/syncplay", line 19, in <module>
    ep_client.main()
  File "/usr/lib/syncplay/syncplay/ep_client.py", line 8, in main
    SyncplayClientManager().run()
  File "/usr/lib/syncplay/syncplay/clientManager.py", line 16, in run
    syncplayClient.start(config['host'], config['port'])
  File "/usr/lib/syncplay/syncplay/client.py", line 839, in start
    waitForConnection = self._reconnectingService.whenConnected()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/twisted/application/internet.py", line 1168, in whenConnected
    return self._machine.whenConnected(failAfterFailures)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/automat/_methodical.py", line 232, in __get__
    @preserveName(self.method)
     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 43, in decorator
    return copyfunction(decorated,
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 35, in copyfunction
    return function(copycode(template.__code__, codechanges), *values)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 23, in copycode
    return code(*values)
           ^^^^^^^^^^^^^
TypeError: code() argument 13 must be str, not int
```

### Steps to reproduce

1. Launch Syncplay and configure server information.
2. Click on Store Configuration and Run Syncplay.
3. Crash

**Comment by kruceter** [comment]
I could reproduce this traceback.

The fault lays with the outdated python3-automat (symlink to python-automat).

Updating it to 22.10.0 solved this issue for me.

@mtroberts, you can use the patch below to build that package locally until it is updated in the repository:

```diff
diff --git a/srcpkgs/python-automat/template b/srcpkgs/python-automat/template
index 8b3f99f196..42efed39d3 100644
--- a/srcpkgs/python-automat/template
+++ b/srcpkgs/python-automat/template
@@ -1,7 +1,7 @@
 # Template file for 'python-automat'
 pkgname=python-automat
-version=20.2.0
-revision=5
+version=22.10.0
+revision=1
 build_style=python-module
 hostmakedepends="python-setuptools python3-setuptools"
 depends="python-setuptools python-attrs python-six"
@@ -11,7 +11,7 @@ maintainer="Alessio Sergi <al3hex@gmail.com>"
 license="MIT"
 homepage="https://github.com/glyph/Automat"
 distfiles="${PYPI_SITE}/A/Automat/Automat-${version}.tar.gz"
-checksum=7979803c74610e11ef0c0d68a2942b152df52da55336e0c9d58daf1831cbdf33
+checksum=e56beb84edad19dcc11d30e8d9b895f75deeb5ef5e96b84a467066b3b84bb04e
 alternatives="automat:automat-visualize:/usr/bin/automat-visualize2"
 
 pre_build() {
```

**Comment by TinfoilSubmarine** [comment]
FYI, https://github.com/void-linux/void-packages/pull/40446 will update python3-automat to 22.10.0
