### ISSUE TITLE
wormhole backage broken

### ISSUE THREAD

**Issue by Risto-Stevcev** [void-linux/void-packages#40487]
### Is this a new report?

Yes

### System Info

Void 5.19.17_1 x86_64 GenuineIntel notuptodate rrmFFFFF

### Package(s) Affected

magic-wormhole-0.12.0_5

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

magic-wormhole/magic-wormhole/issues/463

### Expected behaviour

The send/receive commands work

### Actual behaviour

This was caused by some recent update, it worked previously. The `wormhole send`/`wormhole receive` commands give the same error:
```
[~]λ wormhole send                                                                                                                      
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/wormhole/cli/cli.py", line 255, in <lambda>
    return react(_dispatch_command, (cfg, lambda: f(cfg)))
  File "/usr/lib/python3.11/site-packages/wormhole/cli/cmd_send.py", line 38, in send
    return Sender(args, reactor).go()
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1905, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1815, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status)
--- <exception caught here> ---
  File "/usr/lib/python3.11/site-packages/wormhole/cli/cli.py", line 122, in _dispatch_command
    yield maybeDeferred(command)
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/usr/lib/python3.11/site-packages/wormhole/cli/cmd_send.py", line 66, in go
    w = create(
  File "/usr/lib/python3.11/site-packages/wormhole/wormhole.py", line 290, in create
    b = Boss(w, side, relay_url, appid, wormhole_versions, client_version,
  File "<attrs generated init wormhole._boss.Boss>", line 23, in __init__
    self.__attrs_post_init__()
  File "/usr/lib/python3.11/site-packages/wormhole/_boss.py", line 52, in __attrs_post_init__
    self._build_workers()
  File "/usr/lib/python3.11/site-packages/wormhole/_boss.py", line 62, in _build_workers
    self._RC = RendezvousConnector(self._url, self._appid, self._side,
  File "<attrs generated init wormhole._rendezvous.RendezvousConnector>", line 18, in __init__
    self.__attrs_post_init__()
  File "/usr/lib/python3.11/site-packages/wormhole/_rendezvous.py", line 87, in __attrs_post_init__
    d = self._connector.whenConnected(failAfterFailures=faf)
  File "/usr/lib/python3.11/site-packages/twisted/application/internet.py", line 1168, in whenConnected
    return self._machine.whenConnected(failAfterFailures)
  File "/usr/lib/python3.11/site-packages/automat/_methodical.py", line 232, in __get__
    @preserveName(self.method)
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 43, in decorator
    return copyfunction(decorated,
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 35, in copyfunction
    return function(copycode(template.__code__, codechanges), *values)
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 23, in copycode
    return code(*values)
builtins.TypeError: code() argument 13 must be str, not int
ERROR: code() argument 13 must be str, not int
```

### Steps to reproduce

Run `wormhole send` or `wormhole receive`

**Comment by TinfoilSubmarine** [comment]
Worked with the updates in https://github.com/void-linux/void-packages/pull/40446
