### ISSUE TITLE
vidcutter: libmpv version is incorrect. Required 1.109 got 2.0.

### ISSUE THREAD

**Issue by Eloitor** [void-linux/void-packages#41465]
### Is this a new report?

Yes

### System Info

Void 6.0.12_1 x86_64-musl GenuineIntel uptodate rFFFFFFFFFFFFFFFFFFF

### Package(s) Affected

vidcutter-6.0.5.1_1

### Expected behaviour

vidcutter works

### Actual behaviour

```
$ vidcutter video.mp4
Traceback (most recent call last):
  File "/usr/sbin/vidcutter", line 33, in <module>
    sys.exit(load_entry_point('vidcutter==6.0.5.1', 'gui_scripts', 'vidcutter')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/sbin/vidcutter", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/vidcutter/__main__.py", line 41, in <module>
    from vidcutter.videocutter import VideoCutter
  File "/usr/lib/python3.11/site-packages/vidcutter/videocutter.py", line 57, in <module>
    from vidcutter.libs.mpvwidget import mpvWidget
  File "/usr/lib/python3.11/site-packages/vidcutter/libs/mpvwidget.py", line 44, in <module>
    import vidcutter.libs.mpv as mpv
  File "vidcutter/libs/pympv/mpv.pyx", line 46, in init vidcutter.libs.mpv
ImportError: libmpv version is incorrect. Required 1.109 got 2.0.
```

### Steps to reproduce

1. install vidcutter
2. try to run it

**Comment by oreo639** [comment]
There is a patch upstream:
https://github.com/ozmartian/vidcutter/commit/27c1ceb1764a86b284fb9115b9cf740891be1329

**Comment by sgn** [comment]
Well, we need to remove a patch, not add a patch :-p
