### ISSUE TITLE
dropbox - missing run dependency libglapi

### ISSUE THREAD

**Issue by chax** [void-linux/void-packages#43402]
### Is this a new report?

Yes

### System Info

Void 6.1.21_1 x86_64 GenuineIntel uptodate rrFF

### Package(s) Affected

dropbox-2022.12.05_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

no

### Expected behaviour

dropbox should be able to start after installation.

### Actual behaviour

dropbox package is missing rundep libglapi, i had to manually istall it myself.

```
Traceback (most recent call last):
  File "dropbox/client/main.pyc", line 7610, in main_startup
  File "dropbox/client/main.pyc", line 2843, in initialize
  File "dropbox/client/ui/common/uikit.pyc", line 878, in create_ui_kit
  File "<frozen zipimport>", line 259, in load_module
  File "dropbox/client/ui/qt/uikit.pyc", line 53, in <module>
  File "<_bootstrap_overrides>", line 147, in load_module
ImportError: libglapi.so.0: cannot open shared object file: No such file or directory
```

### Steps to reproduce

- install dropbox
- run dropbox

**Comment by sgn** [comment]
`dropbox` is only a wrapper to download and launch *proprietary* dropbox from dropbox.com
They bundled all of their dependencies there. Any missing dependencies, please report upstream.

Tentatively close as `wont-fix`
