### ISSUE TITLE
python3-lsp-server dependency (yapf) breaks pip

### ISSUE THREAD

**Issue by ElDifinitivo** [void-linux/void-packages#43726]
### Is this a new report?

Yes

### System Info

Void 6.1.25_1 x86_64 AuthenticAMD notuptodate rrmFFFFFFFFFFFFFFFFF

### Package(s) Affected

python3-lsp-server-1.7.2_2, python3-yapf-0.33.0_1, python3-pip-23.1.2_1

### Expected behaviour

```bash
> pip list
...installed python packages
```

### Actual behaviour

```bash
> pip list
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_internal/commands/list.py", line 169, in run
    packages: "_ProcessedDists" = [
                                  ^
  File "/usr/lib/python3.11/site-packages/pip/_internal/commands/list.py", line 169, in <listcomp>
    packages: "_ProcessedDists" = [
                                  ^
  File "/usr/lib/python3.11/site-packages/pip/_internal/metadata/base.py", line 664, in <genexpr>
    return (d for d in it if d.canonical_name not in skip)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions
    for dist in self._iter_distributions():
  File "/usr/lib/python3.11/site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions
    for dist in finder.find_eggs(location):
  File "/usr/lib/python3.11/site-packages/pip/_internal/metadata/importlib/_envs.py", line 144, in find_eggs
    yield from self._find_eggs_in_dir(location)
  File "/usr/lib/python3.11/site-packages/pip/_internal/metadata/importlib/_envs.py", line 111, in _find_eggs_in_dir
    from pip._vendor.pkg_resources import find_distributions
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3326, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3301, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3339, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 620, in _build_master
    ws = cls()
         ^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 613, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 669, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2133, in find_on_path
    for dist in factory(fullpath):
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2198, in distributions_from_metadata
    yield Distribution.from_location(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2672, in from_location
    )._reload_version()
      ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3080, in _reload_version
    md_version = self._get_version()
                 ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2857, in _get_version
    version = _version_from_file(lines)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2623, in _version_from_file
    line = next(iter(version_lines), '')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2852, in _get_metadata
    for line in self.get_metadata_lines(name):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1527, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1517, in get_metadata
    value = self._get(path)
            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1726, in _get
    with open(path, 'rb') as stream:
         ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.11/site-packages/yapf-0.33.0-py3.11.egg-info/PKG-INFO'
Traceback (most recent call last):
  File "/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==23.1.2', 'console_scripts', 'pip3')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_internal/cli/main.py", line 79, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 225, in _main
    self.handle_pip_version_check(options)
  File "/usr/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 180, in handle_pip_version_check
    session = self._build_session(
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
    session = PipSession(
              ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_internal/network/session.py", line 342, in __init__
    self.headers["User-Agent"] = user_agent()
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_internal/network/session.py", line 175, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_internal/metadata/importlib/_envs.py", line 188, in get_distribution
    return next(matches, None)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_internal/metadata/importlib/_envs.py", line 183, in <genexpr>
    matches = (
              ^
  File "/usr/lib/python3.11/site-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions
    for dist in self._iter_distributions():
  File "/usr/lib/python3.11/site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions
    for dist in finder.find_eggs(location):
  File "/usr/lib/python3.11/site-packages/pip/_internal/metadata/importlib/_envs.py", line 144, in find_eggs
    yield from self._find_eggs_in_dir(location)
  File "/usr/lib/python3.11/site-packages/pip/_internal/metadata/importlib/_envs.py", line 111, in _find_eggs_in_dir
    from pip._vendor.pkg_resources import find_distributions
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3326, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3301, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3339, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 620, in _build_master
    ws = cls()
         ^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 613, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 669, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2133, in find_on_path
    for dist in factory(fullpath):
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2198, in distributions_from_metadata
    yield Distribution.from_location(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2672, in from_location
    )._reload_version()
      ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3080, in _reload_version
    md_version = self._get_version()
                 ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2857, in _get_version
    version = _version_from_file(lines)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2623, in _version_from_file
    line = next(iter(version_lines), '')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2852, in _get_metadata
    for line in self.get_metadata_lines(name):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1527, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1517, in get_metadata
    value = self._get(path)
            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1726, in _get
    with open(path, 'rb') as stream:
         ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.11/site-packages/yapf-0.33.0-py3.11.egg-info/PKG-INFO'
```

### Steps to reproduce

1. Install `python3-lsp-server-1.7.2_2`, of which `python3-yapf-0.33.0_1` is a dependency of.
2. Attempt any `pip` command outside of a virtualenv and with the system python other than `help` or `--help`.

**Comment by classabbyamp** [comment]
while this is a bug, you really shouldn't be using pip outside of a venv, it can break python modules from xbps
