### ISSUE TITLE
Cross built rustc missing symbol crc32

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#4379]
### System

* xuname:  
  *Void 4.18.16_2 x86_64 AuthenticAMD uptodate rrdFFFFFFF*
* package:  
  *rust-1.30.0_1*

### Expected behavior
rust should run `rustc -vV`

### Actual behavior
Trying to build librsvg for i686-musl with cross built rust:
```
error: process didn't exit successfully: `rustc -vV` (exit code: 1)
--- stdout
rustc 1.30.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: i686-unknown-linux-musl
release: 1.30.0

--- stderr
error: couldn't load codegen backend "/usr/lib/rustlib/i686-unknown-linux-musl/codegen-backends/librustc_codegen_llvm-llvm.so": "Error relocating /usr/lib/rustlib/i686-unknown-linux-musl/codegen-backends/librustc_codegen_llvm-llvm.so: crc32: symbol not found"
```

### Steps to reproduce the behavior
Install a cross compiled rust (e.g. i686-musl) and try to run rustc.

**Comment by Cogitri** [comment]
Does zlib have the crc32 symbol on i686? If so, I guess `librustc_codegen_llvm-llvm.so` isn't linked against zlib for some reason.

**Comment by pullmoll** [comment]
I can see a `crc32` string looking (with hexdump) into the `i686-musl` version `libz.so.1.2.11`, yes. The libs are stripped and thus no symbols are contained when I run `nm` or `objdump -x` on the library. It looks the same for the `i686` `libz.so.1.2.11`.

On a related note I can't cross compile rust for `x86_64-musl` either. Currently it fails to build in for `x86_64-musl` natively because the previous rust is linked against the previous libressl. In case that error message is of any use, here's the relevant output:
```
error: failed to run custom build command for `lzma-sys v0.1.10`
process didn't exit successfully: `/builddir/rustc-1.30.0-src/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/release/build/lzma-sys-347fef56ab07638c/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=LZMA_API_STATIC
cargo:rustc-link-search=/builddir/rustc-1.30.0-src/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/build/lzma-sys-fd2e2a9eccaea6de/out/lib
cargo:root=/builddir/rustc-1.30.0-src/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/build/lzma-sys-fd2e2a9eccaea6de/out
cargo:include=/builddir/rustc-1.30.0-src/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/build/lzma-sys-fd2e2a9eccaea6de/out/include
cargo:rerun-if-changed=xz-5.2.3/configure
cargo:rustc-link-lib=static=lzma
OPT_LEVEL = Some("2")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = Some("cc")
CFLAGS_x86_64-unknown-linux-gnu = Some("-ffunction-sections -fdata-sections -fPIC -pipe -m64")
DEBUG = Some("false")
running: "sh" "/builddir/rustc-1.30.0-src/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/build/lzma-sys-fd2e2a9eccaea6de/out/src/configure" "--prefix=/builddir/rustc-1.30.0-src/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/build/lzma-sys-fd2e2a9eccaea6de/out" "--disable-doc" "--disable-lzma-links" "--disable-lzmainfo" "--disable-lzmadec" "--disable-xz" "--disable-xzdec" "--disable-scripts" "--disable-shared" "--disable-nls" "--disable-rpath" "--enable-threads=yes"

XZ Utils 5.2.3

System type:
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu

Configure options:
checking if debugging code should be compiled... no
checking which encoders to build... lzma1 lzma2 delta x86 powerpc ia64 arm armthumb sparc
checking which decoders to build... lzma1 lzma2 delta x86 powerpc ia64 arm armthumb sparc
checking which match finders to build... hc3 hc4 bt2 bt3 bt4
checking which integrity checks to build... crc32 crc64 sha256
checking if external SHA-256 should be used... no
checking if assembler optimizations should be used... x86_64
checking if small size is preferred over speed... no
checking if threading support is wanted... yes, posix
checking how much RAM to assume if the real amount is unknown... 128 MiB
checking if library symbol versioning should be used... yes
checking if sandboxing should be used... no

checking for a shell that conforms to POSIX... /bin/sh

Initializing Automake:
checking for a BSD-compatible install... /builddir/.xbps-rust/wrappers/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether ln -s works... yes
checking for style of include used by make... GNU
checking for gcc... cc
checking whether the C compiler works... no

--- stderr
configure: error: in `/builddir/rustc-1.30.0-src/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/build/lzma-sys-fd2e2a9eccaea6de/out/build':
configure: error: C compiler cannot create executables
See `config.log' for more details
thread 'main' panicked at 'assertion failed: try_run(cmd)', /builddir/rustc-1.30.0-src/.cargo/registry/src/github.com-1ecc6299db9ec823/lzma-sys-0.1.10/build.rs:182:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: build_script_build::main
   7: std::rt::lang_start::{{closure}}
   8: std::panicking::try::do_call
   9: __rust_maybe_catch_panic
  10: std::rt::lang_start_internal
  11: main
  12: __libc_start_main
  13: _start

warning: build failed, waiting for other jobs to finish...
error: build failed
command did not execute successfully: "/usr/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "32" "--release" "--manifest-path" "/builddir/rustc-1.30.0-src/src/tools/rust-installer/Cargo.toml" "--features" "" "--message-format" "json"
expected success, got: exit code: 101
Traceback (most recent call last):
  File "/builddir/rustc-1.30.0-src/src/bootstrap/bootstrap.py", line 861, in <module>
    main()
  File "/builddir/rustc-1.30.0-src/src/bootstrap/bootstrap.py", line 844, in main
    bootstrap(help_triggered)
  File "/builddir/rustc-1.30.0-src/src/bootstrap/bootstrap.py", line 835, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/builddir/rustc-1.30.0-src/src/bootstrap/bootstrap.py", line 151, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /builddir/rustc-1.30.0-src/build/bootstrap/debug/bootstrap dist -v
make: *** [Makefile:72: dist] Error 1
=> ERROR: rust-1.30.0_1: do_build: 'env CFLAGS_${_build_triplet}="${CFLAGS_host}" make ${makejobs} ${make_build_args}' exited with 2
=> ERROR:   in do_build() at srcpkgs/rust/template:162
```

The error in `config.log` is this:
```
configure:5255: checking whether the C compiler works
configure:5277: cc -O2 -ffunction-sections -fdata-sections -fPIC -ffunction-sections -fdata-sections -fPIC -pipe -m64 -m64      -Wl,-z,relro -Wl,-z,now -Wl,--as-needed     -L/usr/x86_64-linux-musl/usr/lib conftest.c
 >&5
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/8.2.0/../../../../lib/Scrt1.o: in function `_start':
(.text+0x12): undefined reference to `__libc_csu_fini'
/usr/bin/ld: (.text+0x19): undefined reference to `__libc_csu_init'
collect2: error: ld returned 1 exit status
```

So it looks like this stage is trying to use the host's `cc` with the cross lib in `/usr/x86_64-linux-musl/usr/lib`.
Perhaps this is related to why when cross building for `i686-musl` the `librustc_codegen_llvm-llvm.so` fails to find the `crc32` symbol?

**Comment by jnbr** [comment]
> On a related note I can't cross compile rust for x86_64-musl either. Currently it fails to build in for x86_64-musl natively because the previous rust is linked against the previous libressl.

fixed

**Comment by pullmoll** [comment]
FWIW cross compiling `librsvg` for `i686-musl` from an `x86_64` environment works. That is with `cargo` in the hostmakedepends and `rust` in the makedepends. huh?

**Comment by jnbr** [comment]
I assume this is a problem with our `llvm-config` not reporing that it needs `zlib` and `ncurses`.
I don't understand why it works for native builds.
However, forcing these libs to be included works.
