### ISSUE TITLE
scrcpy failing to run because of SIGILL SDL2

### ISSUE THREAD

**Issue by devlocalhost** [void-linux/void-packages#44829]
### Is this a new report?

Yes

### System Info

Void 6.3.8_dev64-xanmod1 i686 GenuineIntel uptodate rrdDFF

### Package(s) Affected

scrcpy-2.1_1, SDL2-2.28.1_1

### Expected behaviour

Scrcpy will start mirroring the connected android device to the computer 

### Actual behaviour

Scrcpy does not start mirroring, instead it crashes with "SIGILL" error

### Steps to reproduce

1. Install scrcpy
2. Install SDL2
3. Connect an android device with USB debugging enabled
4. On the computer, run "scrcpy"
5. Scrcpy will crash

**Comment by devlocalhost** [comment]
Additional information (gdb): https://dpaste.com/CB2VVSPLR

**Comment by sgn** [comment]
Your CPU, GPU?

**Comment by devlocalhost** [comment]
> Your CPU, GPU?

CPU: Intel Celeron M 360
GPU: Intel Mobile 915GM/GMS/910GML Express Graphics

**Comment by devlocalhost** [comment]
No one knows...?

**Comment by biopsin** [comment]
Its hard to replicate since its workin fine for here
 ~/Downloads $ !544
```
scrcpy -d --stay-awake --turn-screen-off && adb kill-server
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
INFO: ADB device found:
INFO:     -->   (usb)  QV710PVB3F                      device  Xperia_1_II
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 94.6 MB/s (56995 bytes in 0.001s)
[server] INFO: Device: [Sony] Sony Xperia 1 II (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 23.1.3
INFO: Trilinear filtering enabled
[server] INFO: Device screen turned off
INFO: Texture: 1096x2560
```

**Comment by devlocalhost** [comment]
After the SDL2 update (2.28.2_1), now I get a different error:

```
dev64 # 12:25:45 PM
 > scrcpy
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.2.91:5555               device  Mi_A3
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 2.6 MB/s (56995 bytes in 0.021s)
[server] INFO: Device: [Xiaomi] Xiaomi Mi A3 (Android 13)
fish: Job 1, 'scrcpy' terminated by signal SIGILL (Illegal instruction)
dev64 # 12:25:50 PM
 > gdb scrcpy
GNU gdb (GDB) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "i686-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from scrcpy...
Reading symbols from /usr/lib/debug//usr/bin/scrcpy...
(gdb) r
Starting program: /usr/bin/scrcpy
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib32/libthread_db.so.1".
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
[New Thread 0xb2821b40 (LWP 1260)]
[Detaching after fork from child process 1261]
[Detaching after fork from child process 1262]
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.2.91:5555               device  Mi_A3
[Detaching after fork from child process 1263]
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 33.0 MB/s (56995 bytes in 0.002s)
[Detaching after fork from child process 1264]
[Detaching after fork from child process 1265]
[New Thread 0xb1dffb40 (LWP 1266)]
[New Thread 0xb15feb40 (LWP 1268)]
[server] INFO: Device: [Xiaomi] Xiaomi Mi A3 (Android 13)
[Detaching after fork from child process 1269]
[New Thread 0xb0dfdb40 (LWP 1270)]
[New Thread 0xb05fcb40 (LWP 1271)]

Thread 1 "scrcpy" received signal SIGILL, Illegal instruction.
0xb64c1525 in QueueCmdSetViewport (renderer=renderer@entry=0x516310) at ../src/render/SDL_render.c:359
359     ../src/render/SDL_render.c: No such file or directory.
(gdb) bt
#0  0xb64c1525 in QueueCmdSetViewport (renderer=renderer@entry=0x516310) at ../src/render/SDL_render.c:359
#1  0xb64c6223 in SDL_RenderSetViewport_REAL (renderer=0x516310, rect=0x0) at ../src/render/SDL_render.c:2455
#2  0xb64c6530 in SDL_CreateRenderer_REAL (window=0x500280, index=<optimized out>, flags=2) at ../src/render/SDL_render.c:1084
#3  0x0041c6d8 in sc_display_init (display=<optimized out>, mipmaps=true, window=<optimized out>) at ../app/src/display.c:10
#4  sc_screen_init.constprop.0 (params=params@entry=0xbffff888, screen=<optimized out>) at ../app/src/screen.c:405
#5  0x004136ad in scrcpy (options=0xbffffa5c) at ../app/src/scrcpy.c:698
#6  0x0040698d in main_scrcpy (argv=0xbffffc34, argc=1) at ../app/src/main.c:82
#7  main (argc=1, argv=0xbffffc34) at ../app/src/main.c:93
(gdb)
```
