### ISSUE TITLE
Syncplay crashes when joining a room

### ISSUE THREAD

**Issue by prez** [void-linux/void-packages#45306]
### Is this a new report?

Yes

### System Info

Void 6.3.12_1 x86_64 GenuineIntel uptodate rrrrmmnFFFFFFFFF

### Package(s) Affected

syncplay-1.7.0_1

### Expected behaviour

syncplay starts.

### Actual behaviour

```
~ $ syncplay
Traceback (most recent call last):
  File "/usr/bin/syncplay", line 19, in <module>
    ep_client.main()
  File "/usr/lib/syncplay/syncplay/ep_client.py", line 8, in main
    SyncplayClientManager().run()
  File "/usr/lib/syncplay/syncplay/clientManager.py", line 12, in run
    interface = ui.getUi(graphical=not config["noGui"], passedBar=menuBar)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/syncplay/syncplay/ui/__init__.py", line 17, in getUi
    ui = GraphicalUI(passedBar=passedBar)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/syncplay/syncplay/ui/gui.py", line 2109, in __init__
    self.setWindowFlags(self.windowFlags() & Qt.AA_DontUseNativeMenuBar)
                        ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for &: 'WindowType' and 'ApplicationAttribute'
```

### Steps to reproduce

1. open syncplay
2. enter any room/server

**Comment by sgn** [comment]
Upstream https://github.com/Syncplay/syncplay/issues/600

**Comment by sgn** [comment]
What is your video player?

**Comment by classabbyamp** [comment]
downgrade python?

**Comment by sgn** [comment]
Ah, forgot to mention, I can run `syncplay` with `mpv` normally.
