### ISSUE TITLE
eyeD3 has missing runtime dependencies

### ISSUE THREAD

**Issue by meator** [void-linux/void-packages#45579]
### Is this a new report?

Yes

### System Info

Void 6.3.13_1 x86_64 GenuineIntel uptodate rFF

### Package(s) Affected

eyeD3-0.9.6_2

### Expected behaviour

Working program without exceptions.

### Actual behaviour

`eyeD3` prints an exception upon launch. It looks like it isn't fatal, the program continues to do its work and it exits with return code 0, but having an exception raised is still undesirable.

I am not familiar with Python's packaging system so I can't submit a fix for this issue. I tried to install `python3-coverage` but the exception persists.

Here is the error message:
```
> eyeD3
eyed3.plugins:ERROR: Bad plugin ('lastfm.py', '/usr/lib/python3.11/site-packages/eyed3/plugins')
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 631, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 875, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (coverage 7.2.7 (/usr/lib/python3.11/site-packages), Requirement.parse('coverage[toml]==5.*,>=5.3.1'), {'eyeD3'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/eyed3/plugins/__init__.py", line 56, in load
    mod = __import__(mod_name, globals=globals(), locals=locals())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/eyed3/plugins/lastfm.py", line 1, in <module>
    from pylast import SIZE_EXTRA_LARGE, SIZE_LARGE, SIZE_MEDIUM, SIZE_MEGA, SIZE_SMALL
  File "/usr/lib/python3.11/site-packages/pylast/__init__.py", line 35, in <module>
    import pkg_resources
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3327, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 633, in _build_master
    return cls._build_from_requirements(__requires__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 646, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 870, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'coverage[toml]==5.*,>=5.3.1' distribution was not found and is required by eyeD3
No audio files found.
```

### Steps to reproduce

1. ```sh
   xbps-install -S eyeD3
   ```
2. ```sh
   eyeD3
   ```

**Comment by mhmdanas** [comment]
Regardless of the cause of the issue, it's weird that `python3-coverage` is needed at all, because it should only be used for tests.

Possibly related: https://github.com/nicfit/eyeD3/issues/574

**Comment by meator** [comment]
It looks like the packaged `python3-coverage` is too new for eyeD3. The only solution I see is updating eyeD3 (as in #39898).
