### ISSUE TITLE
`quodlibet` fails to start with "ModuleNotFoundError: No module named 'senf'" error

### ISSUE THREAD

**Issue by mhmdanas** [void-linux/void-packages#46603]
### Is this a new report?

Yes

### System Info

Void 6.5.6_1 x86_64 GenuineIntel notuptodate rrrmFFFFFFFFFFFFFFF

### Package(s) Affected

quodlibet-4.5.0_3

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Couldn't find anything.

### Expected behaviour

`quodlibet` start successfully.

### Actual behaviour

```
$ quodlibet
Traceback (most recent call last):
  File "/usr/bin/quodlibet", line 11, in <module>
    from quodlibet.main import main
  File "/usr/lib/python3.12/site-packages/quodlibet/__init__.py", line 21, in <module>
    from .util.i18n import _, C_, N_, ngettext, npgettext
  File "/usr/lib/python3.12/site-packages/quodlibet/util/__init__.py", line 28, in <module>
    from senf import fsnative
ModuleNotFoundError: No module named 'senf'
```

This is despite the vendored `senf` Python package being present in `quodlibet`:
```
$ xls quodlibet | grep senf
/usr/lib/python3.12/site-packages/quodlibet/packages/senf/__init__.py
/usr/lib/python3.12/site-packages/quodlibet/packages/senf/_argv.py
/usr/lib/python3.12/site-packages/quodlibet/packages/senf/_compat.py
/usr/lib/python3.12/site-packages/quodlibet/packages/senf/_environ.py
/usr/lib/python3.12/site-packages/quodlibet/packages/senf/_fsnative.py
/usr/lib/python3.12/site-packages/quodlibet/packages/senf/_print.py
/usr/lib/python3.12/site-packages/quodlibet/packages/senf/_stdlib.py
/usr/lib/python3.12/site-packages/quodlibet/packages/senf/_temp.py
/usr/lib/python3.12/site-packages/quodlibet/packages/senf/_winansi.py
/usr/lib/python3.12/site-packages/quodlibet/packages/senf/_winapi.py
```

According to a user on #voidlinux, this error only appeared after updating their system yesterday, so it could be related to the Python 3.12 bump.

### Steps to reproduce

1. Run `quodlibet`

**Comment by Johnnynator** [comment]
https://github.com/void-linux/void-packages/commit/a700eef617c07a89dbee84b1783073ff4f7b2a0b
