### ISSUE TITLE
weechat crashes on exit when both title.py and autosort.py are loaded

### ISSUE THREAD

**Issue by laemeiqu** [void-linux/void-packages#47336]
### Is this a new report?

Yes

### System Info

Void 6.5.11_1 x86_64 GenuineIntel/VM uptodate FFFF

### Package(s) Affected

weechat-4.1.1_1 , weechat-python-4.1.1_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/weechat/weechat/issues/2046

### Expected behaviour

Weechat doesn't crash on exit when both title.py and autosort.py scripts are installed.

### Actual behaviour

Weechat crashes during exit when both scripts are installed.

### Steps to reproduce

1. /script load title.py
2. /script load autosort.py
3. /exit

After bulding debug packages in voidlinux

gdb /usr/bin/weechat

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff626f76d in PyObject_GC_UnTrack () from /usr/lib/libpython3.12.so.1.0

bt full

```
#0  0x00007ffff626f76d in PyObject_GC_UnTrack () from /usr/lib/libpython3.12.so.1.0
No symbol table info available.
#1  0x00007ffff62a2099 in ?? () from /usr/lib/libpython3.12.so.1.0
No symbol table info available.
#2  0x00007ffff62251e5 in ?? () from /usr/lib/libpython3.12.so.1.0
No symbol table info available.
#3  0x00007ffff6220276 in ?? () from /usr/lib/libpython3.12.so.1.0
No symbol table info available.
#4  0x00007ffff6225bd5 in _PyModule_ClearDict () from /usr/lib/libpython3.12.so.1.0
No symbol table info available.
#5  0x00007ffff62eaaf6 in ?? () from /usr/lib/libpython3.12.so.1.0
No symbol table info available.
#6  0x00007ffff62ead6b in Py_EndInterpreter () from /usr/lib/libpython3.12.so.1.0
No symbol table info available.
#7  0x00007ffff66ea2a0 in weechat_python_unload (script=0x555555df3550)
    at /builddir/weechat-4.1.1/src/plugins/python/weechat-python.c:975
        rc = <optimized out>
        interpreter = 0x7ffff5bec910
        filename = 0x555555e69230 "/home/roald/.local/share/weechat/python/autoload/title.py"
#8  0x00007ffff66ea375 in weechat_python_unload_all ()
    at /builddir/weechat-4.1.1/src/plugins/python/weechat-python.c:1024
No locals.
#9  0x00007ffff670a12c in plugin_script_end (weechat_plugin=weechat_plugin@entry=0x555555b5cd10, 
    plugin_data=plugin_data@entry=0x7ffff671bd00 <python_data>)
    at /builddir/weechat-4.1.1/src/plugins/plugin-script.c:1789
        scripts_loaded = 1
#10 0x00007ffff66eb681 in weechat_plugin_end (plugin=0x555555b5cd10)
    at /builddir/weechat-4.1.1/src/plugins/python/weechat-python.c:1563
No locals.
#11 0x00005555555fadb6 in plugin_unload (plugin=0x555555b5cd10)
    at /builddir/weechat-4.1.1/src/plugins/plugin.c:1253
        end_func = <optimized out>
        name = 0x555555fcd320 "python"
#12 0x00005555555fae69 in plugin_unload_all () at /builddir/weechat-4.1.1/src/plugins/plugin.c:1305
        plugins_loaded = <optimized out>
#13 0x00005555555fb122 in plugin_end () at /builddir/weechat-4.1.1/src/plugins/plugin.c:1425
No locals.
#14 0x00005555555630c2 in weechat_end (gui_end_cb=0x5555555f43d0 <gui_main_end>)
    at /builddir/weechat-4.1.1/src/core/weechat.c:708
No locals.
#15 0x00005555555620d6 in main (argc=1, argv=0x7fffffffe118)
    at /builddir/weechat-4.1.1/src/gui/curses/normal/main.c:45
No locals.
```

WeeChat version:  weechat-4.1.1_1
OS, distribution and version:  Voidlinux (fully updated on Tue Nov 21 2023)
Terminal: foot
Terminal multiplexer (screen/tmux/…/none): none

**Comment by laemeiqu** [comment]
If title is unloaded before autosort then weechat does not crash on exit:
/script unload title
/exit

If autosort is unloaded before title then weechat does crash on exit or on unloading of title:
/script unload autosort
/script unload title

**Comment by ahesford** [comment]
This seems like something for upstream to fix. If they demonstrate that this is a Void packaging problem, please re-open this issue.
