### ISSUE TITLE
undefined symbol in python3-urwid

### ISSUE THREAD

**Issue by IcedQuinn** [void-linux/void-packages#47410]
### Is this a new report?

Yes

### System Info

Void 6.5.11_1 x86_64 AuthenticAMD notuptodate rrmFFFFFFFFF

### Package(s) Affected

vit-2.3.0_2

### Expected behaviour

Typing `vit` should start the software.

### Actual behaviour

```
icedquinn@astaraline ~/> vit
Traceback (most recent call last):
  File "/usr/bin/vit", line 33, in <module>
    sys.exit(load_entry_point('vit==2.3.0', 'console_scripts', 'vit')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/vit", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/vit/__init__.py", line 2, in <module>
    from .application import Application
  File "/usr/lib/python3.12/site-packages/vit/application.py", line 20, in <module>
    from vit.formatter_base import FormatterBase
  File "/usr/lib/python3.12/site-packages/vit/formatter_base.py", line 8, in <module>
    from vit import util
  File "/usr/lib/python3.12/site-packages/vit/util.py", line 7, in <module>
    from urwid.str_util import calc_width
ImportError: /usr/lib/python3.12/site-packages/urwid/str_util.so: undefined symbol: PyUnicode_AS_UNICODE
```

### Steps to reproduce

1. Install `vit`
2. Run it

**Comment by ahesford** [comment]
I bumped urwid; please confirm that an update fixes the problem.
