### ISSUE TITLE
codeblocks: doesn't start

### ISSUE THREAD

**Issue by Calandracas606** [void-linux/void-packages#47691]
### Is this a new report?

Yes

### System Info

Void 6.5.13_1 x86_64 GenuineIntel uptodate rFFFFFFF

### Package(s) Affected

codeblocks-20.03_6

### Expected behaviour

codeblocks application launches

### Actual behaviour

codeblocks application fails to start with error:
codeblocks: macrosmanager.cpp:111: void MacrosManager::Reset(): Assertion `m_RE_Unix.IsValid()' failed.

### Steps to reproduce

1. run "codeblocks" from the terminal
2. crash

**Comment by sgn** [comment]
```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff60a483f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff6055392 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff603f474 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff603f397 in __assert_fail_base (fmt=0x7ffff61b5a80 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7ffff7dfa8be "m_RE_Unix.IsValid()", file=file@entry=0x7ffff7dfa8ac "macrosmanager.cpp", line=line@entry=111, 
    function=function@entry=0x7ffff7dfa890 "void MacrosManager::Reset()") at ./assert/assert.c:92
#5  0x00007ffff604e192 in __GI___assert_fail (assertion=0x7ffff7dfa8be "m_RE_Unix.IsValid()", file=0x7ffff7dfa8ac "macrosmanager.cpp", line=111, 
    function=0x7ffff7dfa890 "void MacrosManager::Reset()") at ./assert/assert.c:101
#6  0x00007ffff7ac56c8 in MacrosManager::Reset() () from /usr/lib64/libcodeblocks.so.0
#7  0x00007ffff7ac5dc0 in MacrosManager::MacrosManager() () from /usr/lib64/libcodeblocks.so.0
#8  0x00007ffff7aced91 in Manager::GetMacrosManager() const () from /usr/lib64/libcodeblocks.so.0
#9  0x00007fffc685c16d in CompilerMINGW::SetVersionString() () from /usr/lib/codeblocks/plugins/libcompiler.so
#10 0x00007fffc685c8ca in CompilerMINGW::CompilerMINGW(wxString const&, wxString const&) () from /usr/lib/codeblocks/plugins/libcompiler.so
#11 0x00007fffc682fb64 in CompilerGCC::DoRegisterCompilers() () from /usr/lib/codeblocks/plugins/libcompiler.so
#12 0x00007fffc683d631 in CompilerGCC::OnAttach() () from /usr/lib/codeblocks/plugins/libcompiler.so
#13 0x00007ffff79e7608 in cbPlugin::Attach() () from /usr/lib64/libcodeblocks.so.0
#14 0x00007ffff7ade5d4 in PluginManager::AttachPlugin(cbPlugin*, bool) () from /usr/lib64/libcodeblocks.so.0
#15 0x00007ffff7ae296b in PluginManager::LoadAllPlugins() () from /usr/lib64/libcodeblocks.so.0
#16 0x000055555569bb1d in ?? ()
#17 0x000055555569f21a in ?? ()
#18 0x0000555555602d20 in ?? ()
#19 0x0000555555609d4b in ?? ()
#20 0x00007ffff674de13 in wxAppConsoleBase::CallOnInit (this=<optimized out>) at /builddir/wxWidgets-gtk3-3.2.4/include/wx/app.h:93
#21 wxEntry (argc=<optimized out>, argv=<optimized out>) at /builddir/wxWidgets-gtk3-3.2.4/src/common/init.cpp:481
#22 0x00005555555ef3a2 in main ()
```

**Comment by sgn** [comment]
https://sourceforge.net/p/codeblocks/tickets/1120/
