### ISSUE TITLE
mega-cmd cannot login due to mega-cmd-server crashing

### ISSUE THREAD

**Issue by devlocalhost** [void-linux/void-packages#48644]
### Is this a new report?

Yes

### System Info

Void 6.7.3_1 x86_64 GenuineIntel uptodate hold rdFFFFFFFF

### Package(s) Affected

MEGAcmd-1.4.0_2, MEGAsdk-3.7.3c_4

### Expected behaviour

mega-cmd logs in to your account

### Actual behaviour

mega-cmd does not login, instead:
```
...
[Server is probably down. Type to respawn or reconnect to it]
...
Unable to connect to service: error=111
Please ensure mega-cmd-server is running
```

### Steps to reproduce

1. install MEGAcmd
2. run mega-cmd and try to login

**Comment by devlocalhost** [comment]
here's what gdb says:
```
(gdb) bt
#0  __memcpy_ssse3 () at ../sysdeps/x86_64/multiarch/memmove-ssse3.S:67
#1  0x00007ffff77882b3 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long) () from /usr/lib/libstdc++.so.6
#2  0x00007ffff7bdedfb in mega::Node::serialize (this=0x7fffb416b1a0, d=0x7ffff37ff070)
    at src/node.cpp:558
#3  0x00007ffff7bc32b9 in mega::DbTable::put (this=0x7fffb40206a0, type=type@entry=1,
    record=0x7fffb416b1a0, key=key@entry=0x5555556d6d68) at src/db.cpp:44
#4  0x00007ffff7b3b273 in mega::MegaClient::updatesc (this=this@entry=0x5555556d5c50)
    at src/megaclient.cpp:4880
#5  0x00007ffff7b60d4b in mega::MegaClient::notifypurge (this=this@entry=0x5555556d5c50)
    at src/megaclient.cpp:6767
#6  0x00007ffff7b671b0 in mega::MegaClient::exec (this=<optimized out>)
    at src/megaclient.cpp:2846
#7  0x00007ffff7cd25f9 in mega::MegaApiImpl::loop (this=0x5555556970a0)
    at src/megaapi_impl.cpp:6301
#8  0x00007ffff7cd26ad in mega::MegaApiImpl::threadEntryPoint (param=0x5555556970a0)
    at src/megaapi_impl.cpp:5038
#9  0x00007ffff728a36b in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#10 0x00007ffff730c298 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```
