### ISSUE TITLE
Khal requires older python-dateutil version

### ISSUE THREAD

**Issue by BlackLotus** [void-linux/void-packages#495]
### System

* Void 4.17.3_1 x86_64 GenuineIntel notuptodate rrm
* khal-0.9.9_1

### Expected behavior
Khal should start

### Actual behavior
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.7.3 (/usr/lib/python3.6/site-packages), Requirement.parse('python-dateutil<=2.6.1'), {'khal'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/khal", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-dateutil<=2.6.1' distribution was not found and is required by khal
```
### Steps to reproduce the behavior
Install khal and try to execute it.

**Comment by BlackLotus** [comment]
K probably the right place for this thx

**Comment by Johnnynator** [comment]
I just added it for reference. You didn't have to close the issue.
