### ISSUE TITLE
vapoursynth import error

### ISSUE THREAD

**Issue by Tachiorz** [void-linux/void-packages#49857]
### Is this a new report?

Yes

### System Info

Void 6.6.25_1 x86_64 AuthenticAMD uptodate rFFFFFFFFFFFFF

### Package(s) Affected

vapoursynth-R66_1

### Expected behaviour

`import vapoursynth` should work

### Actual behaviour

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/cython/vapoursynth.pyx", line 86, in init vapoursynth
TypeError: function() argument 'code' must be code, not str

```

### Steps to reproduce

`$ python`
`>>> import vapoursynth`

**Comment by Tachiorz** [comment]
Build with python3-Cython to fix it
`hostmakedepends="automake libtool nasm pkg-config python3-Cython"`
@lemmi ?
