### ISSUE TITLE
cozy doesn't launch

### ISSUE THREAD

**Issue by meator** [void-linux/void-packages#50029]
### Is this a new report?

Yes

### System Info

irellevant

### Package(s) Affected

cozy-1.2.1_3

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/geigi/cozy/issues/756

### Expected behaviour

Program launching.

### Actual behaviour

```
> com.github.geigi.cozy
['/usr/bin/com.github.geigi.cozy']
14:35:11 [MainThread  ] [applicatio] [INFO ]  ('void', 'rolling', 'void')
14:35:11 [MainThread  ] [applicatio] [INFO ]  Starting up cozy 1.2.1
14:35:11 [MainThread  ] [db        ] [INFO ]  SQLite version: 3.45.2
14:35:11 [Thread-1 (ru] [peewee.sql] [INFO ]  writer received shutdown request, exiting.
14:35:11 [MainThread  ] [applicatio] [INFO ]  libhandy version: 1
handle exception
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/cozy/application.py", line 99, in do_activate
    self.app_controller = AppController(self, main_window_builder, self.ui)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cozy/architecture/singleton.py", line 5, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cozy/app_controller.py", line 52, in __init__
    self.whats_new_window: WhatsNewWindow = WhatsNewWindow()
                                            ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cozy/ui/widgets/whats_new_window.py", line 36, in __init__
    self._fill_window()
  File "/usr/lib/python3.12/site-packages/cozy/ui/widgets/whats_new_window.py", line 54, in _fill_window
    last_launched_version = version.parse(self.app_settings.last_launched_version)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/packaging/version.py", line 54, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'None'
```

An update to version 1.3.0 should resolve this problem. By the way, I'm not a `cozy` user, but I've stumbled upon the issue when testing one of its dependencies.

cc @stein

### Steps to reproduce

Mentioned above

**Comment by meator** [comment]
Don't know why the completion failed, meant to ping @steinex

**Comment by MIvanchev** [comment]
@meator Could you test 1.3.0?
