### ISSUE TITLE
Telegram crashes after update

### ISSUE THREAD

**Issue by basiliscos** [void-linux/void-packages#5012]
### System

* xuname:  

`Void 4.18.19_1 x86_64 GenuineIntel uptodate rrrmFFF`

* package:  
telegram-desktop-1.4.3_2

### Expected behavior

start app

### Actual behavior

crashes on start

```
Telegram
QApplication: invalid style override passed, ignoring it.
[1]    4283 segmentation fault  Telegram

Telegram[4427]: segfault at 7ffc3a6f6810 ip 0000556978b7e44a sp 00007ffc3a6ea760 error 4 in Telegram[556977e00000+234d000]
2018-11-22T17:04:12.428063+03:00 localhost kernel: [ 1126.703701] Code: 24 10 83 c2 01 48 63 d2 0f b7 78 06 eb 0f 66 90 41 0f b6 04 14 48 83 c2 01 a8 01 75 16 41 f6 44 14 ff 02 75 0a 48 8b 44 24 08 <44> 03 74 90 fc 39 d7 7f dd 49 8b 50 58 39 5a 04 7e 2e 48 8b 04 24 

```

Output via gdb

```
Thread 1 "Telegram" received signal SIGSEGV, Segmentation fault.
0x00005555562d244a in ?? ()
(gdb) bt
#0  0x00005555562d244a in  ()
#1  0x00005555562d169d in  ()
#2  0x00005555562cd772 in  ()
#3  0x00005555562d05c8 in  ()
#4  0x00005555562c5699 in  ()
#5  0x00005555562c58b2 in  ()
#6  0x0000555555c7bc0e in  ()
#7  0x0000555555c987ec in  ()
#8  0x000055555591de41 in  ()
#9  0x000055555591e1b0 in  ()
#10 0x000055555591ed98 in  ()
#11 0x00007ffff31e6f9b in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5                                                                                   
#12 0x00007ffff775b7b1 in QLocalSocket::error(QLocalSocket::LocalSocketError) () at /usr/lib/libQt5Network.so.5                                                                              
#13 0x00007ffff775d92a in  () at /usr/lib/libQt5Network.so.5
#14 0x00007ffff775e1ef in  () at /usr/lib/libQt5Network.so.5
#15 0x00007ffff775e388 in QLocalSocket::connectToServer(QFlags<QIODevice::OpenModeFlag>) () at /usr/lib/libQt5Network.so.5                                                                   
#16 0x000055555591e870 in  ()
#17 0x00005555559d3123 in  ()
#18 0x00005555559d3250 in  ()
#19 0x0000555555848662 in  ()
#20 0x00007ffff24133db in __libc_start_main (main=
    0x555555848630, argc=1, argv=0x7fffffffe278, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe268) at ../csu/libc-start.c:308                 
#21 0x000055555586219a in  ()
```

**Comment by maxice8** [comment]
https://github.com/void-linux/void-packages/pull/4988

**Comment by basiliscos** [comment]
Seems solved. 

Thank you!
