### ISSUE TITLE
Anki fails to start

### ISSUE THREAD

**Issue by phinas** [void-linux/void-packages#5053]
### System

* xuname:  Void 4.18.20_1 x86_64 AuthenticAMD uptodate rFFFFF
* package:  anki-2.1.5_1 

### Expected behavior
Anki starts when executing it on the commandline

### Actual behavior
Anki fails to start up with the following error message:

> Error during startup:
Traceback (most recent call last):
  File "/usr/share/anki/aqt/main.py", line 50, in __init__
    self.setupUI()
  File "/usr/share/anki/aqt/main.py", line 75, in setupUI
    self.setupMainWindow()
  File "/usr/share/anki/aqt/main.py", line 584, in setupMainWindow
    tweb = self.toolbarWeb = aqt.webview.AnkiWebView()
  File "/usr/share/anki/aqt/webview.py", line 114, in __init__
    self.focusProxy().installEventFilter(self)
AttributeError: 'NoneType' object has no attribute 'installEventFilter'

### Steps to reproduce the behavior
Update with xbps-install -Syu; try to start anki.

It stopped working after recent updates. I looked over anki's dependencies and assume the recent update of  qt5-webengine-5.10.1_14 to 5.11.2_1 introduced the error.

**Comment by Johnnynator** [comment]
https://bugs.archlinux.org/task/58734?project=5&string=anki

It seems it got fixed in master probably https://github.com/dae/anki/search?q=5.11&type=Commits . I will take a look at cherry-picking a few patches and see if I can get it working.

**Comment by Johnnynator** [comment]
This seems to be more complicated. I tested the latest beta and I just get a different error. I will see what I can do about it tomorrow.
```
Caught exception:
  File "/usr/share/anki/aqt/webview.py", line 294, in handler
    if self._shouldIgnoreWebEvent():
  File "/usr/share/anki/aqt/webview.py", line 324, in _shouldIgnoreWebEvent
    return not mw.col or sip.isdeleted(self)
<class 'TypeError'>: isdeleted() argument 1 must be sip.simplewrapper, not AnkiWebView
Caught exception:
  File "/usr/share/anki/aqt/webview.py", line 27, in cmd
    return json.dumps(self.onCmd(str))
  File "/usr/share/anki/aqt/webview.py", line 83, in _onCmd
    return self._onBridgeCmd(str)
  File "/usr/share/anki/aqt/webview.py", line 331, in _onBridgeCmd
    if self._shouldIgnoreWebEvent():
  File "/usr/share/anki/aqt/webview.py", line 324, in _shouldIgnoreWebEvent
    return not mw.col or sip.isdeleted(self)
<class 'TypeError'>: isdeleted() argument 1 must be sip.simplewrapper, not AnkiWebView
```
