### ISSUE TITLE
Missing dependencies in the beets package

### ISSUE THREAD

**Issue by cumdroplet** [void-linux/void-packages#50995]
### Is this a new report?

Yes

### System Info

Void 6.6.35_1 x86_64 GenuineIntel notuptodate rF

### Package(s) Affected

beets-2.0.0_1

### Expected behaviour

The beets package should install python3-typing_extensions

### Actual behaviour

The beets package does not install python3-typing_extensions, causing an error

### Steps to reproduce

n/a

**Comment by classabbyamp** [comment]
what's the error message?

**Comment by cumdroplet** [comment]
I apologise, I forgot to include this, wasn't thinking there

```
~ $ beet
Traceback (most recent call last):
  File "/usr/bin/beet", line 33, in <module>
    sys.exit(load_entry_point('beets==2.0.0', 'console_scripts', 'beet')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/beet", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/beets/ui/__init__.py", line 35, in <module>
    from beets import config, library, logging, plugins, util
  File "/usr/lib/python3.12/site-packages/beets/library.py", line 29, in <module>
    from beets import dbcore, logging, plugins, util
  File "/usr/lib/python3.12/site-packages/beets/dbcore/__init__.py", line 19, in <module>
    from .db import Database, Model, Results
  File "/usr/lib/python3.12/site-packages/beets/dbcore/db.py", line 54, in <module>
    from beets.util import functemplate, py3_path
  File "/usr/lib/python3.12/site-packages/beets/util/__init__.py", line 49, in <module>
    from typing_extensions import TypeAlias
ModuleNotFoundError: No module named 'typing_extensions'
```
