### ISSUE TITLE
Lutris missing dependency

### ISSUE THREAD

**Issue by nullptroma** [void-linux/void-packages#51383]
### Is this a new report?

Yes

### System Info

Void 6.8.12_2 x86_64 AuthenticAMD uptodate rrrmFFFFFF

### Package(s) Affected

lutris-0.5.17_1, python3-Pillow-10.4.0_1, python3-pillow-simd-7.1.2_7

### Expected behaviour

Lutris should start and run, having resolved all dependencies before doing so.

### Actual behaviour

When starting Lutris, an error occurs about a mismatch of the "_imaging extension" version, the program does not start.
```
--> lutris 
/usr/lib/python3.12/site-packages/PIL/Image.py:122: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: 9.5.0
Pillow version: 10.4.0
  warnings.warn(str(v), RuntimeWarning)
2024-07-22 14:32:08,646: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
/usr/lib/python3.12/site-packages/PIL/Image.py:122: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: 9.5.0
Pillow version: 10.4.0
  warnings.warn(str(v), RuntimeWarning)
Traceback (most recent call last):
  File "/sbin/lutris", line 61, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/gui/application.py", line 42, in <module>
    from lutris.gui.config.preferences_dialog import PreferencesDialog
  File "/usr/lib/python3.12/site-packages/lutris/gui/config/preferences_dialog.py", line 9, in <module>
    from lutris.gui.config.accounts_box import AccountsBox
  File "/usr/lib/python3.12/site-packages/lutris/gui/config/accounts_box.py", line 8, in <module>
    from lutris.gui.config.updates_box import UpdateButtonBox
  File "/usr/lib/python3.12/site-packages/lutris/gui/config/updates_box.py", line 12, in <module>
    from lutris.services.lutris import sync_media
  File "/usr/lib/python3.12/site-packages/lutris/services/__init__.py", line 8, in <module>
    from lutris.services.dolphin import DolphinService
  File "/usr/lib/python3.12/site-packages/lutris/services/dolphin.py", line 6, in <module>
    from PIL import Image
  File "/usr/lib/python3.12/site-packages/PIL/Image.py", line 108, in <module>
    raise ImportError(msg)
ImportError: The _imaging extension was built for another version of Pillow or PIL:
Core version: 9.5.0
Pillow version: 10.4.0
```
Pillow packages:
```
-->  sudo xbps-query -Rs pillow
[*] python3-Pillow-10.4.0_1     Python Imaging Library (PIL) for for Python3
[-] python3-pillow-simd-7.1.2_7 Python3 Imaging Library (PIL) fork (SIMD)
```

### Steps to reproduce

Just install lutris and update your system

**Comment by ahesford** [comment]
Try running

    xbps-pkgdb -a

to make sure that everything is in an expected state. If so, I suspect that something about your setup is shadowing the  python import path with a stale PIL package.

**Comment by nullptroma** [comment]
I'm sorry! I had Pillow installed from psp version 9.5.0, apparently I installed it by accident when I was setting up dots-hyprland at home. 
I deleted the extra package, now everything works!
