### ISSUE TITLE
Package Request: Gitkraken

### ISSUE THREAD

**Issue by archfan** [void-linux/void-packages#5200]
Can we add Gitkraken to the repo? It's a neat frontend for git. Unfortunately it doesn't work out of the box.

URL: https://support.gitkraken.com/how-to-install

Gitkraken is unable to utilize the nodegit module which I have installed with 'npm install nodegit'. Perhaps we could work on a template and fix that issue along the way?

`/gitkraken 
Node started time: 1543433144854
Cannot find module 'build/Debug/nodegit.node'
Error: Cannot find module 'build/Debug/nodegit.node'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/y/Downloads/gitkraken/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/y/Downloads/gitkraken/resources/app.asar/node_modules/@axosoft/nodegit/dist/nodegit.js:66:12)
    at Object.<anonymous> (/home/y/Downloads/gitkraken/resources/app.asar/node_modules/@axosoft/nodegit/dist/nodegit.js:1198:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
`

**Comment by m3tav3rse** [comment]
[This one](https://flathub.org/apps/details/com.axosoft.GitKraken) should work out of the box

**Comment by maxice8** [comment]
Couldn't find the source code.

**Comment by developer1-vd** [comment]
even i needed this
