### ISSUE TITLE
`backblaze-b2` is unusable

### ISSUE THREAD

**Issue by OoLunar** [void-linux/void-packages#53257]
### Is this a new report?

Yes

### System Info

Void 6.6.60_1 x86_64 GenuineIntel uptodate rrrrmmnFFFFF

### Package(s) Affected

backblaze-b2-4.2.0_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

N/A

### Expected behaviour

For `backblaze-b2` to be able to work in any capacity.

### Actual behaviour

```
Traceback (most recent call last):
  File "/usr/bin/backblaze-b2", line 5, in <module>
    from b2._internal.b2v4.__main__ import main
  File "/usr/lib/python3.12/site-packages/b2/_internal/b2v4/__main__.py", line 11, in <module>
    from b2._internal.b2v4.registry import main
  File "/usr/lib/python3.12/site-packages/b2/_internal/b2v4/registry.py", line 12, in <module>
    from b2._internal.console_tool import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/b2/_internal/console_tool.py", line 19, in <module>
    from b2._internal._cli.autocomplete_cache import AUTOCOMPLETE  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/b2/_internal/_cli/autocomplete_cache.py", line 20, in <module>
    import argcomplete
ModuleNotFoundError: No module named 'argcomplete'
```

This happens on all/no arguments.

### Steps to reproduce

Run `backblaze-b2` in anyway or manner.

**Comment by biopsin** [comment]
Try manually install **python3-argcomplete** , might be missing a dependancy.

**Comment by OoLunar** [comment]
I had to install both `python3-argcomplete` and `python3-platformdirs`, however the following error appears below:
```
Traceback (most recent call last):
  File "/usr/bin/backblaze-b2", line 5, in <module>
    from b2._internal.b2v4.__main__ import main
  File "/usr/lib/python3.12/site-packages/b2/_internal/b2v4/__main__.py", line 11, in <module>
    from b2._internal.b2v4.registry import main
  File "/usr/lib/python3.12/site-packages/b2/_internal/b2v4/registry.py", line 12, in <module>
    from b2._internal.console_tool import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/b2/_internal/console_tool.py", line 57, in <module>
    from b2sdk.v2 import (
  File "/usr/lib/python3.12/site-packages/b2sdk/v2/__init__.py", line 12, in <module>
    from b2sdk._v3 import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/b2sdk/_v3/__init__.py", line 30, in <module>
    from b2sdk._internal.api import B2Api
  File "/usr/lib/python3.12/site-packages/b2sdk/_internal/api.py", line 17, in <module>
    from .account_info.abstract import AbstractAccountInfo
  File "/usr/lib/python3.12/site-packages/b2sdk/_internal/account_info/__init__.py", line 12, in <module>
    from .in_memory import InMemoryAccountInfo
  File "/usr/lib/python3.12/site-packages/b2sdk/_internal/account_info/in_memory.py", line 15, in <module>
    from .upload_url_pool import UrlPoolAccountInfo
  File "/usr/lib/python3.12/site-packages/b2sdk/_internal/account_info/upload_url_pool.py", line 16, in <module>
    from .abstract import AbstractAccountInfo
  File "/usr/lib/python3.12/site-packages/b2sdk/_internal/account_info/abstract.py", line 15, in <module>
    from b2sdk._internal.raw_api import ALL_CAPABILITIES
  File "/usr/lib/python3.12/site-packages/b2sdk/_internal/raw_api.py", line 43, in <module>
    from .types import NotRequired, PositiveInt, TypedDict
  File "/usr/lib/python3.12/site-packages/b2sdk/_internal/types.py", line 17, in <module>
    from annotated_types import Ge
ModuleNotFoundError: No module named 'annotated_types'
```

**Comment by biopsin** [comment]
install python3-annotated-types too

**Comment by ppolewicz** [comment]
Is there something the upstream package should do to make it easier to deploy it on void-linux?

**Comment by biopsin** [comment]
@ppolewicz the void template should probably just be adjusted for additional run dependencies to
```
depends="python3-Arrow python3-b2sdk python3-docutils python3-phx-class-registry 
 python3-rst2ansi python3-tabulate python3-argcomplete python3-platformdirs
 python3-annotated-types"
```

**Comment by MIvanchev** [comment]
I can adjust the template but B2 seems to be missing `annotated-types` in the project.toml upstream @ppolewicz.

**Comment by classabbyamp** [comment]
> I can adjust the template but B2 seems to be missing `annotated-types` in the project.toml upstream @ppolewicz.

I mentioned it [here](https://github.com/void-linux/void-packages/pull/53413/files#r1875120296) but `annotated-types` is actually a dependency of `b2sdk`

**Comment by ppolewicz** [comment]
it's defined as a dependency [here](https://github.com/Backblaze/b2-sdk-python/blob/master/pyproject.toml#L9), as it should be
