### ISSUE TITLE
Synapse 1.120.0_2 broken

### ISSUE THREAD

**Issue by 81909ce2298f99ddafa37936ba43eaac** [void-linux/void-packages#53595]
[Uploading updates-2024-12-20.txt…]()
### Is this a new report?

Yes

### System Info

Void 6.6.66-0-lts x86_64 AuthenticAMD uptodate rFF

### Package(s) Affected

synapse-1.120.0_2, python3-3.13.1_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No (AFAIK), but I wrote a bug report here: https://github.com/element-hq/synapse/issues/18042

### Expected behaviour

Synapse should start without any errors like before the update this night.

### Actual behaviour

The system runs perfectly since many month and it's updating itself every night. After the last update synapse (matrix) is not starting anymore. I attached a list of all packages which has been updated this night successfully by using "xbps-install -Su --yes". The log shows the following errors now when starting synapse:

2024-12-20T10:38:50.05669 daemon.notice: Dec 20 11:38:50 synapse: Traceback (most recent call last):
2024-12-20T10:38:50.07886 daemon.notice: Dec 20 11:38:50 synapse:   File "/usr/bin/synapse_homeserver", line 5, in <module>
2024-12-20T10:38:50.07924 daemon.notice: Dec 20 11:38:50 synapse:     from synapse.app.homeserver import main
2024-12-20T10:38:50.07927 daemon.notice: Dec 20 11:38:50 synapse:   File "/usr/lib/python3.13/site-packages/synapse/__init__.py", line 31, in <module>
2024-12-20T10:38:50.07930 daemon.notice: Dec 20 11:38:50 synapse:     from synapse.util.rust import check_rust_lib_up_to_date
2024-12-20T10:38:50.07950 daemon.notice: Dec 20 11:38:50 synapse:   File "/usr/lib/python3.13/site-packages/synapse/util/__init__.py", line 32, in <module>
2024-12-20T10:38:50.07957 daemon.notice: Dec 20 11:38:50 synapse:     from twisted.internet import defer, task
2024-12-20T10:38:50.07963 daemon.notice: Dec 20 11:38:50 synapse:   File "/usr/lib/python3.13/site-packages/twisted/internet/defer.py", line 48, in <module>
2024-12-20T10:38:50.07986 daemon.notice: Dec 20 11:38:50 synapse:     from twisted.internet.interfaces import IDelayedCall, IReactorTime
2024-12-20T10:38:50.07992 daemon.notice: Dec 20 11:38:50 synapse:   File "/usr/lib/python3.13/site-packages/twisted/internet/interfaces.py", line 26, in <module>
2024-12-20T10:38:50.08003 daemon.notice: Dec 20 11:38:50 synapse:     from zope.interface import Attribute, Interface
2024-12-20T10:38:50.08010 daemon.notice: Dec 20 11:38:50 synapse:   File "/usr/lib/python3.13/site-packages/zope/interface/__init__.py", line 57, in <module>
2024-12-20T10:38:50.08056 daemon.notice: Dec 20 11:38:50 synapse:     _wire()
2024-12-20T10:38:50.08065 daemon.notice: Dec 20 11:38:50 synapse:     ~~~~~^^
2024-12-20T10:38:50.08074 daemon.notice: Dec 20 11:38:50 synapse:   File "/usr/lib/python3.13/site-packages/zope/interface/interface.py", line 1104, in _wire
2024-12-20T10:38:50.08080 daemon.notice: Dec 20 11:38:50 synapse:     from zope.interface.interfaces import IElement
2024-12-20T10:38:50.08135 daemon.notice: Dec 20 11:38:50 synapse:   File "/usr/lib/python3.13/site-packages/zope/interface/interfaces.py", line 54, in <module>
2024-12-20T10:38:50.08149 daemon.notice: Dec 20 11:38:50 synapse:     class IElement(Interface):
2024-12-20T10:38:50.08174 daemon.notice: Dec 20 11:38:50 synapse:     ...<91 lines>...
2024-12-20T10:38:50.08183 daemon.notice: Dec 20 11:38:50 synapse:             """
2024-12-20T10:38:50.08362 daemon.notice: Dec 20 11:38:50 synapse:   File "/usr/lib/python3.13/site-packages/zope/interface/interface.py", line 772, in __init__
2024-12-20T10:38:50.08372 daemon.notice: Dec 20 11:38:50 synapse:     self.__attrs = self.__compute_attrs(attrs)
2024-12-20T10:38:50.08378 daemon.notice: Dec 20 11:38:50 synapse:                    ~~~~~~~~~~~~~~~~~~~~^^^^^^^
2024-12-20T10:38:50.08383 daemon.notice: Dec 20 11:38:50 synapse:   File "/usr/lib/python3.13/site-packages/zope/interface/interface.py", line 791, in __compute_attrs
2024-12-20T10:38:50.08388 daemon.notice: Dec 20 11:38:50 synapse:     aname: update_value(aname, aval)
2024-12-20T10:38:50.08393 daemon.notice: Dec 20 11:38:50 synapse:            ~~~~~~~~~~~~^^^^^^^^^^^^^
2024-12-20T10:38:50.08429 daemon.notice: Dec 20 11:38:50 synapse:   File "/usr/lib/python3.13/site-packages/zope/interface/interface.py", line 787, in update_value
2024-12-20T10:38:50.08436 daemon.notice: Dec 20 11:38:50 synapse:     raise InvalidInterface("Concrete attribute, " + aname)
2024-12-20T10:38:50.08442 daemon.notice: Dec 20 11:38:50 synapse: zope.interface.exceptions.InvalidInterface: Concrete attribute, __firstlineno__

### Steps to reproduce

1. Update to the latest version of python3, its libraries and synapse (please see the list above).
2. sv start synapse
3. Synapse will not start and throw the errors shown above.

**Comment by 81909ce2298f99ddafa37936ba43eaac** [comment]
There seems to be a problem with my attachment. After five minutes it's still not available. Here's the list of the packages which have been updated this night:

c-ares (1.34.3_1 -> 1.34.4_1) 
device-mapper (2.03.23_1 -> 2.03.29_1) 
glib (2.82.1_1 -> 2.82.1_2) 
libcap-ng (0.8.5_1 -> 0.8.5_2) 
libjpeg-turbo (3.0.1_1 -> 3.1.0_2) 
libproxy (0.4.18_3 -> 0.4.18_4) 
libxml2 (2.12.6_1 -> 2.12.6_2) 
libxslt (1.1.39_2 -> 1.1.39_3) 
postgresql-libs (16.4_1 -> 16.4_2) 
postgresql16 (16.4_1 -> 16.4_2) 
postgresql16-client (16.4_1 -> 16.4_2) 
python (2.7.9999_1 -> 3.13_2) 
python3 (3.12.7_1 -> 3.13.1_1) 
python3-Jinja2 (3.1.4_1 -> 3.1.4_2) 
python3-MarkupSafe (2.1.5_1 -> 3.0.2_1) 
python3-Pillow (10.4.0_1 -> 11.0.0_1) 
python3-Twisted (24.7.0_1 -> 24.7.0_2) 
python3-annotated-types (0.6.0_1 -> 0.6.0_2) 
python3-attrs (24.2.0_1 -> 24.2.0_2) 
python3-automat (22.10.0_3 -> 22.10.0_4) 
python3-bcrypt (4.1.2_1 -> 4.1.2_2) 
python3-bleach (6.0.0_2 -> 6.0.0_3) 
python3-canonicaljson (2.0.0_2 -> 2.0.0_3) 
python3-cffi (1.17.1_1 -> 1.17.1_2) 
python3-charset-normalizer (3.3.2_1 -> 3.3.2_2) 
python3-constantly (23.10.4_1 -> 23.10.4_2) 
python3-cryptography (43.0.1_1 -> 44.0.0_1) 
python3-dateutil (2.9.0_1 -> 2.9.0_2) 
python3-defusedxml (0.7.1_2 -> 0.7.1_3) 
python3-devel (3.12.7_1 -> 3.13.1_1) 
python3-distlib (0.3.6_2 -> 0.3.6_3) 
python3-elementpath (3.0.2_3 -> 3.0.2_4) 
python3-filelock (3.15.4_1 -> 3.15.4_2) 
python3-hyperlink (21.0.0_4 -> 21.0.0_5) 
python3-idna (3.7_1 -> 3.7_2) 
python3-ijson (3.3.0_1 -> 3.3.0_2) 
python3-immutabledict (4.2.0_1 -> 4.2.0_2) 
python3-incremental (24.7.2_1 -> 24.7.2_2) 
python3-jsonschema (4.23.0_1 -> 4.23.0_2) 
python3-jsonschema-specifications (2023.12.1_1 -> 2023.12.1_2) 
python3-lxml (5.3.0_1 -> 5.3.0_2) 
python3-macaroons (0.13.0_7 -> 0.13.0_8) 
python3-matrix-common (1.3.0_3 -> 1.3.0_4) 
python3-msgpack (1.1.0_1 -> 1.1.0_2) 
python3-netaddr (1.3.0_1 -> 1.3.0_2) 
python3-openssl (24.2.1_1 -> 24.2.1_2) 
python3-packaging (24.1_1 -> 24.2_1) 
python3-parsing (3.1.4_1 -> 3.2.0_1) 
python3-phonenumbers (8.13.43_1 -> 8.13.43_2) 
python3-platformdirs (4.3.6_1 -> 4.3.6_2) 
python3-ply (3.11_8 -> 3.11_9) 
python3-prometheus_client (0.20.0_1 -> 0.20.0_2) 
python3-psutil (5.9.8_1 -> 5.9.8_2) 
python3-psycopg2 (2.9.3_3 -> 2.9.3_4) 
python3-pyasn1 (0.5.1_1 -> 0.5.1_2) 
python3-pyasn1-modules (0.3.0_1 -> 0.3.0_2) 
python3-pycparser (2.21_2 -> 2.21_3) 
python3-pydantic (2.8.2_1 -> 2.8.2_2) 
python3-pydantic-core (2.21.0_1 -> 2.21.0_2) 
python3-pynacl (1.5.0_4 -> 1.5.0_5) 
python3-python-multipart (0.0.9_1 -> 0.0.9_2) 
python3-pytz (2024.2_1 -> 2024.2_2) 
python3-referencing (0.35.1_2 -> 0.35.1_3) 
python3-requests (2.32.3_1 -> 2.32.3_2) 
python3-rpds-py (0.20.0_1 -> 0.20.0_2) 
python3-saml2 (7.5.0_1 -> 7.5.0_2) 
python3-service_identity (23.1.0_1 -> 23.1.0_2) 
python3-setuptools (75.1.0_1 -> 75.6.0_1) 
python3-signedjson (1.1.4_3 -> 1.1.4_4) 
python3-six (1.16.0_4 -> 1.16.0_5) 
python3-sortedcontainers (2.4.0_5 -> 2.4.0_6) 
python3-treq (23.11.0_1 -> 23.11.0_2) 
python3-typing_extensions (4.10.0_1 -> 4.12.2_1) 
python3-unpaddedbase64 (2.1.0_3 -> 2.1.0_4) 
python3-urllib3 (1.26.12_2 -> 1.26.12_3) 
python3-virtualenv (20.27.1_1 -> 20.27.1_2) 
python3-webencodings (0.5.1_9 -> 0.5.1_10) 
python3-xmlschema (2.5.0_1 -> 2.5.0_2) 
python3-yaml (6.0.2_1 -> 6.0.2_2) 
python3-zope.interface (6.1_1 -> 6.1_2) 
synapse (1.120.0_1 -> 1.120.0_2)

**Comment by classabbyamp** [comment]
can you try updating? new python3-zope.interface may fix this

https://github.com/void-linux/void-packages/commit/55f51f8b97767ed139aaa535f8ff79ed3c9c87ca

**Comment by 81909ce2298f99ddafa37936ba43eaac** [comment]
Unfortunately, it did not work. What I did:

1. git clone https://github.com/void-linux/void-packages.git
2. cd void-packages
3. ./xbps-src binary-bootstrap
4. ./xbps-src pkg python3-zope.interface
5. sudo xbps-install --repository hostdir/binpkgs python3-zope.interface-7.2_1
6. sv restart synapse

The log then shows:

2024-12-21T17:46:44.22088 daemon.notice: Dec 21 18:46:44 synapse:   File "/usr/lib/python3.13/site-packages/treq/content.py", line 1, in <module>
2024-12-21T17:46:44.22095 daemon.notice: Dec 21 18:46:44 synapse:     import cgi
2024-12-21T17:46:44.22096 daemon.notice: Dec 21 18:46:44 synapse: ModuleNotFoundError: No module named 'cgi'
2024-12-21T17:46:48.63890 daemon.notice: Dec 21 18:46:48 synapse: Traceback (most recent call last):
2024-12-21T17:46:48.64152 daemon.notice: Dec 21 18:46:48 synapse:   File "/usr/bin/synapse_homeserver", line 5, in <module>
2024-12-21T17:46:48.64156 daemon.notice: Dec 21 18:46:48 synapse:     from synapse.app.homeserver import main
2024-12-21T17:46:48.64157 daemon.notice: Dec 21 18:46:48 synapse:   File "/usr/lib/python3.13/site-packages/synapse/app/homeserver.py", line 43, in <module>
2024-12-21T17:46:48.64158 daemon.notice: Dec 21 18:46:48 synapse:     from synapse.app import _base
2024-12-21T17:46:48.64159 daemon.notice: Dec 21 18:46:48 synapse:   File "/usr/lib/python3.13/site-packages/synapse/app/_base.py", line 71, in <module>
2024-12-21T17:46:48.64161 daemon.notice: Dec 21 18:46:48 synapse:     from synapse.events.auto_accept_invites import InviteAutoAccepter
2024-12-21T17:46:48.64162 daemon.notice: Dec 21 18:46:48 synapse:   File "/usr/lib/python3.13/site-packages/synapse/events/auto_accept_invites.py", line 28, in <module>
2024-12-21T17:46:48.64163 daemon.notice: Dec 21 18:46:48 synapse:     from synapse.module_api import EventBase, ModuleApi, run_as_background_process
2024-12-21T17:46:48.64164 daemon.notice: Dec 21 18:46:48 synapse:   File "/usr/lib/python3.13/site-packages/synapse/module_api/__init__.py", line 70, in <module>
2024-12-21T17:46:48.64167 daemon.notice: Dec 21 18:46:48 synapse:     from synapse.http.client import SimpleHttpClient
2024-12-21T17:46:48.64172 daemon.notice: Dec 21 18:46:48 synapse:   File "/usr/lib/python3.13/site-packages/synapse/http/client.py", line 39, in <module>
2024-12-21T17:46:48.64204 daemon.notice: Dec 21 18:46:48 synapse:     import treq
2024-12-21T17:46:48.64207 daemon.notice: Dec 21 18:46:48 synapse:   File "/usr/lib/python3.13/site-packages/treq/__init__.py", line 5, in <module>
2024-12-21T17:46:48.64214 daemon.notice: Dec 21 18:46:48 synapse:     from treq.api import head, get, post, put, patch, delete, request
2024-12-21T17:46:48.64217 daemon.notice: Dec 21 18:46:48 synapse:   File "/usr/lib/python3.13/site-packages/treq/api.py", line 5, in <module>
2024-12-21T17:46:48.64218 daemon.notice: Dec 21 18:46:48 synapse:     from treq.client import HTTPClient
2024-12-21T17:46:48.64219 daemon.notice: Dec 21 18:46:48 synapse:   File "/usr/lib/python3.13/site-packages/treq/client.py", line 32, in <module>
2024-12-21T17:46:48.64221 daemon.notice: Dec 21 18:46:48 synapse:     from treq.response import _Response
2024-12-21T17:46:48.64222 daemon.notice: Dec 21 18:46:48 synapse:   File "/usr/lib/python3.13/site-packages/treq/response.py", line 7, in <module>
2024-12-21T17:46:48.64223 daemon.notice: Dec 21 18:46:48 synapse:     from treq.content import collect, content, json_content, text_content

I undid the changes with the following commands:

1. sudo xdowngrade /var/cache/xbps/python3-zope.interface-6.1_2.x86_64.xbps
2. sv restart synapse

After that I get the same error messages as before.

**Comment by classabbyamp** [comment]
you didn't need to build it, it's in the repos...
