### ISSUE TITLE
`gpgme` issue with `torbrowser-launcher`

### ISSUE THREAD

**Issue by Clos3y** [void-linux/void-packages#53602]
### Is this a new report?

Yes

### System Info

Void 6.6.66_1 x86_64 AuthenticAMD uptodate rrrmFFFFFFFF

### Package(s) Affected

torbrowser-launcher-0.3.7_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

- Not an official bug report but relevant https://forums.gentoo.org/viewtopic-t-1170670.html
- https://github.com/pypa/setuptools/issues/4642
- https://github.com/NixOS/nixpkgs/issues/354166
- https://dev.gnupg.org/T7281

### Expected behaviour

`torbrowser-launcher` should run

### Actual behaviour

```.pytb
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    import torbrowser_launcher
  File "/usr/lib/python3.13/site-packages/torbrowser_launcher/__init__.py", line 37, in <module>
    from .common import Common, SHARE
  File "/usr/lib/python3.13/site-packages/torbrowser_launcher/common.py", line 37, in <module>
    import gpg
  File "/usr/lib/python3.13/site-packages/gpg/__init__.py", line 123, in <module>
    from . import core
  File "/usr/lib/python3.13/site-packages/gpg/core.py", line 10, in <module>
    from . import gpgme
ImportError: cannot import name 'gpgme' from partially initialized module 'gpg' (most likely due to a circular import) (/usr/lib/python3.13/site-packages/gpg/__init__.py)
```

### Steps to reproduce

1. `$ torbrowser-launcher`

**Comment by classabbyamp** [comment]
#53604
