### ISSUE TITLE
gmrun segfaulting as of 0.9.2_4

### ISSUE THREAD

**Issue by zevweiss** [void-linux/void-packages#5362]
### System

* xuname:  Void 4.19.5_1 x86_64 GenuineIntel uptodate rrdFFFFFF
* package:  gmrun-0.9.2_4

### Expected behavior

Working as it was with 0.9.2_3

### Actual behavior

```
$ gmrun 
Segmentation fault
```

### Steps to reproduce the behavior

Execute `gmrun`.

Run under gdb (with `gmrun-dbg` installed), the backtrace from the point at which it crashes is:

```
$ gdb gmrun

Reading symbols from gmrun...Reading symbols from /usr/lib/debug//usr/bin/gmrun...done.
done.
(gdb): r
Starting program: /usr/bin/gmrun 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff74a4b4b in g_type_is_a () from /usr/lib/libgobject-2.0.so.0
(gdb): bt
#0  0x00007ffff74a4b4b in g_type_is_a () from /usr/lib/libgobject-2.0.so.0
#1  0x00007ffff7bb7924 in gtk_type_new () from /usr/lib/libgtk-x11-2.0.so.0
#2  0x000055555555b895 in gtk_completion_line_new () at gtkcompletionline.cc:781
#3  0x000055555555a9b3 in main () at main.cc:570
#4  0x00007ffff6b8b09b in __libc_start_main (main=0x55555555a740 <main>, argc=1, argv=0x7fffffffe418, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffe408) at ../csu/libc-start.c:308
#5  0x000055555555b02a in _start () at ../sysdeps/x86_64/start.S:120
```

Curiously, when run under valgrind it doesn't crash, and memcheck does not report any errors.

**Comment by maxice8** [comment]
https://sourceforge.net/p/gmrun/bugs/9/
https://sourceforge.net/p/gmrun/bugs/8/
