### ISSUE TITLE
No module named pipes - meld

### ISSUE THREAD

**Issue by tuxslack** [void-linux/void-packages#53652]
### Is this a new report?

Yes

### System Info

Void Linux x86_64

### Package(s) Affected

**meld 3.22.2_2** and **Python 3.13.1**

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

-

### Expected behaviour

-

### Actual behaviour

Using meld program without error.

The ModuleNotFoundError: No module named 'pipes' error occurs because the pipes module was removed in Python 3.12, and Meld appears to be trying to use it, which results in an error if you are using that version of Python.

### Steps to reproduce

$ meld 
Traceback (most recent call last):
  File "/usr/sbin/meld", line 462, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/sbin/meld", line 458, in main
    return run_application()
  File "/usr/sbin/meld", line 438, in run_application
    from meld.meldapp import MeldApp
  File "/usr/lib/python3.13/site-packages/meld/meldapp.py", line 27, in <module>
    from meld.filediff import FileDiff
  File "/usr/lib/python3.13/site-packages/meld/filediff.py", line 46, in <module>
    from meld.melddoc import ComparisonState, MeldDoc, open_files_external
  File "/usr/lib/python3.13/site-packages/meld/melddoc.py", line 20, in <module>
    import pipes
**ModuleNotFoundError: No module named 'pipes'**


Ex: file 1 e 2

$ meld 1 2 
Traceback (most recent call last):
  File "/usr/sbin/meld", line 462, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/sbin/meld", line 458, in main
    return run_application()
  File "/usr/sbin/meld", line 438, in run_application
    from meld.meldapp import MeldApp
  File "/usr/lib/python3.13/site-packages/meld/meldapp.py", line 27, in <module>
    from meld.filediff import FileDiff
  File "/usr/lib/python3.13/site-packages/meld/filediff.py", line 46, in <module>
    from meld.melddoc import ComparisonState, MeldDoc, open_files_external
  File "/usr/lib/python3.13/site-packages/meld/melddoc.py", line 20, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'



$ xbps-query -S meld
**architecture: x86_64**
filename-sha256: 218aa51dddfe11341aaef7649dbfef20eafc00403fb6157d83b94e08f760446a
filename-size: 640KB
homepage: http://meldmerge.org/
install-date: 2024-12-23 15:04 -03
install-script: 1368B
installed_size: 3258KB
license: GPL-2.0-or-later
maintainer: Helmut Pozimski <helmut@pozimski.eu>
metafile-sha256: 75c879402789ebbf5dd619ac9cea6f79486148c6cb99187656100ed0923ffcd9
pkgname: meld
**pkgver: meld-3.22.2_2**
remove-script: 1481B
repository: https://repo-default.voidlinux.org/current
run_depends:
	python3-gobject>=0
	gsettings-desktop-schemas>=0
	gtksourceview4>=0
	desktop-file-utils>=0
	hicolor-icon-theme>=0
short_desc: Visual diff and merge tool
source-revisions: meld:0fa8253dd7a
state: installed

**Comment by classabbyamp** [comment]
b0ea806f3de55ac408ecfa9ceda595a9740885e5

**Comment by tuxslack** [comment]
> [b0ea806](https://github.com/void-linux/void-packages/commit/b0ea806f3de55ac408ecfa9ceda595a9740885e5)


Thanks  classabbyamp

The Meld program is working now... 

![meld](https://github.com/user-attachments/assets/d37d67a2-c3de-4153-82f1-244a78260d5b)
