### ISSUE TITLE
Calibre: please update to match the current qt version

### ISSUE THREAD

**Issue by annadane** [void-linux/void-packages#5412]
I can't open Calibre; I get the following:

```
[annadane@void ~]$ calibre

(python2:30527): dbind-WARNING **: 14:10:16.055: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/bin/calibre", line 20, in <module>
    sys.exit(calibre())
  File "/usr/lib/calibre/calibre/gui_launch.py", line 74, in calibre
    main(args)
  File "/usr/lib/calibre/calibre/gui2/main.py", line 527, in main
    app, opts, args = init_qt(args)
  File "/usr/lib/calibre/calibre/gui2/main.py", line 113, in init_qt
    app = Application(args, override_program_name=override)
  File "/usr/lib/calibre/calibre/gui2/__init__.py", line 839, in __init__
    self.setup_styles(force_calibre_style)
  File "/usr/lib/calibre/calibre/gui2/__init__.py", line 942, in setup_styles
    self.load_calibre_style()
  File "/usr/lib/calibre/calibre/gui2/__init__.py", line 973, in load_calibre_style
    self.pi.load_style(icon_map)
AttributeError: 'NoneType' object has no attribute 'load_style'
```
In receiving support for this issue I was told this is because Calibre has to be updated to take account of newer pyqt/qt versions

**Comment by annadane** [comment]
@thypon

**Comment by thypon** [comment]
I am disowning any python package.
