### ISSUE TITLE
Package Broken: Guake

### ISSUE THREAD

**Issue by johnny-mac** [void-linux/void-packages#5818]
As of today when I ran an update guake no longer functions, it complains about glib-compile-schemas
```
Guake not running, starting it
Unable to load the GLib schema, try to compile it
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/guake/main.py", line 295, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/guake/guake_app.py", line 123, in __init__
    schema_source = load_schema()
  File "/home/user/.local/lib/python3.6/site-packages/guake/guake_app.py", line 119, in load_schema
    SCHEMA_DIR, Gio.SettingsSchemaSource.get_default(), False
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/home/user/.local/lib/python3.6/site-packages/data/gschemas.compiled”: open() failed: No such file or directory (4)
Error opening directory “/home/user/.local/lib/python3.6/site-packages/data”: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/guake/main.py", line 295, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/guake/guake_app.py", line 123, in __init__
    schema_source = load_schema()
  File "/home/user/.local/lib/python3.6/site-packages/guake/guake_app.py", line 119, in load_schema
    SCHEMA_DIR, Gio.SettingsSchemaSource.get_default(), False
gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/home/user/.local/lib/python3.6/site-packages/data/gschemas.compiled”: open() failed: No such file or directory (4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/home/user/.local/lib/python3.6/site-packages/guake/main.py", line 410, in exec_main
    if not main():
  File "/home/user/.local/lib/python3.6/site-packages/guake/main.py", line 310, in main
    instance = Guake()
  File "/home/user/.local/lib/python3.6/site-packages/guake/guake_app.py", line 126, in __init__
    try_to_compile_glib_schemas()
  File "/home/user/.local/lib/python3.6/site-packages/guake/paths.py", line 97, in try_to_compile_glib_schemas
    subprocess.check_call(["glib-compile-schemas", "--strict", SCHEMA_DIR])
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['glib-compile-schemas', '--strict', '/home/user/.local/lib/python3.6/site-packages/data']' returned non-zero exit status 1.
```

**Comment by johnny-mac** [comment]
Compiling guake without glib-compile-schemas appears to have no change...

**Comment by Johnnynator** [comment]
Broke for me too. @prspkt Did you actually test your update?

**Comment by TobyThomasTech** [comment]
Hi. I still get this error with guake. I notice this issue has been closed. Could you please let me know how to fix this issue.

**Comment by Johnnynator** [comment]
@TobyThomasTech Can you open a separate issue for this?
