### ISSUE TITLE
pycp broken after update

### ISSUE THREAD

**Issue by whoizit** [void-linux/void-packages#7365]
### System

* xuname:  
Void 4.19.16_1 x86_64 AuthenticAMD uptodate rFFFFFFFF
* package:  
pycp-8.0.6_1
python3-cli-ui-0.9.1_1

### Steps to reproduce the behavior
```
$ pycp
Traceback (most recent call last):
  File "/usr/bin/pycp", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/user/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/home/user/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/user/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/home/user/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/user/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-cli-ui' distribution was not found and is required by pycp

```

**Comment by whoizit** [comment]
I've manyally reinstall pycp and python3-cli-ui, not helps

**Comment by Hoshpak** [comment]
@ndowens

**Comment by maxice8** [comment]
@whoizit i have pushed an update, can you try version 8.0.6_2 ?

**Comment by maxice8** [comment]
@whoizit the problem is that python3-cli-ui above version 8 did a few breaking changes

- They renamed the project to `cli-ui` (was `python-cli-ui`)
- They renamed their module to `cli_ui` (was `ui`)

I renamed the occurences of `import ui` and `ui.` to `import cli_ui` and `cli_ui.`

and changes the dependencies on setup.py's `install_requires` to request `cli-ui` instead of `python-cli-ui`
