### ISSUE TITLE
android-studio-3.1.2_1 outputs error on new project creation

### ISSUE THREAD

**Issue by noblehelm** [void-linux/void-packages#808]
### System

* xuname:  
  *Void 4.17.4_1 x86_64 GenuineIntel notuptodate rrF*
* package:  
  *android-studio-3.1.2_1*

### Expected behavior
Be able to create/start new projects.
### Actual behavior
The IDE doesn't start a new project and outputs an error:
```
com.android.tools.idea.templates.FreemarkerUtils$TemplateProcessingException: java.io.FileNotFoundException: Template "root://gradle-projects/NewAndroidModule/root/test/app_package/ExampleInstrumentedTest.java.ftl" not found.
java.lang.RuntimeException: com.android.tools.idea.templates.FreemarkerUtils$TemplateProcessingException: java.io.FileNotFoundException: Template "root://gradle-projects/NewAndroidModule/root/test/app_package/ExampleInstrumentedTest.java.ftl" not found.
	at com.intellij.util.ExceptionUtil.rethrowAllAsUnchecked(ExceptionUtil.java:177)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:43)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:171)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1003)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:170)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:210)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:119)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:212)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:168)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:151)
	at com.android.tools.idea.templates.Template.runWriteCommandAction(Template.java:349)
	at com.android.tools.idea.templates.Template.doRender(Template.java:367)
	at com.android.tools.idea.templates.Template.lambda$render$0(Template.java:232)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:119)
	at com.android.tools.idea.templates.Template.render(Template.java:232)
	at com.android.tools.idea.npw.module.NewModuleModel$ModuleTemplateRenderer.renderModule(NewModuleModel.java:280)
	at com.android.tools.idea.npw.module.NewModuleModel$ModuleTemplateRenderer.doDryRun(NewModuleModel.java:242)
	at com.android.tools.idea.npw.template.MultiTemplateRenderer.countDown(MultiTemplateRenderer.java:58)
	at com.android.tools.idea.npw.template.MultiTemplateRenderer.skipRender(MultiTemplateRenderer.java:82)
	at com.android.tools.idea.npw.template.RenderTemplateModel.handleSkipped(RenderTemplateModel.java:190)
	at com.android.tools.idea.wizard.model.ModelWizard.handleFinished(ModelWizard.java:409)
	at com.android.tools.idea.wizard.model.ModelWizard.goForward(ModelWizard.java:331)
	at com.android.tools.idea.wizard.model.ModelWizardDialog$FinishAction.doAction(ModelWizardDialog.java:307)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1838)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:734)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:456)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1696)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1645)
	at com.android.tools.idea.actions.AndroidNewProjectAction.actionPerformed(AndroidNewProjectAction.java:60)
	at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:66)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:156)
	at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:79)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:338)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.android.tools.idea.templates.FreemarkerUtils$TemplateProcessingException: java.io.FileNotFoundException: Template "root://gradle-projects/NewAndroidModule/root/test/app_package/ExampleInstrumentedTest.java.ftl" not found.
	at com.android.tools.idea.templates.FreemarkerUtils.processFreemarkerTemplate(FreemarkerUtils.java:114)
	at com.android.tools.idea.templates.recipe.DefaultRecipeExecutor.instantiate(DefaultRecipeExecutor.java:269)
	at com.android.tools.idea.templates.recipe.Recipe$InstantiateInstruction.execute(Recipe.java:172)
	at com.android.tools.idea.templates.recipe.Recipe.executeInstructions(Recipe.java:120)
	at com.android.tools.idea.templates.recipe.Recipe.execute(Recipe.java:105)
	at com.android.tools.idea.templates.Template$4.process(Template.java:568)
	at com.android.tools.idea.templates.FreemarkerUtils.processFreemarkerTemplate(FreemarkerUtils.java:102)
	at com.android.tools.idea.templates.Template.executeRecipeFile(Template.java:557)
	at com.android.tools.idea.templates.Template.access$200(Template.java:73)
	at com.android.tools.idea.templates.Template$3.startElement(Template.java:519)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at com.android.tools.idea.templates.Template.processXml(Template.java:484)
	at com.android.tools.idea.templates.Template.processFile(Template.java:468)
	at com.android.tools.idea.templates.Template.lambda$doRender$2(Template.java:368)
	at com.android.tools.idea.templates.Template$1.run(Template.java:347)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	... 108 more
Caused by: java.io.FileNotFoundException: Template "root://gradle-projects/NewAndroidModule/root/test/app_package/ExampleInstrumentedTest.java.ftl" not found.
	at freemarker.template.Configuration.getTemplate(Configuration.java:742)
	at freemarker.template.Configuration.getTemplate(Configuration.java:665)
	at com.android.tools.idea.templates.FreemarkerUtils.processFreemarkerTemplate(FreemarkerUtils.java:94)
	... 133 more
```
### Steps to reproduce the behavior
* Install `android-studio`
* Start a new project

### Additional notes
* I managed to reproduce the error on a newly created VM running under QEMU/KVM
* Downloading from the Android Studio website and comparing to the installed packages version, some template files are missing from the installed version (e.g.: Activity template files)

**Comment by Vaelatern** [comment]
So the path mostly exists, but the specific file doesn't exist. Not sure if someone else knows this package better.

**Comment by cr6git** [comment]
In the meantime, updated the package: https://github.com/void-linux/void-packages/pull/821

**Comment by noblehelm** [comment]
I tried building it using xbps-src and I noticed that in both builddir and destdir the files are present, before packaging it in the xbps pkg file, and when installing the package these files are gone. I also experimented with replacing some xbps-src commands (e.g.: vcopy, vmkdir, etc..) with the normal ones and the end result was the same. So I can only assume the problem *may* be in the pkg file creation/compression. I will try more tests to see if I can pinpoint where the problem is.

**Comment by Johnnynator** [comment]
Probably related to https://github.com/void-linux/xbps/issues/2 .
Release of new xbps is planned for in ~10 days.

**Comment by noblehelm** [comment]
I've tested the `android-studio-3.1.3_2`, which was built with `xbps-0.53` (with the 127+ long path fix), and it seems that it is fixed. No errors or warning on project creation or activity creation. So I'm closing this.

Thanks in advance.
