### ISSUE TITLE
GIMP 2.10.4_8 crashes on startup

### ISSUE THREAD

**Issue by LucaSeem2000** [void-linux/void-packages#9394]
### System

* xuname:
``Void 4.19.26_1 x86_64-musl GenuineIntel uptodate rrFFFF``
* package:  
``gimp-2.10.4_8``

### Expected behavior
Startup without crash

### Actual behavior
Crash.
Running GIMP in console, I get the following output:
```
gimp: fatal error: Segmentation fault
29      src/thread/x86_64/syscall_cp.s: No such file or directory.
```
And a GIMP bug tracker window pops up with the following bug information:
```
GNU Image Manipulation Program version 2.10.4
git-describe: GIMP_2_10_2-356-ge384409fe5
C compiler:
	Using built-in specs.
	COLLECT_GCC=/usr/bin/cc
	COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-musl/8.3.0/lto-wrapper
	Target: x86_64-linux-musl
	Configured with: /builddir/gcc-8.3.0/configure --build=x86_64-linux-musl --enable-fast-character --disable-libsanitizer --disable-symvers libat_cv_have_ifunc=no --enable-vtable-verify --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --libexecdir=/usr/lib --libdir=/usr/lib --enable-threads=posix --enable-__cxa_atexit --disable-multilib --with-system-zlib --enable-shared --enable-lto --enable-plugins --enable-linker-build-id --disable-werror --disable-nls --enable-default-pie --enable-default-ssp --enable-checking=release --disable-libstdcxx-pch --with-isl --with-linker-hash-style=gnu --disable-libunwind-exceptions --disable-target-libiberty --enable-serial-configure --enable-languages=c,c++,objc,obj-c++,fortran,lto,ada
	Thread model: posix
	gcc version 8.3.0 (GCC) 
	
using GEGL version 0.4.12 (compiled against version 0.4.12)
using GLib version 2.58.3 (compiled against version 2.58.3)
using GdkPixbuf version 2.38.0 (compiled against version 2.38.0)
using GTK+ version 2.24.32 (compiled against version 2.24.32)
using Pango version 1.42.4 (compiled against version 1.42.4)
using Fontconfig version 2.13.1 (compiled against version 2.13.1)
using Cairo version 1.16.0 (compiled against version 1.16.0)

```
> fatal error: Segmentation fault

Stack trace:
```

# Stack traces obtained from PID 1450 - Thread 1450 #

[New LWP 1464]
[New LWP 1469]
[New LWP 1470]
[New LWP 1473]
[New LWP 1480]
__cp_end () at src/thread/x86_64/syscall_cp.s:29
  Id   Target Id         Frame 
* 1    LWP 1450 "gimp"   __cp_end () at src/thread/x86_64/syscall_cp.s:29
  2    LWP 1464 "gmain"  __cp_end () at src/thread/x86_64/syscall_cp.s:29
  3    LWP 1469 "gdbus"  __cp_end () at src/thread/x86_64/syscall_cp.s:29
  4    LWP 1470 "async"  0x00007ff6abcc0159 in __syscall6 (a6=<optimized out>, a5=<optimized out>, a4=<optimized out>, a3=<optimized out>, a2=<optimized out>, a1=<optimized out>, n=<optimized out>) at ./arch/x86_64/syscall_arch.h:59
  5    LWP 1473 "worker" 0x00007ff6abcc0159 in __syscall6 (a6=<optimized out>, a5=<optimized out>, a4=<optimized out>, a3=<optimized out>, a2=<optimized out>, a1=<optimized out>, n=<optimized out>) at ./arch/x86_64/syscall_arch.h:59
  6    LWP 1480 "pool"   0x00007ff6abcc0159 in __syscall6 (a6=<optimized out>, a5=<optimized out>, a4=<optimized out>, a3=<optimized out>, a2=<optimized out>, a1=<optimized out>, n=<optimized out>) at ./arch/x86_64/syscall_arch.h:59

Thread 6 (LWP 1480):
#0  0x00007ff6abcc0159 in __syscall6 (a6=<optimized out>, a5=<optimized out>, a4=<optimized out>, a3=<optimized out>, a2=<optimized out>, a1=<optimized out>, n=<optimized out>) at ./arch/x86_64/syscall_arch.h:59
        ret = <optimized out>
        r10 = 140697272265856
        r8 = 11750
        r9 = 11751
        ret = <optimized out>
        r10 = <optimized out>
        r8 = <optimized out>
        r9 = <optimized out>
#1  syscall (n=<optimized out>) at src/misc/syscall.c:20
        ap = {{gp_offset = 48, fp_offset = 0, overflow_arg_area = 0x7ff6a2ef2c70, reg_save_area = 0x7ff6a2ef2c30}}
        a = 94581635972368
        b = 128
        c = 0
        d = <optimized out>
        e = <optimized out>
        f = <optimized out>
#2  0x00007ff6aa1dd80a in g_cond_wait_until () from /lib/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ff6aa1680c1 in ?? () from /lib/libglib-2.0.so.0
No symbol table info available.
#4  0x00007ff6aa168681 in g_async_queue_timeout_pop () from /lib/libglib-2.0.so.0
No symbol table info available.
#5  0x00007ff6aa1bf461 in ?? () from /lib/libglib-2.0.so.0
No symbol table info available.
#6  0x00007ff6aa1bea25 in ?? () from /lib/libglib-2.0.so.0
No symbol table info available.
#7  0x00007ff6abce9a2e in start (p=<optimized out>) at src/thread/pthread_create.c:144
        self = <optimized out>
#8  0x00007ff6abcf6d96 in __clone () at src/thread/x86_64/clone.s:22
No locals.
Backtrace stopped: frame did not save the PC

Thread 5 (LWP 1473):
#0  0x00007ff6abcc0159 in __syscall6 (a6=<optimized out>, a5=<optimized out>, a4=<optimized out>, a3=<optimized out>, a2=<optimized out>, a1=<optimized out>, n=<optimized out>) at ./arch/x86_64/syscall_arch.h:59
        ret = <optimized out>
        r10 = 0
        r8 = 0
        r9 = 94581613824928
        ret = <optimized out>
        r10 = <optimized out>
        r8 = <optimized out>
        r9 = <optimized out>
#1  syscall (n=<optimized out>) at src/misc/syscall.c:20
        ap = {{gp_offset = 48, fp_offset = 22021, overflow_arg_area = 0x7ff6a2f1fcf0, reg_save_area = 0x7ff6a2f1fcb0}}
        a = 94581613824952
        b = 128
        c = 0
        d = <optimized out>
        e = <optimized out>
        f = <optimized out>
#2  0x00007ff6aa1dd6ef in g_cond_wait () from /lib/libglib-2.0.so.0
No symbol table info available.
#3  0x000056057f44f453 in ?? ()
No symbol table info available.
#4  0x00007ff6aa1bea25 in ?? () from /lib/libglib-2.0.so.0
No symbol table info available.
#5  0x00007ff6abce9a2e in start (p=<optimized out>) at src/thread/pthread_create.c:144
        self = <optimized out>
#6  0x00007ff6abcf6d96 in __clone () at src/thread/x86_64/clone.s:22
No locals.
Backtrace stopped: frame did not save the PC

Thread 4 (LWP 1470):
#0  0x00007ff6abcc0159 in __syscall6 (a6=<optimized out>, a5=<optimized out>, a4=<optimized out>, a3=<optimized out>, a2=<optimized out>, a1=<optimized out>, n=<optimized out>) at ./arch/x86_64/syscall_arch.h:59
        ret = <optimized out>
        r10 = 0
        r8 = 0
        r9 = 94581613828528
        ret = <optimized out>
        r10 = <optimized out>
        r8 = <optimized out>
        r9 = <optimized out>
#1  syscall (n=<optimized out>) at src/misc/syscall.c:20
        ap = {{gp_offset = 48, fp_offset = 0, overflow_arg_area = 0x7ff6a2f4cd00, reg_save_area = 0x7ff6a2f4ccc0}}
        a = 94581613828504
        b = 128
        c = 0
        d = <optimized out>
        e = <optimized out>
        f = <optimized out>
#2  0x00007ff6aa1dd6ef in g_cond_wait () from /lib/libglib-2.0.so.0
No symbol table info available.
#3  0x000056057f44f22a in ?? ()
No symbol table info available.
#4  0x00007ff6aa1bea25 in ?? () from /lib/libglib-2.0.so.0
No symbol table info available.
#5  0x00007ff6abce9a2e in start (p=<optimized out>) at src/thread/pthread_create.c:144
        self = <optimized out>
#6  0x00007ff6abcf6d96 in __clone () at src/thread/x86_64/clone.s:22
No locals.
Backtrace stopped: frame did not save the PC

Thread 3 (LWP 1469):
#0  __cp_end () at src/thread/x86_64/syscall_cp.s:29
No locals.
#1  0x00007ff6abce8c54 in __syscall_cp_c (nr=7, u=<optimized out>, v=<optimized out>, w=<optimized out>, x=<optimized out>, y=<optimized out>, z=0) at src/thread/pthread_cancel.c:33
        self = 0x7ff6a2f99b10
        r = <optimized out>
        st = <optimized out>
#2  0x00007ff6abcd783f in poll (fds=<optimized out>, n=<optimized out>, timeout=<optimized out>) at src/select/poll.c:9
No locals.
#3  0x00007ff6aa195ea6 in ?? () from /lib/libglib-2.0.so.0
No symbol table info available.
#4  0x00007ff6aa196232 in g_main_loop_run () from /lib/libglib-2.0.so.0
No symbol table info available.
#5  0x00007ff6aab10a46 in ?? () from /lib/libgio-2.0.so.0
No symbol table info available.
#6  0x00007ff6aa1bea25 in ?? () from /lib/libglib-2.0.so.0
No symbol table info available.
#7  0x00007ff6abce9a2e in start (p=<optimized out>) at src/thread/pthread_create.c:144
        self = <optimized out>
#8  0x00007ff6abcf6d96 in __clone () at src/thread/x86_64/clone.s:22
No locals.
Backtrace stopped: frame did not save the PC

Thread 2 (LWP 1464):
#0  __cp_end () at src/thread/x86_64/syscall_cp.s:29
No locals.
#1  0x00007ff6abce8c54 in __syscall_cp_c (nr=7, u=<optimized out>, v=<optimized out>, w=<optimized out>, x=<optimized out>, y=<optimized out>, z=0) at src/thread/pthread_cancel.c:33
        self = 0x7ff6a2fc6b10
        r = <optimized out>
        st = <optimized out>
#2  0x00007ff6abcd783f in poll (fds=<optimized out>, n=<optimized out>, timeout=<optimized out>) at src/select/poll.c:9
No locals.
#3  0x00007ff6aa195ea6 in ?? () from /lib/libglib-2.0.so.0
No symbol table info available.
#4  0x00007ff6aa195fcc in g_main_context_iteration () from /lib/libglib-2.0.so.0
No symbol table info available.
#5  0x00007ff6aa196011 in ?? () from /lib/libglib-2.0.so.0
No symbol table info available.
#6  0x00007ff6aa1bea25 in ?? () from /lib/libglib-2.0.so.0
No symbol table info available.
#7  0x00007ff6abce9a2e in start (p=<optimized out>) at src/thread/pthread_create.c:144
        self = <optimized out>
#8  0x00007ff6abcf6d96 in __clone () at src/thread/x86_64/clone.s:22
No locals.
Backtrace stopped: frame did not save the PC

Thread 1 (LWP 1450):
#0  __cp_end () at src/thread/x86_64/syscall_cp.s:29
No locals.
#1  0x00007ff6abce8c54 in __syscall_cp_c (nr=0, u=<optimized out>, v=<optimized out>, w=<optimized out>, x=<optimized out>, y=<optimized out>, z=0) at src/thread/pthread_cancel.c:33
        self = 0x560580c4bc58
        r = <optimized out>
        st = <optimized out>
#2  0x00007ff6abcf11af in read (fd=<optimized out>, buf=<optimized out>, count=<optimized out>) at src/unistd/read.c:6
No locals.
#3  0x00007ff6ab693e3e in gimp_stack_trace_print () from /lib/libgimpbase-2.0.so.0
No symbol table info available.
#4  0x000056057f1942d0 in ?? ()
No symbol table info available.
#5  0x000056057f19470a in gimp_fatal_error ()
No symbol table info available.
#6  0x000056057f194e57 in ?? ()
No symbol table info available.
#7  <signal handler called>
No locals.
#8  strcmp (l=l@entry=0x0, r=0x7ff6a6a98b83 "Unified transform") at src/string/strcmp.c:5
No locals.
#9  0x00007ff6abca3c31 in __mo_lookup (p=0x7ff6a6a7b000, size=264942, s=s@entry=0x0) at src/locale/__mo_lookup.c:25
        ol = <optimized out>
        os = <optimized out>
        sign = <optimized out>
        mo = 0x7ff6a6a7b000
        sw = <optimized out>
        b = 0
        n = 3346
        o = 7
        t = 6699
#10 0x00007ff6abca4070 in dcngettext (domainname=<optimized out>, msgid1=0x0, msgid2=0x0, n=1, category=5) at src/locale/dcngettext.c:236
        cats = 0x560580f02a00
        p = 0x7ff6abd2e900
        loc = <optimized out>
        lm = 0x560580c62ba0
        domlen = <optimized out>
        q = <optimized out>
        trans = <optimized out>
#11 0x000056057f1cdc1d in dialogs_init ()
No symbol table info available.
#12 0x000056057f196b8f in ?? ()
No symbol table info available.
#13 0x00007ff6aa2769dd in g_closure_invoke () from /lib/libgobject-2.0.so.0
No symbol table info available.
#14 0x00007ff6aa289b33 in ?? () from /lib/libgobject-2.0.so.0
No symbol table info available.
#15 0x00007ff6aa292b4a in g_signal_emit_valist () from /lib/libgobject-2.0.so.0
No symbol table info available.
#16 0x00007ff6aa29319f in g_signal_emit () from /lib/libgobject-2.0.so.0
No symbol table info available.
#17 0x000056057f446261 in gimp_restore ()
No symbol table info available.
#18 0x000056057f193c4b in app_run ()
No symbol table info available.
#19 0x000056057f193358 in main ()
No symbol table info available.
[Inferior 1 (process 1450) detached]

```

### Steps to reproduce the behavior
Open the program using dmenu or on a command line

**Comment by LucaSeem2000** [comment]
No.

This is the latest version of GIMP.
I also have to use flatpak to get GIMP working

**Comment by jnbr** [comment]
Couldn't reproduce.
GIMP was updated to 2.10.10, please re-open if it still isn't working for you.
