### ISSUE TITLE
yoshimi crashes with segmentation fault on musl systems

### ISSUE THREAD

**Issue by newbluemoon** [void-linux/void-packages#980]
### System

* xuname:  
  Void 4.14.52_1 armv7l-musl  uptodate rrrnDDDFFFFFF
* package:  
  yoshimi 1.5.8.2_1

### Expected behavior
normal startup
### Actual behavior
crashes with segmentation fault when CLI is loaded
### Steps to reproduce the behavior
just install and start

The crash seems to happen within ncurses when the CLI is loaded. When the CLI is disabled via `yoshimi -c` everything works normal.

I tried old versions down to 1.5.4.1_2 (which worked 100%), all with the same result so I assume this isn’t an upstream issue. Also tested it in a x86_64-musl chroot, to no avail.

Here’s a backtrace:

```
(gdb) bt full
#0  _nc_read_termtype (ptr=0x14e0f8c, buffer=0x75f6a1d8 "\032\001N", limit=2239) at ../../ncurses/tinfo/read_entry.c:273
        offset = <optimized out>
        name_size = <optimized out>
        bool_count = <optimized out>
        num_count = <optimized out>
        str_count = <optimized out>
        str_size = <optimized out>
        i = <optimized out>
        buf = <error reading variable buf (Cannot access memory at address 0x75f621a8)>
        string_table = <optimized out>
        want = <optimized out>
        have = <optimized out>
        need_ints = <optimized out>
        convert_numbers = <optimized out>
        size_of_numbers = <optimized out>
        max_entry_size = <optimized out>
#1  0x76b149a8 in _nc_read_file_entry (filename=<optimized out>, ptr=0x14e0f8c) at ../../ncurses/tinfo/read_entry.c:547
        limit = <optimized out>
        buffer = "\032\001N\000\035\000\037\000p\001)\005rxvt-unicode-256color|rxvt-unicode terminal with 256 colors (X Window System)\000\001\001\000\000\001\001\000\000\001\001\000\000\000\001\001\000\000\000\000\000\001\000\001\000\000\001\000\001\001\000P\000\b\000\030\000\000\000", '\377' <repeats 18 times>, "\000\001\377\177\000\000", '\377' <repeats 28 times>, "\005\000\377\377\000\000\002\000\004\000\025\000\032\000\"\000&\000*\000"...
        fp = 0x765d9a00
        code = <optimized out>
#2  0x76b14c38 in _nc_read_tic_entry (filename=0x76fff0d8 <__stack_chk_guard> "\035\001Oeְ?", 
    filename@entry=0x75f7a284 "/usr/share/terminfo/r/rxvt-unicode-256color", path=0x14e1020 "/usr/share/terminfo", 
    name=name@entry=0x7efffa6f "rxvt-unicode-256color", tp=0x0, tp@entry=0x14e0f8c, limit=4096) at ../../ncurses/tinfo/read_entry.c:798
        code = 0
        buffer = '\000' <repeats 31368 times>...
        used = <optimized out>
#3  0x76b14e38 in _nc_read_entry2 (name=0x7efffa6f "rxvt-unicode-256color", filename=0x75f7a284 "/usr/share/terminfo/r/rxvt-unicode-256color", 
    filename@entry=0x75f7a27c "\354\341\260v", tp=tp@entry=0x14e0f8c) at ../../ncurses/tinfo/read_entry.c:839
        state = dbdEnvOnce
        offset = 0
        path = <optimized out>
        tp = 0x14e0f8c
        state = <optimized out>
        filename = 0x75f7a284 "/usr/share/terminfo/r/rxvt-unicode-256color"
        name = 0x7efffa6f "rxvt-unicode-256color"
        code = <optimized out>
        offset = <optimized out>
        path = <optimized out>
        state = <optimized out>
        offset = <optimized out>
        path = <optimized out>
#4  0x76b0e1ec in _nc_setup_tinfo (tn=<optimized out>, tp=0x14e0f8c) at ../../ncurses/tinfo/lib_setup.c:482
        filename = "/usr/share/terminfo/r/rxvt-unicode-256color", '\000' <repeats 2625 times>...
        status = <optimized out>
        n = <optimized out>
#5  0x76b0e52c in _nc_setupterm (tname=tname@entry=0x7efffa6f "rxvt-unicode-256color", Filedes=Filedes@entry=1, errret=0x75f7b2c0, errret@entry=0x75f7b2b8, 
    reuse=reuse@entry=1) at ../../ncurses/tinfo/lib_setup.c:732
        status = <optimized out>
        termp = 0x14e0ee0
        sp = 0x0
        code = -1
#6  0x76b0e9a4 in tgetent_sp (sp=0x0, bufp=0x14f7920 "\230\325\377v\230\325\377v\260\020N\001P\020N\001", name=name@entry=0x7efffa6f "rxvt-unicode-256color")
    at ../../ncurses/tinfo/lib_termcap.c:103
        rc = -1
        n = <optimized out>
#7  0x76b0ef08 in tgetent (bufp=<optimized out>, name=name@entry=0x7efffa6f "rxvt-unicode-256color") at ../../ncurses/tinfo/lib_termcap.c:211
No locals.
#8  0x76ab8b40 in _rl_init_terminal_io (terminal_name=<optimized out>) at ../terminal.c:488
        term = 0x7efffa6f "rxvt-unicode-256color"
        buffer = 0x1622bc0 "H\325\377vH\325\377v\266"
        tty = <optimized out>
        tgetent_ret = <optimized out>
#9  0x76a9e3e4 in readline_initialize_everything () at ../readline.c:1199
No locals.
#10 rl_initialize () at ../readline.c:1101
No locals.
#11 0x76a9e6d0 in readline (prompt=<optimized out>) at ../readline.c:368
        value = <optimized out>
#12 0x0044bb80 in CmdInterface::cmdIfaceCommandLoop (this=0x5eb674 <commandInt>) at /builddir/yoshimi-1.5.8.2/src/Interface/CmdInterface.cpp:2988
        hist_filename = {static npos = 4294967295, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0x157d090 "/home/user/.yoshimi_history"}, _M_string_length = 27, {_M_local_buf = "\036", '\000' <repeats 14 times>, 
            _M_allocated_capacity = 30}}
        exit = false
#13 0x00591c00 in commandThread (arg=<optimized out>) at /builddir/yoshimi-1.5.8.2/src/main.cpp:333
No locals.
#14 0x76fb312c in start (p=0x75f7b584) at src/thread/pthread_create.c:150
        self = 0x75f7b584
#15 0x76fb1470 in __clone () at src/thread/arm/clone.s:25
No locals.
#16 0x76fb1470 in __clone () at src/thread/arm/clone.s:25
No locals.
#17 0x76fb1470 in __clone () at src/thread/arm/clone.s:25
No locals.
...
```

**Comment by Johnnynator** [comment]
To lazy to read the backtrace, but it works with musl build with the bigstack build option so it is also stacksize related.

**Comment by Johnnynator** [comment]
This patch should do it, but I don't know anything about pthread to know if this is correct code or not, but it did work locally for me.
```
--- src/main.cpp	2018-06-05 10:05:52.000000000 +0200
+++ -	2018-07-17 17:37:04.558497267 +0200
@@ -411,6 +411,9 @@
     {
         if (pthread_attr_init(&attr) == 0)
         {
+            #ifndef __GLIBC__
+		pthread_attr_setstacksize(&attr, 8388608);
+            #endif
             if (pthread_create(&cmdThr, &attr, commandThread, (void *)firstSynth) == 0)
             {
```

**Comment by newbluemoon** [comment]
Thanks, @Johnnynator! I’ll test your patch and see if I’m running into any problem. I’m just wondering why it worked in the past without the bigstack. However, I think the last time I used it musl was at 1.1.18.

**Comment by Johnnynator** [comment]
@newbluemoon any feedback wether the patch did work fine or not?

**Comment by newbluemoon** [comment]
Sorry, @Johnnynator haven’t gotten to it, yet. I’ll build it right now and let you know. :)

**Comment by newbluemoon** [comment]
It works with a bigstack enabled musl, however.

**Comment by newbluemoon** [comment]
No, that’s not true. It just worked the first time I tried, but afterwards not anymore. Strange.
Still, when disabling the CLI everything is fine. I just can’t tell if creating a new instance ever worked on musl. I’m not using yoshimi regularly, just playing around with it from time to time.

**Comment by Johnnynator** [comment]
For me creating a new instance even fails with bigstack sometimes, it feels somewhat random.

**Comment by maxice8** [comment]
ping

**Comment by newbluemoon** [comment]
Didn’t make any progress, but it’s been a while since I tried. I’ll try to make some time this weekend to have another look. :)

**Comment by newbluemoon** [comment]
Finally got around to do some (limited) testing again and the issues at hand seem to have been resolved. Didn’t encounter any new problem. :)

So I guess this can be close now.
