### ISSUE TITLE
rustc segfaults on aarch64-musl (running on a raspberry pi model 3b+)

### ISSUE THREAD

**Issue by sug0** [void-linux/void-packages#9973]
### System

* xuname:  
```
dmesg: read kernel buffer failed: No such file or directory
Void 4.19.23_1 aarch64-musl  uptodate rFFF
```
* package:  
```
rust-1.32.0_1
```

### Expected behavior

I expect `rustc` to compile a program.

### Actual behavior

`rustc` SEGFAULTs.

### Steps to reproduce the behavior

Try to compile *any* rust program...

### P.S.

Maybe `rustc` is trying to look up some GNU symbols? Since we're on musl, that could be the cause of the SEGFAULT...

![](https://0x0.st/z8Bz.png)

**Comment by jnbr** [comment]
can reproduce, same with rust-133.0

**Comment by jnbr** [comment]
Unfortunately, rust-dbg has no debug symbols on aarch64-musl (neither on aarch64). rust-std-dbg has symbols, so here is a limited backtrace:

```
Thread 1 "rustc" received signal SIGSEGV, Segmentation fault.
0x0000007fbd277e10 in <std::thread::local::LocalKey<T>>::with () from /lib/librustc_data_structures-0b61523a70aae914.so
(gdb) bt
#0  0x0000007fbd277e10 in <std::thread::local::LocalKey<T>>::with () from /lib/librustc_data_structures-0b61523a70aae914.so
#1  0x0000007fbcfeacb0 in tempfile::util::tmpname () from /usr/lib/rustlib/aarch64-unknown-linux-musl/codegen-backends/librustc_codegen_llvm-llvm.so
#2  0x0000007fbcfeaeec in tempfile::util::create_helper () from /usr/lib/rustlib/aarch64-unknown-linux-musl/codegen-backends/librustc_codegen_llvm-llvm.so
#3  0x0000007fbcfeb7e4 in tempfile::Builder::tempdir () from /usr/lib/rustlib/aarch64-unknown-linux-musl/codegen-backends/librustc_codegen_llvm-llvm.so
#4  0x0000007fbcf2cb00 in rustc_codegen_llvm::back::link::link_binary ()
   from /usr/lib/rustlib/aarch64-unknown-linux-musl/codegen-backends/librustc_codegen_llvm-llvm.so
#5  0x0000007fbcf573cc in <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::join_codegen_and_link::{{closure}}
    () from /usr/lib/rustlib/aarch64-unknown-linux-musl/codegen-backends/librustc_codegen_llvm-llvm.so
#6  0x0000007fbcf48d6c in rustc::util::common::time () from /usr/lib/rustlib/aarch64-unknown-linux-musl/codegen-backends/librustc_codegen_llvm-llvm.so
#7  0x0000007fbcf73b9c in <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::join_codegen_and_link ()
   from /usr/lib/rustlib/aarch64-unknown-linux-musl/codegen-backends/librustc_codegen_llvm-llvm.so
#8  0x0000007fbf4ac8d4 in rustc_driver::driver::compile_input () from /lib/librustc_driver-3a6798c136535483.so
#9  0x0000007fbf5666b0 in rustc_driver::run_compiler_with_pool () from /lib/librustc_driver-3a6798c136535483.so
#10 0x0000007fbf4b377c in <scoped_tls::ScopedKey<T>>::set () from /lib/librustc_driver-3a6798c136535483.so
#11 0x0000007fbf56595c in rustc_driver::run_compiler () from /lib/librustc_driver-3a6798c136535483.so
#12 0x0000007fbf4ccb7c in rustc_driver::monitor::{{closure}} () from /lib/librustc_driver-3a6798c136535483.so
#13 0x0000007fbf39dc7c in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:102
#14 0x0000007fbf56427c in rustc_driver::run () from /lib/librustc_driver-3a6798c136535483.so
#15 0x0000007fbf56ecc0 in rustc_driver::main () from /lib/librustc_driver-3a6798c136535483.so
#16 0x00000055555559e0 in std::rt::lang_start::{{closure}} ()
#17 0x0000007fbf392ea0 in std::rt::lang_start_internal::{{closure}} () at src/libstd/rt.rs:59
#18 std::panicking::try::do_call () at src/libstd/panicking.rs:310
#19 0x0000007fbf39dc7c in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:102
#20 0x0000007fbf3784fc in std::panicking::try () at src/libstd/panicking.rs:289
#21 std::panic::catch_unwind () at src/libstd/panic.rs:398
#22 std::rt::lang_start_internal () at src/libstd/rt.rs:58
#23 0x00000055555559cc in main ()
```

**Comment by jnbr** [comment]
The update to rust-1.34.0 which also brings llvm8 fixes this.
